"""
PIRTM Transpiler CLI: Compile descriptors to various backends.

Usage:
    pirtm transpile --input descriptor.yaml --output mlir
    pirtm transpile --input descriptor.yaml --output numpy
    pirtm inspect recurrence.pirtm.bc
"""

import argparse
import sys
import json
from importlib import import_module
from pathlib import Path
from typing import Dict, Any

# Internal imports
from pirtm.transpiler.mlir_lowering import MLIREmitter, MLIRConfig


class PirtmCLI:
    """PIRTM command-line interface."""
    
    def __init__(self):
        self.parser = self._build_parser()
    
    def _build_parser(self) -> argparse.ArgumentParser:
        """Build argument parser."""
        parser = argparse.ArgumentParser(
            prog="pirtm",
            description="PIRTM Transpiler: Compile recurrence descriptors to verified code.",
            formatter_class=argparse.RawDescriptionHelpFormatter,
            epilog="""
Examples:
  # Transpile YAML descriptor to MLIR
  pirtm transpile --input policy.yaml --output mlir --epsilon 0.05

  # Transpile with witness hash from ACE
  pirtm transpile \\
    --input policy.yaml \\
    --output mlir \\
    --trace-id "session_abc123" \\
    --witness-hash poseidon

  # Inspect compiled binary
  pirtm inspect compiled.pirtm.bc

  # Show contractivity metadata
  pirtm inspect --meta compiled.pirtm.bc
            """,
        )
        
        subparsers = parser.add_subparsers(dest="command", help="Command to run")
        
        # === transpile command ===
        transpile = subparsers.add_parser(
            "transpile",
            help="Transpile recurrence descriptor to target backend",
        )
        
        transpile.add_argument(
            "--input", "-i",
            type=str,
            required=True,
            help="Input descriptor file (YAML or JSON)",
        )
        
        transpile.add_argument(
            "--output", "-o",
            type=str,
            choices=["mlir", "numpy", "llvm", "circom"],
            default="mlir",
            help="Target compilation backend (default: mlir)",
        )
        
        transpile.add_argument(
            "--epsilon", "-e",
            type=float,
            default=0.05,
            help="Contractivity margin (default: 0.05)",
        )
        
        transpile.add_argument(
            "--confidence", "-c",
            type=float,
            default=0.9999,
            help="Confidence level (default: 0.9999)",
        )
        
        transpile.add_argument(
            "--op-norm-T",
            type=float,
            default=1.0,
            help="Operator norm of transformation T (default: 1.0)",
        )
        
        transpile.add_argument(
            "--prime-index",
            type=int,
            default=17,
            help="Prime modulus index (default: 17)",
        )
        
        transpile.add_argument(
            "--trace-id",
            type=str,
            help="ACE witness trace ID (optional)",
        )
        
        transpile.add_argument(
            "--witness-hash",
            type=str,
            choices=["poseidon", "sha256"],
            default="poseidon",
            help="Witness hash algorithm (default: poseidon)",
        )
        
        transpile.add_argument(
            "--outfile",
            type=str,
            help="Output file path (default: based on input + format)",
        )
        
        transpile.add_argument(
            "--emit-diag",
            action="store_true",
            help="Emit mlir-opt diagnostic header (for verification)",
        )
        
        transpile.set_defaults(func=self.cmd_transpile)
        
        # === inspect command ===
        inspect = subparsers.add_parser(
            "inspect",
            help="Inspect compiled PIRTM binary or MLIR file",
        )
        
        inspect.add_argument(
            "file",
            type=str,
            help="PIRTM binary (.pirtm.bc) or MLIR file (.mlir)",
        )
        
        inspect.add_argument(
            "--meta",
            action="store_true",
            help="Show contractivity metadata only",
        )
        
        inspect.add_argument(
            "--verify",
            action="store_true",
            help="Verify contractivity bounds",
        )
        
        inspect.set_defaults(func=self.cmd_inspect)
        
        # === audit command ===
        audit = subparsers.add_parser(
            "audit",
            help="Inspect an audit trace log (JSONL) generated by PIRTM operations",
        )
        audit.add_argument(
            "trace_log",
            type=str,
            help="Path to audit trace log (JSONL)",
        )
        audit.add_argument(
            "--limit",
            type=int,
            default=0,
            help="Limit number of events printed (0 = all)",
        )
        audit.set_defaults(func=self.cmd_audit)

        # === clone-check command ===
        clone_check = subparsers.add_parser(
            "clone-check",
            help="Run clone-check automation on candidate vs reference code",
        )
        clone_check.add_argument(
            "--candidate",
            type=str,
            required=True,
            help="Path to candidate source file",
        )
        clone_check.add_argument(
            "--reference",
            type=str,
            required=True,
            help="Path to reference source file",
        )
        clone_check.add_argument(
            "--output",
            type=str,
            help="Optional output JSON report path",
        )
        clone_check.set_defaults(func=self.cmd_clone_check)

        # === badge command ===
        badge = subparsers.add_parser(
            "badge",
            help="Manage PMD badge registry (issue/revoke/status/list)",
        )
        badge.add_argument("command", choices=["issue", "revoke", "status", "list"], help="Badge command")
        badge.add_argument("--registry", required=True, help="Path to badge registry JSON")
        badge.add_argument("--id", help="Badge ID (for status/revoke)")
        badge.add_argument("--module", help="Module name to badge")
        badge.add_argument("--prime", type=int, help="Prime index for badge")
        badge.add_argument("--issuer", help="Issuer identity")
        badge.add_argument("--reason", help="Revocation reason")
        badge.add_argument("--certificate-id", help="Certificate ID")
        badge.add_argument("--clone-check-id", help="Clone-check result ID")
        badge.add_argument("--audit-trace", help="Audit trace URL/Path")
        badge.add_argument(
            "--clone-check-report",
            help="Path to clone-check JSON report (required for issuance)",
        )
        badge.add_argument("--metadata", help="Optional JSON metadata")
        badge.add_argument("--all", action="store_true", help="List all badges (including revoked)")
        badge.set_defaults(func=self.cmd_badge)

        # === certify command ===
        certify = subparsers.add_parser(
            "certify",
            help="Run full certification pipeline: clone-check + audit trace validation + badge issuance",
        )
        certify.add_argument("--candidate", required=True, help="Candidate source file")
        certify.add_argument("--reference", required=True, help="Reference source file")
        certify.add_argument(
            "--audit-trace",
            required=False,
            help="Optional path to audit trace JSONL (auto-generated if omitted)",
        )
        certify.add_argument("--registry", required=True, help="Badge registry JSON path")
        certify.add_argument("--module", required=True, help="Module name for badge")
        certify.add_argument("--prime", type=int, required=True, help="Prime index for badge")
        certify.add_argument("--issuer", required=True, help="Issuer identity")
        certify.add_argument("--certificate-id", help="Optional certificate ID")
        certify.add_argument("--metadata", help="Optional JSON metadata")
        certify.add_argument(
            "--generate-invariant",
            help="Optional invariant spec JSON to pass through pirtm iag as part of certification",
        )
        certify.add_argument(
            "--iag-registry",
            default="pirtm/docs/PRIME_FREQUENCY_INTEGRITY_SUITE.md",
            help="Registry markdown path used when generating an invariant",
        )
        certify.add_argument(
            "--iag-output-root",
            default=".",
            help="Output root under which pirtm iag writes generated artifacts",
        )
        certify.add_argument(
            "--iag-meta-ensemble-log",
            default="pirtm/docs/META_ENSEMBLE_LOG.md",
            help="Meta-ensemble markdown log path used when generating an invariant",
        )
        certify.add_argument(
            "--iag-assembly-record",
            help="Optional structured assembly record path used when generating an invariant",
        )
        certify.add_argument(
            "--meta-ensemble-ledger",
            help="Optional ensemble ledger SQLite path used to emit fold/retract provenance sidecars",
        )
        certify.add_argument(
            "--meta-ensemble-sidecar-dir",
            help="Optional directory for emitted fold/retract provenance sidecars",
        )
        certify.add_argument(
            "--strict",
            action="store_true",
            help="Fail if an existing audit trace mismatches expected deterministic trace",
        )
        certify.set_defaults(func=self.cmd_certify)

        # === iag command ===
        iag = subparsers.add_parser(
            "iag",
            help="Generate scaffold artifacts (test + binding + registry entry) from an invariant spec",
        )
        iag.add_argument("--spec", required=True, help="Invariant spec JSON file")
        iag.add_argument(
            "--registry",
            default="pirtm/docs/PRIME_FREQUENCY_INTEGRITY_SUITE.md",
            help="Path to registry markdown file",
        )
        iag.add_argument(
            "--output-root",
            default=".",
            help="Root directory under which generated pirtm artifacts are written",
        )
        iag.add_argument(
            "--meta-ensemble-log",
            default="pirtm/docs/META_ENSEMBLE_LOG.md",
            help="Path to the meta-ensemble markdown log to update",
        )
        iag.add_argument(
            "--assembly-record",
            help="Optional path to structured assembly record JSON",
        )
        iag.set_defaults(func=self.cmd_iag)

        # === acf-review command ===
        acf_review = subparsers.add_parser(
            "acf-review",
            help="Emit reviewer-facing ADR-029 ACF summary JSON for a named fixture",
        )
        acf_review.add_argument(
            "--fixture",
            required=True,
            choices=[
                "certified-tail",
                "overlapping-tail",
                "mixed-size",
                "four-edge-mixed",
                "high-fractional-direct",
            ],
            help="Named ADR-029 fixture to summarize",
        )
        acf_review.add_argument(
            "--output",
            help="Optional output JSON path",
        )
        acf_review.add_argument(
            "--pretty",
            action="store_true",
            help="Pretty-print JSON output",
        )
        acf_review.set_defaults(func=self.cmd_acf_review)

        # === helix-hamiltonian command ===
        helix = subparsers.add_parser(
            "helix-hamiltonian",
            help="Construct and print a HELIX Hamiltonian matrix for given parameters",
        )
        helix.add_argument("--knot-type", type=str, default="3_1", help="Knot type (default: 3_1)")
        helix.add_argument("--n-qubits", type=int, default=1, help="Number of qubits (default: 1)")
        helix.add_argument("--omega-z", type=float, default=1.0, help="Omega_z parameter (default: 1.0)")
        helix.add_argument("--omega-fold", type=float, default=0.5, help="Omega_fold parameter (default: 0.5)")
        helix.add_argument("--lambda-topo", type=float, default=0.3, help="Lambda_topo parameter (default: 0.3)")
        helix.set_defaults(func=self.cmd_helix_hamiltonian)

        # === link command ===
        link = subparsers.add_parser(
            "link",
            help="Link PIRTM modules and verify network contractivity/entanglement",
        )
        link.add_argument(
            "--coupling", "-c",
            type=str,
            required=True,
            help="Path to coupling.json configuration",
        )
        link.add_argument(
            "--check-entanglement",
            action="store_true",
            help="Run ADR-021 Phase 2 Ξ(t) entanglement verification",
        )
        link.add_argument(
            "--link-time",
            type=float,
            default=1.0,
            help="Time parameter for Ξ(t) evolution (default: 1.0)",
        )
        link.add_argument(
            "--verify-all",
            action="store_true",
            help="Verify all sessions in the coupling configuration",
        )
        link.set_defaults(func=self.cmd_link)

        return parser
    
    def cmd_transpile(self, args: argparse.Namespace) -> int:
        """Execute transpile command."""
        try:
            # Load descriptor
            descriptor = self._load_descriptor(args.input)
            
            # Route to appropriate backend
            if args.output == "mlir":
                return self._transpile_to_mlir(descriptor, args)
            elif args.output == "numpy":
                return self._transpile_to_numpy(descriptor, args)
            else:
                print(f"Error: Backend '{args.output}' not yet implemented", file=sys.stderr)
                return 1
        
        except Exception as e:
            print(f"Error: {e}", file=sys.stderr)
            return 1
    
    def _transpile_to_mlir(self, descriptor: Dict[str, Any], args: argparse.Namespace) -> int:
        """Transpile descriptor to MLIR."""
        # Extract metadata
        config = MLIRConfig(
            epsilon=args.epsilon,
            confidence=args.confidence,
            op_norm_T=args.op_norm_T,
            prime_index=args.prime_index,
            emit_witness_hash=bool(args.trace_id),
            witness_hash_type=args.witness_hash,
        )
        
        emitter = MLIREmitter(config=config)
        
        # Emit MLIR
        mlir_code = emitter.emit_module(
            policy_name=descriptor.get("policy", "CarryForward"),
            kernel_name=descriptor.get("kernel", "FullAsymmetricAttribution"),
            trace_id=args.trace_id,
            dimension=descriptor.get("dimension", 512),
        )
        
        # Optional diagnostic header
        if args.emit_diag:
            diag = emitter.emit_diagnostics_header()
            mlir_code = diag + "\n\n" + mlir_code
        
        # Determine output file
        outfile = args.outfile or self._default_output_path(args.input, "mlir")
        
        # Write to file
        with open(outfile, "w") as f:
            f.write(mlir_code)
        
        print(f"✅ Transpiled to MLIR: {outfile}")
        print(f"   Epsilon: {args.epsilon}")
        print(f"   Confidence: {args.confidence}")
        
        if args.trace_id:
            print(f"   Witness ID: {args.trace_id}")
        
        return 0
    
    def _transpile_to_numpy(self, descriptor: Dict[str, Any], args: argparse.Namespace) -> int:
        """Transpile descriptor to NumPy (symbolic IR)."""
        # For now, just output descriptor as annotated JSON
        outfile = args.outfile or self._default_output_path(args.input, "numpy.json")
        
        output: Dict[str, Any] = {
            "format": "numpy-symbolic-ir",
            "descriptor": descriptor,
            "config": {
                "epsilon": args.epsilon,
                "confidence": args.confidence,
                "op_norm_T": args.op_norm_T,
                "prime_index": args.prime_index,
            },
        }
        
        with open(outfile, "w") as f:
            json.dump(output, f, indent=2)
        
        print(f"✅ Transpiled to NumPy IR: {outfile}")
        return 0
    
    def cmd_inspect(self, args: argparse.Namespace) -> int:
        """Execute inspect command."""
        try:
            filepath = Path(args.file)
            
            if not filepath.exists():
                print(f"Error: File not found: {args.file}", file=sys.stderr)
                return 1
            
            if filepath.suffix == ".mlir":
                return self._inspect_mlir(filepath, args)
            elif filepath.suffix == ".bc":
                return self._inspect_bytecode(filepath, args)
            else:
                print(f"Error: Unknown file format: {filepath.suffix}", file=sys.stderr)
                return 1
        
        except Exception as e:
            print(f"Error: {e}", file=sys.stderr)
            return 1

    def cmd_audit(self, args: argparse.Namespace) -> int:
        """Execute audit command."""
        try:
            pirtm_audit = import_module("pirtm.tools.pirtm_audit")
            return pirtm_audit.main([args.trace_log, "--limit", str(args.limit)])
        except Exception as e:
            print(f"Error: {e}", file=sys.stderr)
            return 1

    def cmd_clone_check(self, args: argparse.Namespace) -> int:
        """Execute clone-check command."""
        try:
            pirtm_clone_check = import_module("pirtm.tools.pirtm_clone_check")
            return pirtm_clone_check.main([
                "--candidate",
                args.candidate,
                "--reference",
                args.reference,
                "--output",
                args.output if args.output else "",
            ])
        except Exception as e:
            print(f"Error: {e}", file=sys.stderr)
            return 1

    def cmd_badge(self, args: argparse.Namespace) -> int:
        """Execute badge registry command."""
        try:
            pirtm_badge = import_module("pirtm.tools.pirtm_badge")
            # Dispatch to pirtm_badge CLI with the correct args
            cmd = [
                args.command,
                "--registry",
                args.registry,
            ]
            if args.command == "issue":
                cmd += [
                    "--module", args.module,
                    "--prime", str(args.prime),
                    "--issuer", args.issuer,
                ]
                if args.certificate_id:
                    cmd += ["--certificate-id", args.certificate_id]
                if args.clone_check_report:
                    cmd += ["--clone-check-report", args.clone_check_report]
                if args.audit_trace:
                    cmd += ["--audit-trace", args.audit_trace]
                if args.metadata:
                    cmd += ["--metadata", args.metadata]
            elif args.command == "revoke":
                cmd += [
                    "--id", args.id,
                    "--reason", args.reason,
                    "--issuer", args.issuer,
                ]
            elif args.command == "status":
                cmd += ["--id", args.id]
            elif args.command == "list":
                if args.all:
                    cmd += ["--all"]

            return pirtm_badge.main(cmd)
        except Exception as e:
            print(f"Error: {e}", file=sys.stderr)
            return 1

    def cmd_certify(self, args: argparse.Namespace) -> int:
        """Execute certification pipeline command."""
        try:
            pirtm_certify = import_module("pirtm.tools.pirtm_certify")
            cmd = [
                "--candidate",
                args.candidate,
                "--reference",
                args.reference,
            ]
            if args.audit_trace:
                cmd += ["--audit-trace", args.audit_trace]
            cmd += [
                "--registry",
                args.registry,
                "--module",
                args.module,
                "--prime",
                str(args.prime),
                "--issuer",
                args.issuer,
            ]
            if args.certificate_id:
                cmd += ["--certificate-id", args.certificate_id]
            if args.metadata:
                cmd += ["--metadata", args.metadata]
            if getattr(args, "strict", False):
                cmd += ["--strict"]
            if getattr(args, "generate_invariant", None):
                cmd += ["--generate-invariant", args.generate_invariant]
                cmd += ["--iag-registry", getattr(args, "iag_registry", "pirtm/docs/PRIME_FREQUENCY_INTEGRITY_SUITE.md")]
                cmd += ["--iag-output-root", getattr(args, "iag_output_root", ".")]
                cmd += ["--iag-meta-ensemble-log", getattr(args, "iag_meta_ensemble_log", "pirtm/docs/META_ENSEMBLE_LOG.md")]
                if getattr(args, "iag_assembly_record", None):
                    cmd += ["--iag-assembly-record", args.iag_assembly_record]
            if getattr(args, "meta_ensemble_ledger", None):
                cmd += ["--meta-ensemble-ledger", args.meta_ensemble_ledger]
            if getattr(args, "meta_ensemble_sidecar_dir", None):
                cmd += ["--meta-ensemble-sidecar-dir", args.meta_ensemble_sidecar_dir]

            return pirtm_certify.main(cmd)
        except Exception as e:
            print(f"Error: {e}", file=sys.stderr)
            return 1

    def cmd_link(self, args: argparse.Namespace) -> int:
        """Execute link command."""
        try:
            pirtm_link = import_module("pirtm.tools.pirtm_link")
            cmd = ["--coupling", args.coupling]
            if args.check_entanglement:
                cmd += ["--check-entanglement"]
            if args.link_time != 1.0:
                cmd += ["--link-time", str(args.link_time)]
            if args.verify_all:
                cmd += ["--verify-all"]
            return pirtm_link.main(cmd)
        except Exception as e:
            print(f"Error: {e}", file=sys.stderr)
            return 1

    def cmd_iag(self, args: argparse.Namespace) -> int:
        """Execute invariant-to-artifact generator command."""
        try:
            pirtm_iag = import_module("pirtm.tools.pirtm_iag")
            return pirtm_iag.main([
                "--spec",
                args.spec,
                "--registry",
                args.registry,
                "--output-root",
                args.output_root,
                "--meta-ensemble-log",
                args.meta_ensemble_log,
                *(["--assembly-record", args.assembly_record] if args.assembly_record else []),
            ])
        except Exception as e:
            print(f"Error: {e}", file=sys.stderr)
            return 1

    def cmd_acf_review(self, args: argparse.Namespace) -> int:
        """Execute ADR-029 reviewer summary command."""
        try:
            pirtm_acf_review = import_module("pirtm.tools.pirtm_acf_review")
            cmd = ["--fixture", args.fixture]
            if getattr(args, "output", None):
                cmd += ["--output", args.output]
            if getattr(args, "pretty", False):
                cmd += ["--pretty"]
            return pirtm_acf_review.main(cmd)
        except Exception as e:
            print(f"Error: {e}", file=sys.stderr)
            return 1

    def cmd_helix_hamiltonian(self, args: argparse.Namespace) -> int:
        """Invoke HELIX Hamiltonian construction and print the matrix."""
        try:
            from pirtm.integrations.helix_adapter import helix_hamiltonian_matrix

            mat = helix_hamiltonian_matrix(
                knot_type=args.knot_type,
                n_qubits=args.n_qubits,
                omega_z=args.omega_z,
                omega_fold=args.omega_fold,
                lambda_topo=args.lambda_topo,
            )
            print(f"Constructed HELIX Hamiltonian matrix for knot {args.knot_type}:")
            print(mat)
            return 0
        except ImportError as e:
            print(f"Error: {e}", file=sys.stderr)
            return 1
        except Exception as e:
            print(f"Unexpected error: {e}", file=sys.stderr)
            return 1

    def _inspect_mlir(self, filepath: Path, args: argparse.Namespace) -> int:
        """Inspect MLIR file."""
        with open(filepath, "r") as f:
            mlir_code = f.read()
        
        if args.meta:
            # Extract metadata only
            self._print_mlir_metadata(mlir_code)
        else:
            # Print full file
            print(mlir_code)
        
        return 0
    
    def _inspect_bytecode(self, filepath: Path, args: argparse.Namespace) -> int:
        """Inspect PIRTM bytecode."""
        # Placeholder: in production, decode .pirtm.bc binary format
        print(f"File: {filepath}")
        print(f"Format: PIRTM Bytecode (.pirtm.bc)")
        print(f"Size: {filepath.stat().st_size} bytes")
        
        if args.verify:
            print("Audit Chain: NOT EMBEDDED — retrieve via pirtm audit <trace.log>")
        
        return 0
    
    def _print_mlir_metadata(self, mlir_code: str) -> None:
        """Print contractivity metadata from MLIR."""
        import re
        
        print("=== MLIR Module Metadata ===")
        print()
        
        # Extract module comments
        comments = re.findall(r'// (.*)', mlir_code)
        for comment in comments[:5]:  # First 5 comments
            print(f"  {comment}")
        
        print()
        
        # Extract pirtm.module metadata
        if "pirtm.module {" in mlir_code:
            print("Contractivity Bounds:")
            for key in ["epsilon", "confidence", "op_norm_T", "prime_index"]:
                match = re.search(fr'@{key} = ([\d.]+|\'?\d+\'?)', mlir_code)
                if match:
                    print(f"  {key}: {match.group(1)}")
        
        print()
    
    # ========== Helper Methods ==========
    
    def _load_descriptor(self, filepath: str) -> Dict[str, Any]:
        """Load descriptor from YAML or JSON."""
        path = Path(filepath)
        
        if not path.exists():
            raise FileNotFoundError(f"Descriptor file not found: {filepath}")
        
        with open(path, "r") as f:
            if path.suffix == ".yaml" or path.suffix == ".yml":
                import yaml
                return yaml.safe_load(f)
            elif path.suffix == ".json":
                return json.load(f)
            else:
                raise ValueError(f"Unknown descriptor format: {path.suffix}")
    
    def _default_output_path(self, input_path: str, format: str) -> str:
        """Generate default output path from input."""
        input_p = Path(input_path)
        stem = input_p.stem.replace(".pirtm", "")
        return str(input_p.parent / f"{stem}.{format}")
    
    def run(self, argv: list[str] | None = None) -> int:
        """Run CLI."""
        args = self.parser.parse_args(argv)
        
        if not hasattr(args, "func"):
            self.parser.print_help()
            return 0
        
        return args.func(args)


def main():
    """Entry point for pirtm CLI."""
    cli = PirtmCLI()
    sys.exit(cli.run())


if __name__ == "__main__":
    main()
