/-!
# Foundations.Dynamics.Flows — Discrete Dynamical Systems, Flows & Stability

Formalizes discrete dynamical systems, trajectories, fixed point iteration propagation,
Lyapunov stability criteria, monoid continuous flows, and periodic orbits.
-/

namespace Foundations.Dynamics.Flows

/-- Discrete dynamical system consisting of a state transition map and initial state. -/
structure DiscreteSystem (α : Type) where
  map   : α → α
  state : α

/-- Iterated application of a state transition map. -/
def iterate {α : Type} (f : α → α) : Nat → α → α
  | 0, a => a
  | n + 1, a => f (iterate f n a)

/-- Trajectory generated by iterating f starting from x0. -/
def trajectory {α : Type} (f : α → α) (x₀ : α) : Nat → α :=
  fun n => iterate f n x₀

/-- Fixed point predicate. -/
def IsFixedPoint {α : Type} (f : α → α) (x : α) : Prop :=
  f x = x

/-- Base step of iteration. -/
theorem iterate_zero {α : Type} (f : α → α) (x : α) : iterate f 0 x = x := rfl

/-- Successor step of iteration. -/
theorem iterate_succ {α : Type} (f : α → α) (n : Nat) (x : α) :
    iterate f (n + 1) x = f (iterate f n x) := rfl

/-- Theorem: Additive index composition for iterated map application. -/
theorem iterate_add {α : Type} (f : α → α) (m n : Nat) (x : α) :
    iterate f (m + n) x = iterate f m (iterate f n x) := by
  induction m with
  | zero =>
    rw [Nat.zero_add]
    rfl
  | succ m ih =>
    rw [Nat.succ_add]
    rw [iterate_succ, iterate_succ, ih]

/-- Theorem: Fixed point preservation under subsequent iteration. -/
theorem fixedPointOfIterate {α : Type} (f : α → α) (x : α) (n : Nat) :
    IsFixedPoint f (iterate f n x) → ∀ m, iterate f (m + n) x = iterate f n x := by
  intro h m
  induction m with
  | zero =>
    rw [Nat.zero_add]
  | succ m ih =>
    rw [Nat.succ_add]
    rw [iterate_succ, ih]
    exact h

/-- Lyapunov function witnessing discrete energy descent. -/
def LyapunovFunction {α : Type} (f : α → α) (V : α → Nat) (x_star : α) : Prop :=
  V x_star = 0 ∧
  (∀ x, x ≠ x_star → V x > 0) ∧
  (∀ x, V (f x) ≤ V x)

/-- Stability predicate in the sense of Lyapunov. -/
def IsStable {α : Type} (f : α → α) (x_star : α) : Prop :=
  ∃ V, LyapunovFunction f V x_star

/-- Asymptotic stability: Lyapunov stability with global finite-time convergence. -/
def IsAsymptoticallyStable {α : Type} (f : α → α) (x_star : α) : Prop :=
  IsStable f x_star ∧
  ∀ x₀, ∃ N, ∀ n ≥ N, iterate f n x₀ = x_star

/-- Continuous flow indexed by monoid parameter. -/
structure Flow (α : Type) where
  phi      : Nat → α → α
  phi_zero : ∀ x, phi 0 x = x
  phi_add  : ∀ s t x, phi (s + t) x = phi s (phi t x)

/-- Equilibrium point of a flow. -/
def EquilibriumPoint {α : Type} (φ : Flow α) (x : α) : Prop :=
  ∀ t, φ.phi t x = x

/-- Periodic orbit of period T > 0. -/
def PeriodicOrbit {α : Type} (φ : Flow α) (x : α) (T : Nat) : Prop :=
  T > 0 ∧ φ.phi T x = x ∧ ∀ t, 0 < t ∧ t < T → φ.phi t x ≠ x

end Foundations.Dynamics.Flows
