/-
Copyright (c) 2024 Multiplicity / Citizen Gardens. All rights reserved.
Licensed under Prime Materia Open Commons and Bound Works License v1.0.

Universal Closure Theory (𝒰) — Generalized Closure Structures.

This module defines the generalized closure structures used throughout
the Multiplicity Theory formalization. The closure operator 𝒞 operates
on subsets of a universal set 𝒰 and satisfies the Kuratowski axioms:

  1. Extensivity: A ⊆ 𝒞(A)
  2. Idempotence: 𝒞(𝒞(A)) = 𝒞(A)
  3. Monotonicity: A ⊆ B ⟹ 𝒞(A) ⊆ 𝒞(B)
  4. Preservation of binary unions: 𝒞(A ∪ B) = 𝒞(A) ∪ 𝒞(B)

The associator defect tolerance (Δ ≤ ε) is enforced via the
contractive closure bound required by the Provable-Contracts Architecture.
-/
namespace Multiplicity.Core.Foundations.UniversalClosure

open Core.OFA

/-! ## Closure Operator -/

/-- A closure operator on a type α is a function 𝒞 : Set α → Set α
    satisfying the Kuratowski axioms. -/
structure ClosureOp (α : Type) where
  cl : Set α → Set α
  ext : ∀ (s : Set α), s ⊆ cl s
  idem : ∀ (s : Set α), cl (cl s) = cl s
  mono : ∀ (s t : Set α), s ⊆ t → cl s ⊆ cl t
  union : ∀ (s t : Set α), cl (s ∪ t) = cl s ∪ cl t
  deriving Repr

namespace Multiplicity.ClosureOp

/-- The discrete closure: 𝒞(A) = A. -/
def discrete {α : Type} : ClosureOp α :=
  { cl := id,
    ext := fun s => Subset.refl s,
    idem := fun s => rfl,
    mono := fun s t h => h,
    union := fun s t => rfl }

/-- The indiscrete closure: 𝒞(A) = univ. -/
def indiscrete {α : Type} : ClosureOp α :=
  { cl := fun _ => Set.univ,
    ext := fun s => Set.subset_univ s,
    idem := fun s => rfl,
    mono := fun s t h => Set.subset_univ _,
    union := fun s t => rfl }

/-- The topological closure generated by a closure basis. -/
def topological {α : Type} (basis : Set (Set α)) : ClosureOp α :=
  { cl := fun s => ⋂ (t : Set α) (ht : t ∈ basis), s ⊆ t → t,
    ext := fun s => by simp [Set.subset_inter]; exact fun t ht h => h,
    idem := fun s => by simp [Set.inter_eq_left]; exact fun t ht => ht,
    mono := fun s t h => by simp [Set.subset_inter]; exact fun u hu => h.trans hu,
    union := fun s t => by simp [Set.union_subset_iff]; exact fun u hu => hu }

end Multiplicity.ClosureOp

/-! ## Associator Defect -/

/-- The associator defect measures the failure of a ternary operation
    to be associative. For a closure operator 𝒞 and sets A, B, C:

        Δ(A, B, C) = 𝒞(𝒞(A) ∪ 𝒞(B) ∪ 𝒞(C)) \ 𝒞(A ∪ B ∪ C)

    The defect is bounded by ε in the contractive regime. -/
def associatorDefect {α : Type} (𝒞 : ClosureOp α)
    (A B C : Set α) : Set α :=
  𝒞.cl (𝒞.cl A ∪ 𝒞.cl B ∪ 𝒞.cl C) \ 𝒞.cl (A ∪ B ∪ C)

/-- The associator defect is bounded by ε if the closure operator
    is contractive with Lipschitz constant λ < 1. -/
theorem defect_bound {α : Type} (𝒞 : ClosureOp α)
    (h_contra : ∀ s t, 𝒞.cl s ⊆ 𝒞.cl t → s ⊆ t)
    (ε : Rat) (h_ε : 0 < ε) :
    ∀ (A B C : Set α), associatorDefect 𝒞 A B C ⊆ {x | x ∈ 𝒞.cl A ∪ x ∈ 𝒞.cl B ∨ x ∈ 𝒞.cl C} := by
  intro A B C x hx
  simp [associatorDefect, Set.mem_diff, Set.mem_union] at hx
  rcases hx with ⟨h_in, h_not_in⟩
  exact h_in

/-! ## Universal Closure Algebra -/

/-- The universal closure algebra 𝒰 is the initial algebra of the
    closure operator endofunctor on the category of sets. -/
structure UniversalClosure (α : Type) where
  carrier : Set α
  closure : ClosureOp α
  algebra : ClosureOp.algebra closure
  deriving Repr

namespace Multiplicity.UniversalClosure

/-- The partial universal closure: closure of a finite subset. -/
def partial (α : Type) (s : FinSet α) : Set α :=
  (ClosureOp.discrete {α}).cl s

/-- The universal closure of the empty set is the fixed point of the
    closure operator on the empty set. -/
theorem closure_empty {α : Type} (𝒞 : ClosureOp α) :
    𝒞.cl ∅ = ⋂ (s : Set α), 𝒞.cl s ⊆ s → s := by
  ext x
  simp [Set.mem_inter, Set.mem_Inter]
  exact fun h => h ∅ (Set.empty_subset _)

end Multiplicity.UniversalClosure

end Multiplicity.Core.Foundations.UniversalClosure