use crate::binding::{HealthTwinState, LambdaTraceAtom, TwinBindingContract, TwinBindingError};
use serde::{Deserialize, Serialize};

/// Report generated by the Master Primatician Λ_m Interface after evaluating the coupled twin system.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CoupledCoherenceReport {
    pub global_contraction_margin: f64,
    pub spectral_alignment: bool,
    pub dissonance_detected: bool,
    pub twin_resonance: bool,
    pub timestamp: u64,
}

/// The Λ_m Consciousness Interface orchestrates the educational (EchoMirror) and health (Ataraxia) twins.
pub struct LambdaMCoupledInterface {
    pub active_trajectory: String,
    pub contract: TwinBindingContract,
}

impl LambdaMCoupledInterface {
    pub fn new(trajectory: &str, max_q_threshold: f64, min_eeg_coherence: f64) -> Self {
        Self {
            active_trajectory: trajectory.to_string(),
            contract: TwinBindingContract::new(max_q_threshold, min_eeg_coherence),
        }
    }

    /// Orchestrates and evaluates the real-time coherence of the coupled twin system.
    pub fn orchestrate_twins(
        &self,
        educational_atom: &LambdaTraceAtom,
        health_twin: &HealthTwinState,
    ) -> Result<CoupledCoherenceReport, TwinBindingError> {
        self.contract
            .evaluate_resonance(educational_atom, health_twin)?;

        let global_margin = (1.0 - educational_atom.q) * health_twin.eeg_coherence_score;
        let spectral_alignment =
            educational_atom.q < 0.98 && health_twin.eeg_coherence_score > 0.75;
        let dissonance_detected = global_margin < 0.01 || !spectral_alignment;

        Ok(CoupledCoherenceReport {
            global_contraction_margin: global_margin,
            spectral_alignment,
            dissonance_detected,
            twin_resonance: true,
            timestamp: educational_atom.timestamp,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_atom(q: f64, trajectory: &str) -> LambdaTraceAtom {
        LambdaTraceAtom {
            proof_digest: "digest".to_string(),
            state_root_hash: "state_hash".to_string(),
            timestamp: 123456789,
            q,
            tee_quote: Some("TEE_HARDWARE_QUOTE".to_string()),
            trajectory_id: trajectory.to_string(),
            protocol_v: 1,
            signer_id: Some("signer".to_string()),
        }
    }

    fn make_health(trajectory: &str, eeg: f64) -> HealthTwinState {
        HealthTwinState {
            twin_id: "twin-001".to_string(),
            active_trajectory: trajectory.to_string(),
            biometrics_hash: "bio_hash".to_string(),
            eeg_coherence_score: eeg,
            last_updated: 123456780,
        }
    }

    #[test]
    fn test_successful_lambda_m_orchestration() {
        let interface =
            LambdaMCoupledInterface::new("Ataraxia-EchoMirror-Twin-Binding", 0.995, 0.70);
        let atom = make_atom(0.95, "Ataraxia-EchoMirror-Twin-Binding");
        let health = make_health("Ataraxia-EchoMirror-Twin-Binding", 0.85);
        let report = interface
            .orchestrate_twins(&atom, &health)
            .expect("Orchestration failed");
        assert!((report.global_contraction_margin - 0.0425).abs() < f64::EPSILON);
        assert!(report.spectral_alignment);
        assert!(!report.dissonance_detected);
        assert!(report.twin_resonance);
    }

    #[test]
    fn test_lambda_m_dissonance_detection() {
        let interface =
            LambdaMCoupledInterface::new("Ataraxia-EchoMirror-Twin-Binding", 0.995, 0.70);
        let atom = make_atom(0.985, "Ataraxia-EchoMirror-Twin-Binding");
        let health = make_health("Ataraxia-EchoMirror-Twin-Binding", 0.72);
        let report = interface
            .orchestrate_twins(&atom, &health)
            .expect("Orchestration failed");
        assert!(!report.spectral_alignment);
        assert!(report.dissonance_detected);
    }

    #[test]
    fn test_lambda_m_rejects_misalignment() {
        let interface =
            LambdaMCoupledInterface::new("Ataraxia-EchoMirror-Twin-Binding", 0.995, 0.70);
        let atom = make_atom(0.95, "Ataraxia-EchoMirror-Twin-Binding");
        let health = make_health("Ataraxia-EchoMirror-Twin-Binding", 0.50);
        let result = interface.orchestrate_twins(&atom, &health);
        assert!(matches!(
            result,
            Err(TwinBindingError::CrossDomainMisalignment)
        ));
    }
}
