use crate::binding::{LambdaTraceAtom, HealthTwinState, TwinBindingContract, TwinBindingError};
use serde::{Deserialize, Serialize};

/// Report generated by the Master Primatician Λ_m Interface after evaluating the coupled twin system.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CoupledCoherenceReport {
    pub global_contraction_margin: f64,
    pub spectral_alignment: bool,
    pub dissonance_detected: bool,
    pub twin_resonance: bool,
    pub timestamp: u64,
}

/// The Λ_m Consciousness Interface acts as the highest-level orchestrator,
/// binding the educational (EchoMirror) and health (Ataraxia) twins together.
pub struct LambdaMCoupledInterface {
    pub active_trajectory: String,
    pub contract: TwinBindingContract,
}

impl LambdaMCoupledInterface {
    pub fn new(trajectory: &str, max_q_threshold: f64, min_eeg_coherence: f64) -> Self {
        Self {
            active_trajectory: trajectory.to_string(),
            contract: TwinBindingContract::new(max_q_threshold, min_eeg_coherence),
        }
    }

    /// Orchestrates and evaluates the real-time coherence of the coupled twin system.
    pub fn orchestrate_twins(
        &self,
        educational_atom: &LambdaTraceAtom,
        health_twin: &HealthTwinState,
    ) -> Result<CoupledCoherenceReport, TwinBindingError> {
        // 1. Evaluate cross-domain resonance using the foundational TwinBindingContract
        self.contract.evaluate_resonance(educational_atom, health_twin)?;

        // 2. Compute Global Contraction Margin
        // The global margin fuses the educational q-factor and the health twin's coherence score.
        // A high q (stress) combined with a borderline EEG coherence lowers the overall margin.
        let global_margin = (1.0 - educational_atom.q) * health_twin.eeg_coherence_score;

        // 3. Spectral Alignment Check
        // The fused system is spectrally aligned if both sub-systems operate in high-stability bands.
        let spectral_alignment = educational_atom.q < 0.98 && health_twin.eeg_coherence_score > 0.75;

        // 4. Dissonance Detection
        // Dissonance is flagged if the global fused margin drops below a critical viability kernel (e.g., 0.01)
        // even if individual threshold bounds were barely met.
        let dissonance_detected = global_margin < 0.01 || !spectral_alignment;

        if dissonance_detected {
            println!("[WARN] [Λ_m] Systemic Dissonance Detected in Coupled Twins. Global Margin: {:.4}", global_margin);
        } else {
            println!("[INFO] [Λ_m] Coupled Twins Coherent. Global Margin: {:.4}", global_margin);
        }

        Ok(CoupledCoherenceReport {
            global_contraction_margin: global_margin,
            spectral_alignment,
            dissonance_detected,
            twin_resonance: true,
            timestamp: educational_atom.timestamp,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_successful_lambda_m_orchestration() {
        let interface = LambdaMCoupledInterface::new("Ataraxia-EchoMirror-Twin-Binding", 0.995, 0.70);
        let atom = LambdaTraceAtom {
            proof_digest: "digest".to_string(),
            state_root_hash: "state_hash".to_string(),
            timestamp: 123456789,
            q: 0.95, // 0.05 margin
            tee_quote: Some("TEE_HARDWARE_QUOTE".to_string()),
            trajectory_id: "Ataraxia-EchoMirror-Twin-Binding".to_string(),
            protocol_v: 1,
            signer_id: Some("signer".to_string()),
        };
        let health_twin = HealthTwinState {
            twin_id: "twin-001".to_string(),
            active_trajectory: "Ataraxia-EchoMirror-Twin-Binding".to_string(),
            biometrics_hash: "bio_hash".to_string(),
            eeg_coherence_score: 0.85,
            last_updated: 123456780,
        };

        let report = interface.orchestrate_twins(&atom, &health_twin).expect("Orchestration failed");
        
        // global_margin = (1.0 - 0.95) * 0.85 = 0.05 * 0.85 = 0.0425
        assert!((report.global_contraction_margin - 0.0425).abs() < f64::EPSILON);
        assert!(report.spectral_alignment);
        assert!(!report.dissonance_detected);
        assert!(report.twin_resonance);
    }

    #[test]
    fn test_lambda_m_dissonance_detection() {
        let interface = LambdaMCoupledInterface::new("Ataraxia-EchoMirror-Twin-Binding", 0.995, 0.70);
        let atom = LambdaTraceAtom {
            proof_digest: "digest".to_string(),
            state_root_hash: "state_hash".to_string(),
            timestamp: 123456789,
            q: 0.985, // Highly stressful educational move
            tee_quote: Some("TEE_HARDWARE_QUOTE".to_string()),
            trajectory_id: "Ataraxia-EchoMirror-Twin-Binding".to_string(),
            protocol_v: 1,
            signer_id: Some("signer".to_string()),
        };
        let health_twin = HealthTwinState {
            twin_id: "twin-001".to_string(),
            active_trajectory: "Ataraxia-EchoMirror-Twin-Binding".to_string(),
            biometrics_hash: "bio_hash".to_string(),
            eeg_coherence_score: 0.72, // Borderline acceptable health twin
            last_updated: 123456780,
        };

        let report = interface.orchestrate_twins(&atom, &health_twin).expect("Orchestration failed");
        
        // Dissonance is expected due to poor spectral alignment (q >= 0.98 or eeg <= 0.75)
        assert!(!report.spectral_alignment);
        assert!(report.dissonance_detected);
    }

    #[test]
    fn test_lambda_m_rejects_misalignment() {
        let interface = LambdaMCoupledInterface::new("Ataraxia-EchoMirror-Twin-Binding", 0.995, 0.70);
        let atom = LambdaTraceAtom {
            proof_digest: "digest".to_string(),
            state_root_hash: "state_hash".to_string(),
            timestamp: 123456789,
            q: 0.95,
            tee_quote: Some("TEE_HARDWARE_QUOTE".to_string()),
            trajectory_id: "Ataraxia-EchoMirror-Twin-Binding".to_string(),
            protocol_v: 1,
            signer_id: Some("signer".to_string()),
        };
        let health_twin = HealthTwinState {
            twin_id: "twin-001".to_string(),
            active_trajectory: "Ataraxia-EchoMirror-Twin-Binding".to_string(),
            biometrics_hash: "bio_hash".to_string(),
            eeg_coherence_score: 0.50, // Fails base contract
            last_updated: 123456780,
        };

        let result = interface.orchestrate_twins(&atom, &health_twin);
        assert!(matches!(result, Err(TwinBindingError::CrossDomainMisalignment)));
    }
}
