-- @generated by uor-lean from uor-ontology — do not edit manually
--
-- UOR Foundation — individual constant namespaces (aggregator).

import Core.UOR.Individuals.Schema
import Core.UOR.Individuals.Op
import Core.UOR.Individuals.Resolver
import Core.UOR.Individuals.Type_
import Core.UOR.Individuals.Foundation
import Core.UOR.Individuals.Observable
import Core.UOR.Individuals.Homology
import Core.UOR.Individuals.Cohomology
import Core.UOR.Individuals.Proof
import Core.UOR.Individuals.Trace
import Core.UOR.Individuals.Morphism
import Core.UOR.Individuals.State
import Core.UOR.Individuals.Reduction
import Core.UOR.Individuals.Convergence
import Core.UOR.Individuals.Division
import Core.UOR.Individuals.Predicate
import Core.UOR.Individuals.Conformance_
