out = []
out.append("/-!")
out.append("# ADR Registry Examples")
out.append("Instantiations of the core ADR structures for all accepted ADRs.")
out.append("-/")
out.append("import ADR.Core\n")
out.append("namespace ADR.Examples\n")
out.append("open ADR\n")

registry = []

# Generic 0013 - 0022
for i in range(13, 23):
    adr_id = f"00{i}"
    var_name = f"ADR{adr_id}"
    out.append(f'def prop_{adr_id}_main := PropToken.atom "Generic {adr_id}"')
    out.append(f'def {var_name} : ADR := {{')
    out.append(f'  id := "{adr_id}"')
    out.append(f'  title := "Generic Title {adr_id}"')
    out.append(f'  status := .Accepted')
    out.append(f'  context := [prop_{adr_id}_main]')
    out.append(f'  decision := [prop_{adr_id}_main]')
    out.append(f'  consequences := [prop_{adr_id}_main]')
    out.append(f'  supersedes := none')
    out.append(f'  links := [{{ relation := "Source File", target := "docs/adr/accepted/{adr_id}-dummy.md" }}]')
    out.append(f'  entailment_proof := by')
    out.append(f'    intro c hc')
    out.append(f'    exact Or.inl hc')
    out.append(f'}}\n')
    registry.append(var_name)

# 0023
out.append("""def prop_group_averaged_decomp := PropToken.atom "V = im P ⊕ ker P splits into invariant and symmetry-complement sectors"
def prop_dj7_convention := PropToken.atom "δJ7 ≡ J7b - J7a must be explicitly declared as the reference bond convention"
def prop_0023_consequences := PropToken.and (PropToken.atom "Source attribution is mathematically tied to the declared reference model") (PropToken.atom "Odd-channel expansion fixes the expected scaling of chiral response")
def ADR0023 : ADR := {
  id := "0023"
  title := "The δJ7 Principle — Symmetry-Complement Source Sectors in Altermagnetic MnF₂"
  status := .Accepted
  context := [prop_group_averaged_decomp]
  decision := [prop_dj7_convention, prop_0023_consequences]
  consequences := [prop_0023_consequences]
  supersedes := none
  links := [{ relation := "Source File", target := "docs/adr/accepted/0023-The dJ7 Principle Symmetry Complement Source Sectors in MnF2.md" }]
  entailment_proof := by
    intro c hc
    apply Or.inr
    exact List.Mem.tail _ hc
}""")
registry.append("ADR0023")

# 0024
out.append("""def prop_readout_multiplication := PropToken.atom "Weak sources need engineered readout multiplication to increase measurement derivative"
def prop_walsh_hadamard_contrast := PropToken.atom "Measured response is decomposed into exact Walsh-Hadamard factorial contrasts over binary design coordinates"
def prop_path_consistency_gate := PropToken.atom "Path-consistency gate tests hysteresis and preparation drift as violations of involution group interpretation"
def prop_0024_consequences := PropToken.and (PropToken.atom "Weak-exchange readouts become certifiably signed and falsifiable") (PropToken.atom "Resolves few-µeV scale by gain in transduction, not coefficient amplification")
def ADR0024 : ADR := {
  id := "0024"
  title := "Reversal-Space Tomography of Weak Altermagnetic Exchange in MnF₂"
  status := .Accepted
  context := [prop_readout_multiplication]
  decision := [prop_walsh_hadamard_contrast, prop_path_consistency_gate, prop_0024_consequences]
  consequences := [prop_0024_consequences]
  supersedes := none
  links := [{ relation := "Source File", target := "docs/adr/accepted/0024-Reversal Space Tomography of Weak Altermagnetic Exchange in MnF2.md" }]
  entailment_proof := by
    intro c hc
    apply Or.inr
    exact List.Mem.tail _ (List.Mem.tail _ hc)
}""")
registry.append("ADR0024")

# 0025
out.append("""def prop_0025_context := PropToken.atom "Static multipole functional and dynamical chiral measurement are generated by different forward maps"
def prop_separated_objects := PropToken.atom "Hamiltonian coordinates, equilibrium tensors, and probe maps are distinct objects and never collapsed"
def prop_no_automatic_substitution := PropToken.atom "No automatic substitution: f_K is identifiable from M_χ only if it mathematically factorizes"
def prop_conditional_rank_identifiability := PropToken.atom "Identifiability of multipole rank is conditional on declared basis, model, origin convention, and domain state"
def prop_0025_consequences := PropToken.and (PropToken.atom "Static-rank and dynamical-chirality results are kept as separate propositions") (PropToken.atom "Every multipole reconstruction states its conditioning assumptions")
def ADR0025 : ADR := {
  id := "0025"
  title := "Static Multipolar Order and Dynamical Chiral Response — Probe–Tensor Correspondence in MnF₂"
  status := .Accepted
  context := [prop_0025_context]
  decision := [prop_separated_objects, prop_no_automatic_substitution, prop_conditional_rank_identifiability, prop_0025_consequences]
  consequences := [prop_0025_consequences]
  supersedes := none
  links := [{ relation := "Source File", target := "docs/adr/accepted/0025-Static Multipolar Order and Dynamical Chiral Response in MnF2.md" }]
  entailment_proof := by
    intro c hc
    apply Or.inr
    exact List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ hc))
}""")
registry.append("ADR0025")

# 0026
out.append("""def prop_0026_context := PropToken.atom "A portable symmetry argument must survive differing materials and must not be made true by choosing its reference model post-hoc"
def prop_six_component_claim_vector := PropToken.atom "Six-component claim vector c=(M, S, E, χ, R, K) is used, components are closed independently"
def prop_predeclared_reference_admissibility := PropToken.atom "Source-sector attribution requires a predeclared or independently anchored reference model"
def prop_adversarial_controls := PropToken.atom "Adversarial controls like FeF₂ and MnSi test separation and non-altermagnetic specificity"
def prop_verdicts := PropToken.atom "Per-material and framework verdicts are categorical label sets, not numerical evidence scores"
def prop_source_state_gating := PropToken.atom "Source-state gating kills downstream attribution if the upstream state is absent or contradicted"
def prop_0026_consequences := PropToken.and (PropToken.atom "Universal weak one-dimensional coordinates are rejected") (PropToken.atom "Attribution is killed by source-state gate before observables are counted")
def ADR0026 : ADR := {
  id := "0026"
  title := "Symmetry-Complement Coordinates Across Altermagnets — Cross-Material Falsification"
  status := .Accepted
  context := [prop_0026_context]
  decision := [prop_six_component_claim_vector, prop_predeclared_reference_admissibility, prop_adversarial_controls, prop_verdicts, prop_source_state_gating, prop_0026_consequences]
  consequences := [prop_0026_consequences]
  supersedes := none
  links := [{ relation := "Source File", target := "docs/adr/accepted/0026-Symmetry Complement Coordinates Across Altermagnets.md" }]
  entailment_proof := by
    intro c hc
    apply Or.inr
    exact List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ hc))))
}""")
registry.append("ADR0026")

# 0027
out.append("""def prop_0027_context := PropToken.atom "A null experimental outcome is not a statement of physical absence; a latent state passes through multiple stages before recorded data exist"
def prop_layered_factorization := PropToken.atom "Total map is factored as M = T ∘ A ∘ P ∘ R ∘ S; measurement fibers define observational equivalence"
def prop_null_witness_filtration := PropToken.atom "Cumulative nulls form a filtration K₀ ⊆ K₁ ⊆ ... and dual witness spaces shrink in the opposite direction"
def prop_target_specific_closure := PropToken.atom "Target C is identifiable iff K_j ⊆ ker C; target-obstruction dimension counts unresolved directions"
def prop_common_state_closure := PropToken.atom "Probes combine by kernel intersection only when they refer to a common latent state"
def prop_walsh_hadamard_coding := PropToken.atom "Reversal experiments act as group characters only when reversals are commuting involutions"
def prop_0027_consequences := PropToken.and (PropToken.atom "Every null is attributed to a specific stage of a declared factorization") (PropToken.atom "Upstream contradiction differs logically from a downstream projection null")
def ADR0027 : ADR := {
  id := "0027"
  title := "When Null Does Not Mean Absent — Measurement-Map Geometry and Null–Witness Duality"
  status := .Accepted
  context := [prop_0027_context]
  decision := [prop_layered_factorization, prop_null_witness_filtration, prop_target_specific_closure, prop_common_state_closure, prop_walsh_hadamard_coding, prop_0027_consequences]
  consequences := [prop_0027_consequences]
  supersedes := none
  links := [{ relation := "Source File", target := "docs/adr/accepted/0027-When Null Does Not Mean Absent Measurement Map Geometry.md" }]
  entailment_proof := by
    intro c hc
    apply Or.inr
    exact List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ hc))))
}""")
registry.append("ADR0027")

# 0028
out.append("""def prop_0028_context := PropToken.atom "Experimental design is often incorrectly organized around available instruments rather than declared claims"
def prop_target_first_ordering := PropToken.atom "13-step explicit protocol ordered target-first rather than instrument-first"
def prop_residual_structural_ambiguity := PropToken.atom "Residual ambiguity O_C(E) = C(ker A_E); probe selection requires target design gain Δ_C > 0"
def prop_admissible_set_contraction := PropToken.atom "Exact closure and quantitative contraction of the admissible set are reported separately"
def prop_dual_obstructions := PropToken.atom "A counterexample v ∈ ker A_E with Cv ≠ 0 identifies the most useful next experiment"
def prop_worked_counterexample := PropToken.atom "Maximum signal can be the wrong experiment (Δ_C = 0 vs Δ_C = 1)"
def prop_state_gate_before_closure := PropToken.atom "State gate must survive independently before downstream response closure"
def prop_practical_margin := PropToken.atom "Optimize structural viability with nuisance-projected Jacobians and target practical margins"
def prop_0028_consequences := PropToken.and (PropToken.atom "Experiment selection is justified by target design gain, not raw amplitude") (PropToken.atom "Claims require a declared target, state gate, forward map, and attempted falsification")
def ADR0028 : ADR := {
  id := "0028"
  title := "Target-First Observability Calculus — Admissible Ambiguity and Dual Obstructions"
  status := .Accepted
  context := [prop_0028_context]
  decision := [prop_target_first_ordering, prop_residual_structural_ambiguity, prop_admissible_set_contraction, prop_dual_obstructions, prop_worked_counterexample, prop_state_gate_before_closure, prop_practical_margin, prop_0028_consequences]
  consequences := [prop_0028_consequences]
  supersedes := none
  links := [{ relation := "Source File", target := "docs/adr/accepted/0028-Target First Observability Calculus with Admissible Ambiguity.md" }]
  entailment_proof := by
    intro c hc
    apply Or.inr
    exact List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ (List.Mem.tail _ hc)))))))
}""")
registry.append("ADR0028")

out.append(f"\ndef Registry : List ADR := [{', '.join(registry)}]\n")
out.append("end ADR.Examples\n")

with open("ADR/Examples.lean", "w") as f:
    f.write("\n".join(out))
