import Lean

import ADR.Core
import ADR.Proofs

/-!
# ADR-0068: OSCAL and PrismPM — Zero-Sorry Formal Model

This module formalizes the **semantic core** of ADR-0068 (OSCAL and PrismPM) as a
self-contained, zero-`sorry` Lean model of the **Legalese Scopist** translation
layer mandated by `docs/adr/accepted/0068-OSCAL and PrismPM.md`:

1. **The Legalese Scopist** is the exclusive, *read-only* translation mapping
   layer downstream of PrismPM and the Sedona Spine. It is mathematically
   forbidden from calculating, negotiating, or re-interpreting risk.
2. **Deterministic translation:** the Scopist ingests the cryptographically
   sealed `ContractivityReceipt` (R) emitted when PrismPM artifacts are evaluated
   by the Sedona Spine, and applies `f_Scopist(R) = Narrative_legal` to produce an
   OSCAL assessment-result model (`OSCALModel`, O).
3. **Zero-drift enforcement:** if the execution engine emits a `SIG_GOV_KILL`
   verdict due to a contractivity/drift breach, the resulting OSCAL model is
   mathematically forbidden from mitigating the risk: it must mark its evidence
   **UNATTESTED** (any SAR lacking a hashed R1CS compiler manifest or Lean proof
   hash is explicitly UNATTESTED).
4. **Packaging-only OSCAL:** OSCAL is used strictly as an optional, read-only
   export format — a narrative envelope, never a runtime attester.

As in `ADR.Prism` and `ADR.Archivum`, all quantities are fixed-point `Nat` (scaled
integers, no floating point, no Mathlib), so every gate below is decidable and
machine-checkable. The document's `class ScopistLaw` is realized here as a
`structure` indexed by a `LegaleseScopist` translator; Lean classes and
structures are interchangeable for a proposition-valued law.

> **Deliberately minimal, yet extensible:** the acceptance doc sketches the
> translator input as `ℝ`-valued `l_phi`/`delta`. We encode them as scaled `Nat`
> to keep the whole model decidable and `native_decide`/`decide`-dischargeable,
> mirroring the deterministic scaled-integer comparisons of the ACE veto gate.
> The `risk` field of an emitted `OSCALModel` is *copied verbatim* from the
> receipt (never recomputed), which is exactly the "OSCAL acts solely as a
> narrative envelope, never as a runtime attester" boundary. Replace the
> `stateLabel`/`narrativeOf` string builders with a real OSCAL JSON serializer
> inside a `@[implemented_by]` FFI later; every theorem that quantifies over a
> `ScopistLaw` translator remains sound because the law only constrains
> determinism, zero-drift, and verbatim risk.

No `axiom`, `constant`, `opaque`, or `unsafe` is used anywhere in this file.
-/

namespace ADR
namespace OSCAL

/-! ## 1. Fixed-Point Governance Constants
Any narrative risk quantity must be a scaled integer (mirroring the PrismPM ACE
`u64` fixed-point convention); floats are strictly excluded.
-/

/-- Fixed-point unit scale: `1.0` is represented as `10^9 = 1_000_000_000`. -/
def RECEIPT_SCALE : Nat := 1_000_000_000

/-- The `(1 − ε)` contractivity bound in scaled units (`999_000_000`): a receipt
whose `l_phi` is at or above this bound is a contractivity breach
(`ρ(Λ) ≥ 1 − ε`), mirroring `ADR.Prism.CONTRACTIVITY_LIMIT_SCALED`. -/
def CONTRACTIVITY_BOUND_SCALED : Nat := 999_000_000

/-- The pinned risk level emitted for a `SIG_GOV_KILL` receipt. The narrative is
forbidden from mitigating a kill, so the OSCAL model reports the breach ceiling. -/
def KILL_RISK_SCALED : Nat := 999_000_000

/-- The bounded drift allowance (`30_000_000`), mirroring
`ADR.Prism.DRIFT_LIMIT_SCALED`: `delta` beyond this is a drift breach. -/
def DRIFT_LIMIT_SCALED : Nat := 30_000_000

/-! ## 2. Receipt, OSCAL Model, and Translation Types
Mirrors the ADR-0068 document (SRC §"ContractivityReceipt", §"OSCALModel").
-/

/-- Terminal execution states indicating the L0 base reality verdict emitted by
the Sedona Spine when a PrismPM artifact is evaluated. -/
inductive ExecutionState where
  | NOMINAL : ExecutionState
  | SIG_GOV_KILL : ExecutionState
  deriving DecidableEq, Repr, Inhabited

/-- The Contractivity Receipt (R) generated by the Sedona Spine. All quantities
are fixed-point scaled `Nat` (no floats), matching the ACE deterministic gates. -/
structure ContractivityReceipt where
  /-- Logical identifier of the evaluated lift. -/
  lift_id : String
  /-- Spectral-radius estimate `‖Ψ‖₊` (scaled); at/above `CONTRACTIVITY_BOUND_SCALED` is a breach. -/
  l_phi : Nat
  /-- Tensor defect `Δ` / execution drift (scaled). -/
  delta : Nat
  /-- Hashed R1CS compiler manifest (Lean proof hash) attesting the artifact. -/
  sigma_proof : String
  /-- Terminal execution verdict. -/
  verdict : ExecutionState
  deriving DecidableEq, Repr, Inhabited

/-- The structured OSCAL Assessment-Result marking for evidence. -/
inductive AttestationState where
  | ATTESTED : AttestationState
  | UNATTESTED : AttestationState
  deriving DecidableEq, Repr, Inhabited

/-- The structured OSCAL assessment-result model (O): a *narrative envelope*,
never a runtime attester. -/
structure OSCALModel where
  /-- The legal narrative `Narrative_legal` produced by `f_Scopist(R)`. -/
  narrative : String
  /-- Evidence marking: `ATTESTED` only on `NOMINAL`, else `UNATTESTED`. -/
  attestation : AttestationState
  /-- Copy of the receipt's hashed R1CS/Lean proof manifest; empty ⇒ UNATTESTED. -/
  proof_hash : String
  /-- Risk level, copied **verbatim** from the receipt (never re-computed). -/
  risk_level : Nat
  deriving DecidableEq, Repr, Inhabited

/-! ## 3. The Legalese Scopist Translator `f_Scopist` -/

/-- Deterministic state label used inside the legal narrative (the translator
never performs arithmetic; it only labels the verdict). -/
def stateLabel : ExecutionState → String
  | ExecutionState.NOMINAL => "NOMINAL"
  | ExecutionState.SIG_GOV_KILL => "SIG_GOV_KILL"

/-- The risk level carried by the narrative: verbatim drift `Δ` on `NOMINAL`,
pinned to the kill ceiling on `SIG_GOV_KILL`. This is a *copy* of the execution
engine's numbers — the Scopist does not calculate risk. -/
def riskLevelOf (r : ContractivityReceipt) : Nat :=
  match r.verdict with
  | ExecutionState.NOMINAL => r.delta
  | ExecutionState.SIG_GOV_KILL => KILL_RISK_SCALED

/-- The proof-hash evidence field: verbatim `sigma_proof` when attested;
empty (no manifest) when the engine killed the lift. -/
def proofHashOf (r : ContractivityReceipt) : String :=
  match r.verdict with
  | ExecutionState.NOMINAL => r.sigma_proof
  | ExecutionState.SIG_GOV_KILL => ""

/-- Deterministic narrative assembly `f_Scopist`'s string layer. Because it is a
pure function of the receipt fields, identical receipts always yield identical
narratives (idempotency & purity). -/
def narrativeOf (r : ContractivityReceipt) : String :=
  "Lift " ++ r.lift_id ++ ": state=" ++ stateLabel r.verdict ++ ", Δ=" ++ toString r.delta

/-- Attestation is granted on `NOMINAL` only; a kill is always `UNATTESTED`. -/
def attestationOf (r : ContractivityReceipt) : AttestationState :=
  match r.verdict with
  | ExecutionState.NOMINAL => AttestationState.ATTESTED
  | ExecutionState.SIG_GOV_KILL => AttestationState.UNATTESTED

/-- The **deterministic mapping function** `f_Scopist(R) = Narrative_legal`,
rendered as an `OSCALModel`. Structurally mirrors the doc's `LegaleseScopist`
class; all four fields are pure functions of the sealed receipt. -/
def scopistTranslate (r : ContractivityReceipt) : OSCALModel :=
  { narrative := narrativeOf r
    attestation := attestationOf r
    proof_hash := proofHashOf r
    risk_level := riskLevelOf r }

/-! ## 4. Zero-Drift Law and its Satisfaction -/

/-- The doc's `class LegaleseScopist`, realized as a structure carrying the
deterministic mapping interface `f_Scopist : ContractivityReceipt → OSCALModel`.
This is the machine-checkable counterpart of
"the Legalese Scopist mapping function must be formalized within an axiom-clean
Lean 4 core" (SRC §"Atom-clean core"). -/
structure LegaleseScopist where
  /-- The deterministic mapping function `f_Scopist(R) = Narrative_legal`. -/
  translate : ContractivityReceipt → OSCALModel

/-- **The Scopist Law.** Structural constraints guaranteeing idempotency/purity,
zero-drift, and the packaging-only rule (risk is never re-computed by the
compliance layer). Equivalent to the doc's `class ScopistLaw : Prop`; a
proposition-valued structure is interchangeable with a Prop class in Lean. -/
structure ScopistLaw (scopist : LegaleseScopist) : Prop where
  /-- **Idempotency & Purity:** identical telemetry packages always generate
  identical legal narratives (no probabilistic or heuristic adjustments). -/
  deterministic : ∀ (r1 r2 : ContractivityReceipt),
    r1.lift_id = r2.lift_id → r1.l_phi = r2.l_phi → r1.delta = r2.delta →
    r1.sigma_proof = r2.sigma_proof → r1.verdict = r2.verdict →
    scopist.translate r1 = scopist.translate r2
  /-- **Zero-Drift Enforcement:** a `SIG_GOV_KILL` verdict cannot be softened;
  the narrative must reflect an UNATTESTED state. -/
  zero_drift : ∀ (r : ContractivityReceipt),
    r.verdict = ExecutionState.SIG_GOV_KILL →
    (scopist.translate r).attestation = AttestationState.UNATTESTED
  /-- **Packaging-only:* the OSCAL envelope never computes risk — the risk field
  is verbatim from the receipt, so the Scopist cannot recalculate or negotiate
  the execution engine's numbers. -/
  risk_never_recalculated : ∀ (r : ContractivityReceipt),
    (scopist.translate r).risk_level = riskLevelOf r

/-- The concrete translator as a `LegaleseScopist` (the ADR-0068 instance). -/
def scopistTranslator : LegaleseScopist :=
  { translate := scopistTranslate }

/-! ### 4.1 Determinism and Idempotency -/

/-- **Idempotency & Purity (fieldwise).** Identical receipts `R₁ ≅ R₂` (same
lift id, `‖Ψ‖₊`, `Δ`, proof hash, verdict) always translate to identical
narratives. This is the formal counterpart of "eliminates compliance drift by
directly binding PrismPM's Lean 4 proofs ... to the generated legal narrative". -/
@[proof]
theorem scopist_deterministic (r1 r2 : ContractivityReceipt)
    (hli : r1.lift_id = r2.lift_id) (hp : r1.l_phi = r2.l_phi)
    (hd : r1.delta = r2.delta) (hs : r1.sigma_proof = r2.sigma_proof)
    (hv : r1.verdict = r2.verdict) :
    scopistTranslate r1 = scopistTranslate r2 := by
  rcases r1 with ⟨l1, p1, d1, s1, v1⟩
  rcases r2 with ⟨l2, p2, d2, s2, v2⟩
  simp at hli hp hd hs hv
  subst l1
  subst p1
  subst d1
  subst s1
  subst v1
  rfl

/-- **Trivially idempotent:** translating a receipt is stable under repetition
(the rigorous form of narrative repeatability; the substantive idempotency —
identical receipts ⇒ identical narratives — is `scopist_deterministic`). -/
@[proof]
theorem scopist_repeat_stable (r : ContractivityReceipt) :
    scopistTranslate r = scopistTranslate r := by
  rfl

/-! ### 4.2 Zero-Drift and Attestation Boundary -/

/-- **Zero-Drift Enforcement (translator).** A `SIG_GOV_KILL` verdict forces the
narrative into an `UNATTESTED` state: the compliance layer cannot mitigate the
kill. -/
@[proof]
theorem scopist_zero_drift (r : ContractivityReceipt)
    (hv : r.verdict = ExecutionState.SIG_GOV_KILL) :
    (scopistTranslate r).attestation = AttestationState.UNATTESTED := by
  cases r with
  | mk _ _ _ _ verdict =>
      cases verdict with
      | NOMINAL => cases hv
      | SIG_GOV_KILL => simp [scopistTranslate, attestationOf]

/-- A kill pins the OSCAL risk level to the breach ceiling (the narrative never
represents the kill as anything softer than the breach). -/
@[proof]
theorem scopist_kill_pins_full_risk (r : ContractivityReceipt)
    (hv : r.verdict = ExecutionState.SIG_GOV_KILL) :
    (scopistTranslate r).risk_level = KILL_RISK_SCALED := by
  cases r with
  | mk _ _ _ _ verdict =>
      cases verdict with
      | NOMINAL => cases hv
      | SIG_GOV_KILL => simp [scopistTranslate, riskLevelOf]

/-- **Unattested Markings:** a killed lift carries no hashed R1CS / Lean proof
manifest in the OSCAL model (`""`), so the SAR must be marked `UNATTESTED`. -/
@[proof]
theorem scopist_kill_withholds_proof (r : ContractivityReceipt)
    (hv : r.verdict = ExecutionState.SIG_GOV_KILL) :
    (scopistTranslate r).proof_hash = "" := by
  cases r with
  | mk _ _ _ _ verdict =>
      cases verdict with
      | NOMINAL => cases hv
      | SIG_GOV_KILL => simp [scopistTranslate, proofHashOf]

/-- A `NOMINAL` verdict attests (the only state that may carry `ATTESTED`). -/
@[proof]
theorem scopist_nominal_attests (r : ContractivityReceipt)
    (hv : r.verdict = ExecutionState.NOMINAL) :
    (scopistTranslate r).attestation = AttestationState.ATTESTED := by
  cases r with
  | mk _ _ _ _ verdict =>
      cases verdict with
      | NOMINAL => simp [scopistTranslate, attestationOf]
      | SIG_GOV_KILL => cases hv

/-- **Attestation boundary:** an `ATTESTED` OSCAL model can only ever have
originated from a `NOMINAL` verdict — the narrative can never attest a kill.
This is the "OSCAL acts solely as a narrative envelope, never as a runtime
attester" invariant (SRC §"Packaging-Only OSCAL"). -/
@[proof]
theorem attestation_only_on_nominal (r : ContractivityReceipt)
    (ha : (scopistTranslate r).attestation = AttestationState.ATTESTED) :
    r.verdict = ExecutionState.NOMINAL := by
  rcases r with ⟨_, _, _, _, v⟩
  cases v with
  | NOMINAL => rfl
  | SIG_GOV_KILL =>
      simp [scopistTranslate, attestationOf] at ha

/-- **Packaging-only:** on `NOMINAL` the OSCAL risk field is the receipt's `Δ`
verbatim — the Scopist never re-computes risk. -/
@[proof]
theorem scopist_risk_verbatim (r : ContractivityReceipt)
    (hv : r.verdict = ExecutionState.NOMINAL) :
    (scopistTranslate r).risk_level = r.delta := by
  cases r with
  | mk _ _ d _ verdict =>
      cases verdict with
      | NOMINAL => simp [scopistTranslate, riskLevelOf]
      | SIG_GOV_KILL => cases hv

/-! ### 4.3 The Concrete Translator Satisfies the Law -/

/-- The concrete `scopistTranslator` obeys `ScopistLaw`: deterministic,
zero-drift, and packaging-only. This is the machine-checked certification that
the documented translation mapping is axiom-clean. -/
@[proof]
theorem scopistTranslator_satisfies_law : ScopistLaw scopistTranslator :=
  { deterministic := by
      intro r1 r2 hli hp hd hs hv
      change scopistTranslate r1 = scopistTranslate r2
      exact scopist_deterministic r1 r2 hli hp hd hs hv
    zero_drift := by
      intro r hv
      change (scopistTranslate r).attestation = AttestationState.UNATTESTED
      exact scopist_zero_drift r hv
    risk_never_recalculated := by
      intro r
      change (scopistTranslate r).risk_level = riskLevelOf r
      rfl }

/-! ## 5. Law-Level Consequences (Binding the Narrative) -/

/-- **Consequence: Zero-Drifts.** Any translator obeying `ScopistLaw` forces an
`UNATTESTED` narrative on every `SIG_GOV_KILL` verdict — the legal layer is
mathematically forbidden from mitigating the kill. -/
@[proof]
theorem law_zero_drift_forces_unattested (scopist : LegaleseScopist) (law : ScopistLaw scopist)
    (r : ContractivityReceipt) (hv : r.verdict = ExecutionState.SIG_GOV_KILL) :
    (scopist.translate r).attestation = AttestationState.UNATTESTED :=
  law.zero_drift r hv

/-- **Consequence: Packaging-Only.** Every OSCAL model produced under `ScopistLaw`
carries receipt-verbatim risk — the Scopist cannot recalculate or re-interpret
the execution engine's numbers. -/
@[proof]
theorem law_risk_binds_verbatim (scopist : LegaleseScopist) (law : ScopistLaw scopist)
    (r : ContractivityReceipt) :
    (scopist.translate r).risk_level = riskLevelOf r :=
  law.risk_never_recalculated r

/-! ## 6. Concrete Receipt Scenarios (mirroring the Rust/Kani harness) -/

/-- A nominal receipt: `‖Ψ‖₊ = 0.5`, `Δ = 0.002` (scaled), with a hashed R1CS
manifest — the only shape allowed to attest. -/
def nominalReceipt : ContractivityReceipt :=
  { lift_id := "lift-0001"
    l_phi := 500_000_000
    delta := 2_000_000
    sigma_proof := "r1cs-manifest sha256:9f86d081884c7d659a2feaa0c55ad015"
    verdict := ExecutionState.NOMINAL }

/-- A kill receipt: `‖Ψ‖₊` breaches the `(1 − ε)` bound and `Δ` breaches drift —
the engine issued `SIG_GOV_KILL`. The narrative *must* reflect an unattested
state. -/
def killReceipt : ContractivityReceipt :=
  { lift_id := "lift-0099"
    l_phi := CONTRACTIVITY_BOUND_SCALED + 1
    delta := DRIFT_LIMIT_SCALED + 20000000
    sigma_proof := ""
    verdict := ExecutionState.SIG_GOV_KILL }

@[proof]
theorem nominalWithinScale : nominalReceipt.l_phi < RECEIPT_SCALE := by
  decide

@[proof]
theorem killBreachesBound : CONTRACTIVITY_BOUND_SCALED < killReceipt.l_phi := by
  decide

@[proof]
theorem nominalReceipt_is_attested :
    (scopistTranslate nominalReceipt).attestation = AttestationState.ATTESTED := by
  decide

@[proof]
theorem nominalReceipt_risk_verbatim :
    (scopistTranslate nominalReceipt).risk_level = nominalReceipt.delta := by
  decide

@[proof]
theorem killReceipt_is_unattested :
    (scopistTranslate killReceipt).attestation = AttestationState.UNATTESTED := by
  decide

@[proof]
theorem killReceipt_risk_pinned :
    (scopistTranslate killReceipt).risk_level = KILL_RISK_SCALED := by
  decide

@[proof]
theorem killReceipt_never_attests :
    (scopistTranslate killReceipt).attestation ≠ AttestationState.ATTESTED := by
  decide

@[proof]
theorem killReceipt_withholds_proof :
    (scopistTranslate killReceipt).proof_hash = "" := by
  decide

/-! ## 7. ADR-0068 Record and Governance Invariants -/

/-- ADR-0068 "OSCAL and PrismPM", transcribed as an `ADR` record from
`docs/adr/accepted/0068-OSCAL and PrismPM.md`. -/
@[adr]
def ADR_0068 : ADR :=
  { id := "ADR-0068"
    title := "OSCAL and PrismPM"
    status := ADRStatus.Accepted
    context := "PrismPM transforms .lex.tex models into verified artifacts, while enterprise compliance requires standardized reporting such as NIST OSCAL. If the compliance narrative were computed or negotiated independently of the settled mathematical execution, a contractivity/drift breach (SIG_GOV_KILL) could be reported as an accepted state. The P²C Core v1.1 Witness Calculus mandate forbids this: calculations are the sole domain of the physical execution engine, and compliance must be a consequence of exact arithmetic — not a sociologically negotiated paper trail."
    decision := "Adopt the Legalese Scopist as the exclusive, read-only translation mapping layer downstream of PrismPM and the Sedona Spine. It ingests the cryptographically sealed ContractivityReceipt R emitted when artifacts are evaluated, applies the deterministic mapping f_Scopist(R) = Narrative_legal to produce an OSCAL assessment-result model, and is mathematically forbidden from recalculating, negotiating, or re-interpreting risk. OSCAL is packaging-only (an optional read-only export envelope, never a runtime attester); any OSCAL Assessment Result (SAR) lacking a hashed R1CS compiler manifest or Lean proof hash must explicitly mark its evidence as UNATTESTED. The Scopist law is enforced inside an axiom-clean Lean 4 core."
    consequences := [
      "Zero-drift enforcement: a SIG_GOV_KILL verdict always yields an UNATTESTED narrative — the legal layer cannot mitigate a kill.",
      "Deterministic translation: identical receipts (same lift id, ‖Ψ‖₊, Δ, proof hash, verdict) produce identical narratives (idempotency & purity).",
      "Packaging-only OSCAL: risk is copied verbatim from the receipt (never recalculated); OSCAL is a read-only narrative envelope, never a runtime attester.",
      "Unattested markings: an SAR lacking a hashed R1CS compiler manifest or Lean proof hash is explicitly marked UNATTESTED.",
      "Negative: rigorous schema alignment between PrismPM model definitions and the Scopist mapping is mandatory to prevent translation failures."
    ]
    supersedes := none
    links := [
      ⟨"0068-OSCAL and PrismPM", .SpecificationDoc, "Source ADR (docs/adr/accepted/0068-OSCAL and PrismPM.md)"⟩
      , ⟨"crates/legalese-scopist", .SourceFile, "Legalese Scopist layer (Rust): FFI translation stack"⟩
      , ⟨"packages/rust/sedona_spine", .SourceFile, "Sedona Spine: ContractivityReceipt (R) execution rail"⟩
      , ⟨"ADR/OSCAL.lean", .LeanDeclaration, "Zero-sorry formal model of ADR-0068 (this file)"⟩
    ] }

@[proof]
theorem adr0068_accepted : ADR_0068.status = ADRStatus.Accepted := by
  rfl

/-- Once Accepted, ADR-0068 cannot transition back to Proposed
(`ADR.Proofs.accepted_cannot_revert_to_proposed`). -/
@[proof]
theorem adr0068_accepted_no_revision (w : Option ADRId)
    (h : ValidTransition .Accepted .Proposed w) : False :=
  accepted_cannot_revert_to_proposed w h

/-- ADR-0068 has no supersession edge to any parent: the singleton supersession
graph contains no cycles. -/
@[proof]
theorem adr0068_no_supersede_edge (parent : ADRId) :
    ¬ SupersedesRel [ADR_0068] "ADR-0068" parent := by
  rintro ⟨a, ham, haid, hasup⟩
  have haeq : a = ADR_0068 := List.mem_singleton.mp ham
  subst a
  simp [ADR_0068] at hasup

/-- **No circular supersession (ADR-0068):** `StrictAcyclic [ADR_0068]`. -/
@[proof]
theorem adr0068_acyclic : StrictAcyclic [ADR_0068] := by
  intro id h
  rcases h with ⟨parent, hrel, _⟩
  by_cases hid : id = "ADR-0068"
  · subst id
    exact adr0068_no_supersede_edge parent hrel
  · rcases hrel with ⟨a, ham, haid, hasup⟩
    have haeq : a = ADR_0068 := List.mem_singleton.mp ham
    subst a
    exact hid (by simpa [ADR_0068] using haid.symm)

/-- The singleton registry containing ADR-0068 satisfies every `ADRRegistry`
invariant: unique ids, acyclicity, supersession hygiene, no conflicts, coherent
claims. -/
def ADR_0068_Registry : ADRRegistry :=
  { adrs := [ADR_0068]
    uniqueIds := by decide
    acyclic := adr0068_acyclic
    supersedesExist := by
      intro a ha sid hs
      have haeq : a = ADR_0068 := List.mem_singleton.mp ha
      subst a
      simp [ADR_0068] at hs
    supersededStatusConsistent := by
      intro a ha sid hs
      have haeq : a = ADR_0068 := List.mem_singleton.mp ha
      subst a
      simp [ADR_0068] at hs
    noConflicts := by
      intro a ha b hb hc
      have haeq : a = ADR_0068 := List.mem_singleton.mp ha
      have hbeq : b = ADR_0068 := List.mem_singleton.mp hb
      subst haeq hbeq
      rcases hc with ⟨hne, _, _, _⟩
      exact hne rfl
    claims := []
    claimsOwnedByAccepted := by
      intro c hc
      simp at hc
    noClaimConflicts := by
      intro c₁ hc₁ c₂ hc₂ hne
      simp at hc₁
  }

/-- **Traceability:** the accepted ADR-0068 possesses a reconstructible
provenance path in its registry (`ADR.Proofs.registry_self_traceable`). -/
@[proof]
theorem adr0068_traceable : ProvenancePath [ADR_0068] "ADR-0068" "ADR-0068" := by
  exact registry_self_traceable ADR_0068_Registry ADR_0068 (by native_decide)

/-! ## 8. Consequence Entailment via the Embedded Logic (`PropTerm`/`Entails`)

The consequences of ADR-0068 are discharged as *logical consequences* of the
decision and context using the embedded propositional logic of `ADR.Core`
(`Entails`). Each consequence below is *derived*, never asserted.
-/

/-- The decision's contract, lifted to the embedded propositional logic:
adopt the Scopist as read-only, ingest the sealed receipt, and enforce
zero-drift. -/
def adr0068DecisionProp : PropTerm :=
  .and (.atom "adoptScopistAsReadOnly")
       (.and (.atom "ingestSealedReceipt") (.atom "zeroDriftEnforced"))

/-- Left-elimination for a single conjunctive premise. -/
theorem and_elim_left_oscal {p q : PropTerm} : Entails [.and p q] p := by
  intro env hprem
  rcases hprem (.and p q) (by simp) with ⟨hp, _⟩
  exact hp

/-- Right-elimination for a single conjunctive premise. -/
theorem and_elim_right_oscal {p q : PropTerm} : Entails [.and p q] q := by
  intro env hprem
  rcases hprem (.and p q) (by simp) with ⟨_, hq⟩
  exact hq

/-- **Consequence: Read-Only Scopist Commitment.** The decision commits to the
Legalese Scopist as the exclusive read-only translation layer. -/
@[proof]
theorem adr0068_scopist_commitment :
    Entails [adr0068DecisionProp] (.atom "adoptScopistAsReadOnly") := by
  simpa [adr0068DecisionProp]
    using (and_elim_left_oscal (p := .atom "adoptScopistAsReadOnly")
      (q := .and (.atom "ingestSealedReceipt") (.atom "zeroDriftEnforced")))

/-- **Consequence: Sealed-Receipt Ingestion.** The decision commits to ingesting
the cryptographically sealed ContractivityReceipt R. -/
@[proof]
theorem adr0068_receipt_commitment :
    Entails [adr0068DecisionProp] (.atom "ingestSealedReceipt") := by
  intro env hprem
  rcases hprem adr0068DecisionProp (by simp [adr0068DecisionProp]) with ⟨_, hbc⟩
  rcases hbc with ⟨hb, _⟩
  exact hb

/-- **Consequence: Zero-Drift Mandate.** The decision commits to zero-drift
enforcement. -/
@[proof]
theorem adr0068_zero_drift_mandate :
    Entails [adr0068DecisionProp] (.atom "zeroDriftEnforced") := by
  intro env hprem
  rcases hprem adr0068DecisionProp (by simp [adr0068DecisionProp]) with ⟨_, hbc⟩
  rcases hbc with ⟨_, hc⟩
  exact hc

/-- **Consequence: Kills Cannot Be Mitigated.** The zero-drift mandate entails
(by modus ponens, `ADR.Proofs.entailment_modus_ponens`) that a `SIG_GOV_KILL`
always yields an UNATTESTED narrative. -/
@[proof]
theorem adr0068_zero_drift_consequence_entailed :
    Entails [.atom "zeroDriftEnforced",
             .implies (.atom "zeroDriftEnforced") (.atom "killNarrativesUnattested")]
            (.atom "killNarrativesUnattested") :=
  entailment_modus_ponens _ _

/-- **Consequence: Packaging-Only OSCAL.** The read-only Scopist commitment
entails (modus ponens) that OSCAL is a packaging-only narrative envelope, never
a runtime attester. -/
@[proof]
theorem adr0068_packaging_only_entailed :
    Entails [.atom "adoptScopistAsReadOnly",
             .implies (.atom "adoptScopistAsReadOnly") (.atom "oscalPackagingOnly")]
            (.atom "oscalPackagingOnly") :=
  entailment_modus_ponens _ _

/-- **Consequence: Unattested Markings.** The zero-drift mandate entails (modus
ponens) that an SAR lacking a hashed R1CS / Lean proof manifest is UNATTESTED. -/
@[proof]
theorem adr0068_unattested_marking_entailed :
    Entails [.atom "zeroDriftEnforced",
             .implies (.atom "zeroDriftEnforced") (.atom "unattestedMarkings")]
            (.atom "unattestedMarkings") :=
  entailment_modus_ponens _ _

/-! ## 9. Intentional Failure Cases (Type System Catches Them)

These `example` blocks are *supposed* to be rejected by the type system. They are
commented out deliberately: re-enabling any of them must fail to compile, which is
the working proof that the model is not vacuous.
-/

--    example : (scopistTranslate killReceipt).attestation = AttestationState.ATTESTED := by
--      decide    -- FALSE: SIG_GOV_KILL is never attestable — must NOT compile.

--    example : (scopistTranslate killReceipt).proof_hash = "r1cs-manifest sha256:deadbeef" := by
--      decide    -- FALSE: a kill withholds the manifest — must NOT compile.

--    example : (scopistTranslate nominalReceipt).attestation = AttestationState.UNATTESTED := by
--      decide    -- FALSE: a NOMINAL receipt attests — must NOT compile.

--    -- A malicious translator that attests every receipt violates zero_drift:
--    example : ScopistLaw ⟨fun _ => ⟨"", AttestationState.ATTESTED, "", 0⟩⟩ := by
--      intro law
--      exact law.zero_drift ⟨"l", 0, 0, "", ExecutionState.SIG_GOV_KILL⟩ rfl
--        -- must NOT compile (the zero_drift field is unprovable).

end OSCAL
end ADR