import LorenzAttractor.Core
import LorenzAttractor.Dynamics
import LorenzAttractor.FeedbackTensor
import LorenzAttractor.Examples

/-! # LorenzAttractor.Export

Generates formal verification Markdown reports and trajectory logs from the Lean 4 formalization.
-/

namespace LorenzAttractor

/-- Generate full formal verification report string. -/
def generateMarkdownReport : String :=
  let (finalCanonical, _) := runStabilizedSimulation 20
  let (finalPrime, _) := runPrimeSimulation 20

  let trCanon := theoreticalTrace canonicalParams
  let trPrime := theoreticalTrace (primeToLorenzParams primeParams7_29_3)

  let header := "# MULTIPLICITY-ENHANCED LORENZ ATTRACTOR: FORMAL REPORT\n\n" ++
    "**Generated by Lean 4.31.0 Formalization Substrate**\n\n---\n\n"

  let sec1 := "## 1. Classical vs Prime-Encoded Parameters\n" ++
    s!"- **Canonical Parameters**: sigma={canonicalParams.sigma / 1000}, rho={canonicalParams.rho / 1000}, beta={canonicalParams.betaNum / (canonicalParams.betaDen * 1000)}\n" ++
    s!"- **Canonical Jacobian Trace Tr(J)**: {trCanon / 1000} (Dissipative volume contraction)\n" ++
    s!"- **Prime Parameters**: (p1=7, p2=29, p3=3)\n" ++
    s!"- **Prime Jacobian Trace Tr(J)**: {trPrime / 1000}\n\n---\n\n"

  let sec2 := "## 2. Multiplicity Unified Dynamics & Stability\n" ++
    s!"- **Simulation Steps**: 20 integration steps\n" ++
    s!"- **Canonical Final Point**: ({finalCanonical.point.x / 1000}, {finalCanonical.point.y / 1000}, {finalCanonical.point.z / 1000})\n" ++
    s!"- **Canonical Final S(t) Stability Metric**: {finalCanonical.stabilityIntegral}\n" ++
    s!"- **Prime-Encoded Final Point**: ({finalPrime.point.x / 1000}, {finalPrime.point.y / 1000}, {finalPrime.point.z / 1000})\n" ++
    s!"- **Prime-Encoded Final S(t) Stability Metric**: {finalPrime.stabilityIntegral}\n\n---\n\n"

  let sec3 := "## 3. Machine-Checked Invariants\n" ++
    "1. `time_advances_monotonically` — Proven monotonic temporal evolution\n" ++
    "2. `theoretical_trace_negative` — Proven dissipative volume contraction for positive regimes\n" ++
    "3. `prime_params_strictly_positive` — Proven positivity under prime encoding\n" ++
    "4. `clamp_bounds_x` — Proven compact domain invariance on X-axis\n" ++
    "5. `clamp_bounds_y` — Proven compact domain invariance on Y-axis\n" ++
    "6. `clamp_bounds_z` — Proven compact domain invariance on Z-axis\n" ++
    "7. `jacobian_trace_exact` — Proven evaluated Jacobian trace identically matches theoretical trace\n" ++
    "8. `lorenz_origin_velocity_zero` — Proven origin (0,0,0) is stationary equilibrium point\n" ++
    "9. `prime_parameters_preserve_dissipativity` — Proven volume contraction Tr(J) < 0 under prime parameters\n" ++
    "10. `stability_integral_monotonic` — Proven monotonicity of stability functional S(t)\n"

  header ++ sec1 ++ sec2 ++ sec3

/-- Export report to file system. -/
def exportReportToFile (path : String) : IO Unit := do
  IO.FS.writeFile path generateMarkdownReport
  IO.println s!"[+] Successfully exported formal verification report to {path}"

end LorenzAttractor
