import math
from decimal import Decimal, getcontext

# Set precision for log calculation
getcontext().prec = 50

primes = [2, 3, 5, 7, 11, 13, 17]
den = 10**15

def get_q_string(val):
    num = int(val * den)
    return f"⟨{num}, {den}⟩"

print("/-")
print("  Concrete Lefschetz-derived data for T1 truncation.")
print("  Generated by scripts/generate_lefschetz_data.py")
print("-/")
print("\nimport F1Square.Analysis.Real")
print("import F1Square.Analysis.ROrder")
print("import F1Square.IntersectionTemplate")
print("\nnamespace UOR.Bridge.F1Square.LefschetzData")
print("\nopen UOR.Bridge.F1Square.Analysis")
print("open UOR.Bridge.F1Square.IntersectionTemplate")
print("\n/-- Prime log approximations as Real constants. --/")

for p in primes:
    log_p = Decimal(p).ln()
    q_str = get_q_string(log_p)
    print(f"def log{p} : Real := ofQ {q_str} (by decide)")

print("\n/-- The finite prime list. --/")
print("def T1_primes : List Nat := [2, 3, 5, 7, 11, 13, 17]")

print("\n/-- Concrete template data for n=7. --/")
print("def t1_data : TemplateData 7 := {")
print("  d := ofQ ⟨-1, 1⟩ (by decide),")
print("  a := fun i j => if i = j then")
print("    match i.val with")
for i, p in enumerate(primes):
    print(f"    | {i} => log{p}")
print("    | _ => zero")
print("    else zero,")
print("  b := fun i j => if i = j then")
print("    match i.val with")
for i, p in enumerate(primes):
    print(f"    | {i} => log{p}")
print("    | _ => zero")
print("    else zero,")
print("  c := fun i j => if i = j then ofQ ⟨-1, 1⟩ (by decide) else zero,")
print("  a_sym := fun i j => by sorry,")
print("  b_sym := fun i j => by sorry,")
print("  c_sym := fun i j => by sorry,")
print("  trace_condition := zero")
print("}")

print("\n/-- Proof that d ≤ 0 for t1_data. --/")
print("theorem t1_d_nonpos : Rle t1_data.d zero := by")
print("  intro n; unfold t1_data; dsimp")
print("  show Qle ⟨-1, 1⟩ (add (zero.seq n) ⟨2, n + 1⟩)")
print("  simp [zero, ofQ]; unfold Qle add; push_cast; omega")

print("\nend UOR.Bridge.F1Square.LefschetzData")
