"""ADR-026 Phase 1: Certification Pipeline Gate Tests

Purpose:
    Ensure the integrated certification pipeline (clone-check + audit trace + badge issuance)
    behaves correctly and enforces governance constraints.

Blocking condition:
    Any failing test means ADR-026 is incomplete.

Tests:
    1. Certification fails if clone-check status != PASS
    2. Certification fails if audit trace is missing
    3. Certification succeeds when clone-check passes and audit trace exists
    4. Certification is deterministic (same inputs → same badge fingerprint)

Provenance: MultiplicityFoundation/Meta-Relativity
"""

import json
import os
import tempfile

from pirtm.core.attestation import SignedPIRTMAttestation
from pirtm.transpiler.cli import PirtmCLI


class TestGate1CloneCheckMustPass:
    """Certification should fail when clone-check status is not PASS."""

    def test_certify_fails_when_clone_check_not_pass(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            cand_path = os.path.join(tmpdir, "cand.py")
            ref_path = os.path.join(tmpdir, "ref.py")
            audit_path = os.path.join(tmpdir, "audit.jsonl")
            registry_path = os.path.join(tmpdir, "registry.json")

            # Use identical code to force clone-check FAIL
            code = "print('same')\n"
            with open(cand_path, "w") as f:
                f.write(code)
            with open(ref_path, "w") as f:
                f.write(code)
            with open(audit_path, "w") as f:
                f.write("{}\n")

            cli = PirtmCLI()
            rv = cli.cmd_certify(
                type("A", (), {
                    "candidate": cand_path,
                    "reference": ref_path,
                    "audit_trace": audit_path,
                    "registry": registry_path,
                    "module": "xi_operator",
                    "prime": 17,
                    "issuer": "test",
                    "certificate_id": "cert-1",
                    "metadata": None,
                })
            )
            assert rv != 0


class TestGate2AuditTraceAutoGenerated:
    """Certification should auto-generate an audit trace when none is provided."""

    def test_certify_auto_generates_audit_trace(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            cand_path = os.path.join(tmpdir, "cand.py")
            ref_path = os.path.join(tmpdir, "ref.py")
            registry_path = os.path.join(tmpdir, "registry.json")

            # Use distinct code to ensure clone-check PASS
            with open(cand_path, "w") as f:
                f.write("def foo():\n    return sum(range(10))\n")
            with open(ref_path, "w") as f:
                f.write("def bar(x):\n    r = 1\n    for i in range(x):\n        r *= i + 1\n    return r\n")

            audit_path = os.path.join(tmpdir, "generated.audit.jsonl")

            cli = PirtmCLI()
            rv = cli.cmd_certify(
                type("A", (), {
                    "candidate": cand_path,
                    "reference": ref_path,
                    "audit_trace": audit_path,
                    "registry": registry_path,
                    "module": "xi_operator",
                    "prime": 17,
                    "issuer": "test",
                    "certificate_id": "cert-1",
                    "metadata": None,
                })
            )
            assert rv == 0
            assert os.path.exists(audit_path)

            # The audit trace should be JSONL with at least one line
            with open(audit_path, "r") as f:
                lines = [l.strip() for l in f if l.strip()]
            assert len(lines) > 0


class TestGate3SuccessfulCertification:
    """Certification should succeed when clone-check passes and audit trace exists."""

    def test_certify_succeeds(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            cand_path = os.path.join(tmpdir, "cand.py")
            ref_path = os.path.join(tmpdir, "ref.py")
            audit_path = os.path.join(tmpdir, "audit.jsonl")
            registry_path = os.path.join(tmpdir, "registry.json")

            with open(cand_path, "w") as f:
                f.write("def foo():\n    return sum(range(10))\n")
            with open(ref_path, "w") as f:
                f.write("def bar(x):\n    r = 1\n    for i in range(x):\n        r *= i + 1\n    return r\n")

            with open(audit_path, "w") as f:
                f.write("{}\n")

            cli = PirtmCLI()
            rv = cli.cmd_certify(
                type("A", (), {
                    "candidate": cand_path,
                    "reference": ref_path,
                    "audit_trace": audit_path,
                    "registry": registry_path,
                    "module": "xi_operator",
                    "prime": 17,
                    "issuer": "test",
                    "certificate_id": "cert-1",
                    "metadata": None,
                })
            )
            assert rv == 0
            assert os.path.exists(registry_path)

            with open(registry_path, "r") as f:
                registry = json.load(f)

            entry = registry["entries"][0]
            attestation = entry["metadata"]["pirtm_attestation"]
            assert attestation["attestation_type"] == "pirtm-native"
            assert attestation["certificate_kind"] == "module"
            assert attestation["prime_index"] == 17

            signed_attestation = entry["metadata"]["signed_pirtm_attestation"]
            receipt = SignedPIRTMAttestation.from_dict(signed_attestation)
            assert receipt.algorithm == "bls12-381"
            assert receipt.verify() is True
            assert signed_attestation["attestation"]["proof_hash"] == attestation["proof_hash"]


class TestGate4DeterministicCertification:
    """Certification should produce deterministic badge fingerprints."""

    def test_certify_deterministic(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            cand_path = os.path.join(tmpdir, "cand.py")
            ref_path = os.path.join(tmpdir, "ref.py")
            audit_path = os.path.join(tmpdir, "audit.jsonl")
            registry_path = os.path.join(tmpdir, "registry.json")

            with open(cand_path, "w") as f:
                f.write("def foo():\n    return sum(range(10))\n")
            with open(ref_path, "w") as f:
                f.write("def bar(x):\n    r = 1\n    for i in range(x):\n        r *= i + 1\n    return r\n")

            with open(audit_path, "w") as f:
                f.write("{}\n")

            cli = PirtmCLI()
            for _ in range(2):
                rv = cli.cmd_certify(
                    type("A", (), {
                        "candidate": cand_path,
                        "reference": ref_path,
                        "audit_trace": audit_path,
                        "registry": registry_path,
                        "module": "xi_operator",
                        "prime": 17,
                        "issuer": "test",
                        "certificate_id": "cert-1",
                        "metadata": None,
                    })
                )
                assert rv == 0

            with open(registry_path, "r") as f:
                data = json.load(f)

            entries = data.get("entries", [])
            assert len(entries) == 1
            fingerprint = entries[0]["certificate_id"]
            # certificate_id should be stable when explicitly provided
            assert fingerprint == "cert-1"


class TestGate5StrictAuditTraceMode:
    """Strict mode should fail if existing audit trace does not match expected deterministic trace."""

    def test_certify_strict_mode_detects_mismatch(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            cand_path = os.path.join(tmpdir, "cand.py")
            ref_path = os.path.join(tmpdir, "ref.py")
            audit_path = os.path.join(tmpdir, "strict.audit.jsonl")
            registry_path = os.path.join(tmpdir, "registry.json")

            with open(cand_path, "w") as f:
                f.write("def foo():\n    return sum(range(10))\n")
            with open(ref_path, "w") as f:
                f.write("def bar(x):\n    r = 1\n    for i in range(x):\n        r *= i + 1\n    return r\n")

            # Create a mismatched audit trace
            with open(audit_path, "w") as f:
                f.write("{\"foo\":\"bar\"}\n")

            cli = PirtmCLI()
            rv = cli.cmd_certify(
                type("A", (), {
                    "candidate": cand_path,
                    "reference": ref_path,
                    "audit_trace": audit_path,
                    "registry": registry_path,
                    "module": "xi_operator",
                    "prime": 17,
                    "issuer": "test",
                    "certificate_id": "cert-1",
                    "metadata": None,
                    "strict": True,
                })
            )
            assert rv != 0

    def test_certify_strict_mode_allows_matching_trace(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            cand_path = os.path.join(tmpdir, "cand.py")
            ref_path = os.path.join(tmpdir, "ref.py")
            audit_path = os.path.join(tmpdir, "strict.audit.jsonl")
            registry_path = os.path.join(tmpdir, "registry.json")

            with open(cand_path, "w") as f:
                f.write("def foo():\n    return sum(range(10))\n")
            with open(ref_path, "w") as f:
                f.write("def bar(x):\n    r = 1\n    for i in range(x):\n        r *= i + 1\n    return r\n")

            cli = PirtmCLI()
            rv = cli.cmd_certify(
                type("A", (), {
                    "candidate": cand_path,
                    "reference": ref_path,
                    "audit_trace": audit_path,
                    "registry": registry_path,
                    "module": "xi_operator",
                    "prime": 17,
                    "issuer": "test",
                    "certificate_id": "cert-1",
                    "metadata": None,
                    "strict": True,
                })
            )
            assert rv == 0
