'use client';

import React, { useState } from 'react';
import { ResearchPaper } from '@/types/research';
import { FileText, Download, Copy, Check, Sparkles } from 'lucide-react';

interface ReportGeneratorViewProps {
  papers: ResearchPaper[];
}

export default function ReportGeneratorView({ papers }: ReportGeneratorViewProps) {
  const [reportTitle, setReportTitle] = useState('Autonomous Agent Architectures and Universal Object References');
  const [copied, setCopied] = useState(false);

  const generatedMarkdown = `# ${reportTitle}

## Abstract
Recent advancements in agentic language models and decentralized knowledge substrates require robust verification frameworks. This paper synthesizes current literature on self-correcting agent memory (Reflexion), multi-agent communication protocols (AutoGen), and immutable UOR addressing schemes.

## 1. Introduction
The integration of large language models into autonomous research workflows demands rigorous citation tracking and memory management. Traditional zero-shot generation often suffers from hallucination and link rot.

## 2. Literature Review
### 2.1 Reflexion Framework
Shinn et al. (2024) introduce actor-evaluator feedback loops, enabling agents to improve task performance through trial-and-error reflection.
* **Key Finding:** Achieves 91% pass rate on HumanEval.
* **UOR Reference:** \`uor:obj:paper:reflexion-2024\`

### 2.2 AutoGen Multi-Agent Messaging
Wu et al. (2024) formalize multi-agent conversations as a foundational programming paradigm, streamlining complex problem decomposition.
* **UOR Reference:** \`uor:obj:paper:autogen-2024\`

### 2.3 Universal Object Reference (UOR) Substrate
Foundation et al. (2025) propose cryptographic content-derived addressing to replace traditional URLs, eliminating scholarly link rot.
* **UOR Reference:** \`uor:obj:paper:uor-substrate-2025\`

## 3. Conclusion & Future Work
By combining self-correcting memory loops with immutable UOR registries, researchers can achieve high-fidelity scientific automation and verifiable attribution.

---
*Generated by ResearchLM PrismPM v2.4*
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedMarkdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6 pb-12">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 dark:text-white tracking-tight flex items-center space-x-2">
            <FileText className="w-6 h-6 text-indigo-600" />
            <span>Academic Draft & Report Generator</span>
          </h1>
          <p className="text-sm text-slate-500 dark:text-slate-400">
            Compile indexed literature and synthesis into structured academic drafts with BibTeX references.
          </p>
        </div>
        <div className="flex items-center space-x-3">
          <button
            onClick={handleCopy}
            className="inline-flex items-center space-x-2 px-4 py-2.5 rounded-xl bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-200 border border-slate-300 dark:border-slate-700 font-semibold text-sm hover:bg-slate-50 dark:hover:bg-slate-700 transition shadow-sm"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-500" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? 'Copied!' : 'Copy Markdown'}</span>
          </button>
        </div>
      </div>

      {/* Title Input */}
      <div className="bg-white dark:bg-slate-800 p-6 rounded-2xl border border-slate-200 dark:border-slate-700 shadow-sm space-y-4">
        <label className="block text-xs font-semibold uppercase text-slate-500 dark:text-slate-400">Report Title</label>
        <input
          type="text"
          value={reportTitle}
          onChange={(e) => setReportTitle(e.target.value)}
          className="w-full px-4 py-3 rounded-xl border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-white text-base font-semibold focus:outline-none focus:ring-2 focus:ring-indigo-500 shadow-sm"
        />
      </div>

      {/* Rendered Preview / Editor */}
      <div className="bg-white dark:bg-slate-800 p-8 rounded-2xl border border-slate-200 dark:border-slate-700 shadow-sm space-y-6">
        <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-700 pb-4">
          <span className="text-xs font-semibold uppercase tracking-wider text-indigo-600 dark:text-indigo-400">
            Markdown Academic Preview
          </span>
          <span className="text-xs text-slate-400 font-mono">PrismPM Exporter</span>
        </div>
        <div className="prose dark:prose-invert max-w-none text-sm text-slate-700 dark:text-slate-300 leading-relaxed space-y-4 whitespace-pre-wrap font-mono bg-slate-50 dark:bg-slate-900 p-6 rounded-xl border border-slate-200 dark:border-slate-800">
          {generatedMarkdown}
        </div>
      </div>

    </div>
  );
}
