apiVersion: v1
kind: Secret
metadata:
  name: {{ include "phase-mirror-agent.fullname" . }}-keys
type: Opaque
data:
  operator.key: {{ required "A valid operator key must be provided via .Values.secrets.operatorKey" .Values.secrets.operatorKey | b64enc | quote }}
