{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "phase-mirror-agent.fullname" . }}
  labels:
    {{- include "phase-mirror-agent.selectorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "phase-mirror-agent.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
{{- end }}
