/-
F1 square — v0.21.0 stage G, brick **Atlas calculus**: the seven operators, the free-monoid `Term`,
and the catamorphism (§3/§4) — "form determines function".

Discovering the operational-calculus facet. Expression in the Atlas is generated by SEVEN operators
(`mark, copy, swap, merge, split, quote, evaluate`, §3), composed sequentially by `∘` (associative,
unit `ε`). The signature's initial algebra is `Term` (§3/§4); resolution is the catamorphism — the
unique fold out of `Term` into any semantics (§4: "because `Term` is initial, any chosen semantics
receives a unique homomorphism out of it, and that homomorphism is the fold").

Formalized here as the FREE MONOID on the seven operators:
- `Op` with exactly seven constructors (`op_count`); `Term = List Op`, sequential composition `++`,
  associative with unit `[]` (`term_assoc`, `term_unit_left/right`) — the §3 monoid `(∘, ε)`.
- `cata` — the fold into any carrier `(M, e, mul)`; `cata_append` proves it is a homomorphism for a
  monoid, and `cata_unique` proves it is THE UNIQUE one extending the generators. That is the
  initiality of `Term` (§4): form (the signature) determines function (the fold).

Implication / connection. This is the categorical core: the free monoid is the initial object of its
algebras, and the catamorphism is the unique mediating morphism — exactly Lambek/initial-algebra
semantics. The Atlas's "declarative principle" (define the structure, the function is determined) is
this universal property, mechanized. It is the same initiality that pins `𝕊` (the coproduct) and
`H¹` (free on one generator) elsewhere in the build — one principle, three objects.

Pure Lean 4 core, no Mathlib, no `sorry`/`native_decide`, choice-free; audited by
`scripts/honesty_audit.sh`.
-/

import Foundations.F1.Square.AtlasCharacteristics

namespace Multiplicity.UOR.Bridge.F1Square.Square

/-- **The seven operators** of the Atlas's operational calculus (§3). -/
inductive Op
  | mark | copy | swap | merge | split | quote | evaluate
  deriving DecidableEq, Repr

/-- The list of all seven operators. -/
def allOps : List Op := [.mark, .copy, .swap, .merge, .split, .quote, .evaluate]

/-- **There are exactly seven operators** (§3). -/
theorem op_count : allOps.length = 7 := rfl

/-- **`Term`**: the free structure on the operators — sequential composition `∘` is list append,
    unit `ε` is `[]` (§3/§4, the initial algebra of the signature). -/
abbrev Term := List Op

/-- Sequential composition is **associative** (the `∘` monoid of §3). -/
theorem term_assoc (s t u : Term) : (s ++ t) ++ u = s ++ (t ++ u) := List.append_assoc s t u

/-- `ε = []` is a **left unit**. -/
theorem term_unit_left (t : Term) : [] ++ t = t := rfl

/-- `ε = []` is a **right unit**. -/
theorem term_unit_right (t : Term) : t ++ [] = t := List.append_nil t

/-- **The catamorphism** (§4, the fold): the map `Term → M` into a carrier `(M, e, mul)` extending a
    semantics `f : Op → M`. -/
def cata {M : Type} (e : M) (mul : M → M → M) (f : Op → M) : Term → M
  | [] => e
  | op :: rest => mul (f op) (cata e mul f rest)

/-- **The fold is a homomorphism** (for a monoid carrier): `cata (s ∘ t) = cata s ⬝ cata t`. -/
theorem cata_append {M : Type} (e : M) (mul : M → M → M)
    (assoc : ∀ a b c, mul (mul a b) c = mul a (mul b c)) (unitL : ∀ a, mul e a = a)
    (f : Op → M) (s t : Term) :
    cata e mul f (s ++ t) = mul (cata e mul f s) (cata e mul f t) := by
  induction s with
  | nil => exact (unitL (cata e mul f t)).symm
  | cons op rest ih =>
    show mul (f op) (cata e mul f (rest ++ t)) = mul (mul (f op) (cata e mul f rest)) _
    rw [ih]; exact (assoc (f op) (cata e mul f rest) (cata e mul f t)).symm

/-- **THE UNIVERSAL PROPERTY** (`Term` is initial, §4): any homomorphism `h : Term → M` extending the
    generators `f` IS the fold `cata`. So the fold is unique — form determines function. -/
theorem cata_unique {M : Type} (e : M) (mul : M → M → M) (f : Op → M) (h : Term → M)
    (h_unit : h [] = e) (h_mul : ∀ s t, h (s ++ t) = mul (h s) (h t))
    (h_ext : ∀ op, h [op] = f op) :
    ∀ t, h t = cata e mul f t := by
  intro t
  induction t with
  | nil => exact h_unit
  | cons op rest ih =>
    show h (op :: rest) = mul (f op) (cata e mul f rest)
    rw [show (op :: rest) = [op] ++ rest from rfl, h_mul, h_ext, ih]

end Multiplicity.UOR.Bridge.F1Square.Square
