apiVersion: v1
kind: Service
metadata:
  name: {{ include "phase-mirror-operator.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ws
      protocol: TCP
      name: ws
  selector:
    app: {{ include "phase-mirror-operator.name" . }}
