// ADR-008: Halo2-based Batch Aggregation Circuit
//
// Integrates `snark-verifier` to natively aggregate BN254 Groth16 
// proofs generated by `attestation.circom`.

use halo2_proofs::{
    circuit::{Layouter, SimpleFloorPlanner, Value},
    plonk::{Circuit, ConstraintSystem, Error, Column, Instance},
    halo2curves::bn256::{Bn256, Fr, G1Affine, G2Affine},
};
use snark_verifier::{
    loader::halo2::{halo2_ecc::ecc::EccChip, Halo2Loader},
    system::groth16::{Groth16Verifier, Groth16Proof, VerifyingKey},
    pcs::kzg::Bdfg21,
    util::arithmetic::FieldExt,
};
use halo2_base::{
    gates::{flex_gate::FlexGateConfig, range::RangeConfig, GateInstructions},
    Context, ContextParams,
};
use std::rc::Rc;

/// Halo2 Aggregation Configuration
#[derive(Clone, Debug)]
pub struct AggregationConfig {
    pub flex_gate: FlexGateConfig<Fr>,
    pub range: RangeConfig<Fr>,
    pub instance: Column<Instance>,
}

/// The structure holding the private witness data for the batch.
#[derive(Clone)]
pub struct BatchAggregationCircuit {
    pub vk: VerifyingKey<G1Affine, G2Affine>,
    pub proofs: Vec<Groth16Proof<G1Affine, G2Affine>>,
    pub instances: Vec<Vec<Fr>>,
    pub batch_merkle_root: Fr,
}

impl Circuit<Fr> for BatchAggregationCircuit {
    type Config = AggregationConfig;
    type FloorPlanner = SimpleFloorPlanner;

    fn without_witnesses(&self) -> Self {
        Self {
            vk: self.vk.clone(),
            proofs: vec![],
            instances: vec![],
            batch_merkle_root: Fr::zero(),
        }
    }

    fn configure(meta: &mut ConstraintSystem<Fr>) -> Self::Config {
        let flex_gate = FlexGateConfig::configure(meta, halo2_base::gates::flex_gate::Strategy::Vertical, &[], 1);
        let range = RangeConfig::configure(meta, flex_gate.clone(), &[], 10);
        let instance = meta.instance_column();
        meta.enable_equality(instance);

        AggregationConfig { flex_gate, range, instance }
    }

    fn synthesize(&self, config: Self::Config, mut layouter: impl Layouter<Fr>) -> Result<(), Error> {
        let mut first_pass = halo2_base::SKIP_FIRST_PASS;
        layouter.assign_region(
            || "Batch Aggregation",
            |region| {
                if first_pass {
                    first_pass = false;
                    return Ok(());
                }
                
                let ctx = Context::new(
                    region,
                    ContextParams {
                        max_rows: config.flex_gate.max_rows,
                        num_context_ids: 1,
                        tuning_params: halo2_base::halo2_proofs::circuit::Default::default(),
                    },
                );
                
                // Initialize the Halo2 Loader for snark-verifier
                let loader = Halo2Loader::<Bn256, EccChip<Fr>>::new(ctx, config.flex_gate.clone());

                // Load the VK as constants into the circuit
                let loaded_vk = loader.load_vk(&self.vk);

                // 1. Verify Groth16 Pairings
                for (proof, instances) in self.proofs.iter().zip(self.instances.iter()) {
                    let loaded_proof = loader.load_proof(proof);
                    let loaded_instances = loader.load_instances(instances);

                    // Groth16Verifier inherently performs the pairing checks
                    // e(A, B) = e(alpha, beta) * e(X, gamma) * e(C, delta)
                    // inside the Halo2 circuit.
                    Groth16Verifier::<Bn256, Halo2Loader<Bn256, EccChip<Fr>>>::verify(
                        &loaded_vk,
                        &loaded_instances,
                        &loaded_proof,
                    ).map_err(|_| Error::Synthesis)?;
                }

                // 2. Compute the Batch Merkle Root via Poseidon hash
                // TODO: Replace with PoseidonChip from halo2_gadgets once integrated.
                // The Poseidon hash must be computed over all instance vectors in the batch
                // to produce a single Merkle root that can be verified on-chain.
                //
                // Required integration:
                //   use halo2_gadgets::poseidon::{PoseidonChip, PoseidonInstructions};
                //   let poseidon_chip = PoseidonChip::construct(config.poseidon_config);
                //   let computed_root = poseidon_chip.hash(
                //       &mut layouter, &loaded_instances_flat, &poseidon_spec
                //   )?;
                //
                // For now, assign the provided batch_merkle_root as a witness.
                // The circuit owner MUST ensure this matches the off-chain Poseidon computation.
                let computed_root = loader.assign_scalar(self.batch_merkle_root);

                // 3. Constrain the computed root against the public instance column.
                // The public instance at index 0 is the expected Merkle root.
                // This enforces: circuit_computed_root == public_input_root
                loader.ctx_mut().constrain_equal(
                    &computed_root,
                    &loader.load_public_instance(0),
                );

                Ok(())
            },
        )
    }
}
