// src/basis.rs

#[cfg(feature = "lean_certified")]
pub mod certified {
    // Include the Lean-generated array.
    // This file is generated by `build.rs` from the Lean-certified JSON.
    include!(concat!(env!("OUT_DIR"), "/generated_vals_array.rs"));
}

#[cfg(not(feature = "lean_certified"))]
pub mod mock {
    // Fallback mock data for testing without the Lean pipeline.
    include!("basis_data.rs");
}

// Re-export the active basis.
#[cfg(feature = "lean_certified")]
pub use certified::*;

#[cfg(not(feature = "lean_certified"))]
pub use mock::*;
