use serde::{Deserialize, Serialize};

/// The Boundary Lattice G = P x B, where |G| = 12,288.
/// P = Z/48Z, B = Z/256Z.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct LatticeElement {
    pub p: u8, // 0..47
    pub b: u8, // 0..255
}

impl LatticeElement {
    pub fn new(p: u8, b: u8) -> Self {
        debug_assert!(p < 48);
        Self { p, b }
    }

    pub fn to_index(&self) -> usize {
        (self.p as usize * 256) + self.b as usize
    }

    pub fn from_index(index: usize) -> Self {
        debug_assert!(index < 12288);
        Self {
            p: (index / 256) as u8,
            b: (index % 256) as u8,
        }
    }
}

/// Subgroup U_ref of order 2048 generated by 11 commuting involutions.
pub struct URef {
    pub generators: [u64; 11],
}

impl URef {
    /// Canonical U_ref generators acting as XOR masks on the index representation.
    /// This is a simplified model of the involution action.
    pub fn canonical() -> Self {
        Self {
            generators: [
                1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024
            ],
        }
    }

    pub fn apply(&self, element: LatticeElement, mask: u16) -> LatticeElement {
        let mut index = element.to_index();
        for i in 0..11 {
            if (mask & (1 << i)) != 0 {
                index ^= self.generators[i] as usize;
            }
        }
        // Ensure index stays in range (simplified for initial derivation)
        LatticeElement::from_index(index % 12288)
    }
}

/// The 6 anchors that generate the 6 orbits of size 2048.
pub const ANCHORS: [LatticeElement; 6] = [
    LatticeElement { p: 0, b: 0 },
    LatticeElement { p: 8, b: 0 },
    LatticeElement { p: 16, b: 0 },
    LatticeElement { p: 24, b: 0 },
    LatticeElement { p: 32, b: 0 },
    LatticeElement { p: 40, b: 0 },
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct LatticeCertificate {
    pub total_elements: usize,
    pub orbit_sizes: [usize; 6],
    pub is_free_action: bool,
}

impl LatticeCertificate {
    pub fn verify() -> Self {
        let u_ref = URef::canonical();
        let mut orbit_sizes = [0; 6];
        let mut seen = std::collections::HashSet::new();
        let mut is_free_action = true;

        for (i, &anchor) in ANCHORS.iter().enumerate() {
            let mut orbit_count = 0;
            for mask in 0..2048 {
                let transformed = u_ref.apply(anchor, mask as u16);
                if !seen.insert(transformed) {
                    is_free_action = false;
                }
                orbit_count += 1;
            }
            orbit_sizes[i] = orbit_count;
        }

        Self {
            total_elements: seen.len(),
            orbit_sizes,
            is_free_action,
        }
    }
}

/// Resonance Class R96 (0..95).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct R96(pub u8);

impl R96 {
    pub fn from_lattice(element: LatticeElement) -> Self {
        // Derived mapping: P (0..47) and the first bit of B (0..255)
        // This partition creates 96 classes with 128 elements each.
        let class = (element.p * 2) + (element.b % 2);
        Self(class)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_lattice_tiling() {
        let cert = LatticeCertificate::verify();
        assert_eq!(cert.total_elements, 12288, "Lattice must have 12,288 elements");
        assert!(cert.is_free_action, "U_ref action must be free on anchors");
        for &size in cert.orbit_sizes.iter() {
            assert_eq!(size, 2048, "Each orbit must have 2048 elements");
        }
    }

    #[test]
    fn test_r96_distribution() {
        let mut counts = vec![0; 96];
        for i in 0..12288 {
            let el = LatticeElement::from_index(i);
            let class = R96::from_lattice(el);
            counts[class.0 as usize] += 1;
        }
        for &count in counts.iter() {
            assert_eq!(count, 128, "Each R96 class must have exactly 128 elements");
        }
    }
}
