//! ORT (ONNX Runtime) runner for cross-validation.
//!
//! Builds single-op ONNX graphs in memory and runs them through ORT to get
//! reference outputs. These are compared against `dispatch_float()` outputs.
//!
//! Gated behind the `conformance` feature.

/// Load ONNX fixture files from the `fixtures/` directory.
///
/// Fixtures are real `.onnx` files generated by `fixtures/generate.py`.
/// Tests load these instead of building models programmatically, mimicking
/// how real ONNX models are loaded from disk.
pub mod fixtures {
    use std::path::PathBuf;

    /// Root directory for fixture files.
    fn fixtures_dir() -> PathBuf {
        let mut dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        dir.push("fixtures");
        dir
    }

    /// Load a fixture by name (without `.onnx` extension).
    ///
    /// Returns `None` if the fixture file doesn't exist (test should skip).
    /// Panics on I/O errors other than "not found".
    pub fn load(name: &str) -> Option<Vec<u8>> {
        let path = fixtures_dir().join(format!("{name}.onnx"));
        match std::fs::read(&path) {
            Ok(bytes) => Some(bytes),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                eprintln!("SKIP: fixture {:?} not found", path);
                None
            }
            Err(e) => panic!("failed to read fixture {:?}: {e}", path),
        }
    }

    /// Load a fixture by name, panicking if not found.
    pub fn load_or_panic(name: &str) -> Vec<u8> {
        load(name).unwrap_or_else(|| {
            panic!(
                "fixture {name}.onnx not found in {:?} — run `python3 fixtures/generate.py`",
                fixtures_dir()
            )
        })
    }
}

#[cfg(feature = "conformance")]
pub mod runner {
    use anyhow::{Context, Result};
    use ort::{session::Session, value::Tensor};

    /// Input for ORT: name, shape, flat f32 data.
    pub struct OrtInput {
        pub name: String,
        pub shape: Vec<usize>,
        pub data: Vec<f32>,
    }

    /// Input for ORT that can carry either f32 or i64 data.
    pub enum OrtInputTyped {
        F32 {
            name: String,
            shape: Vec<usize>,
            data: Vec<f32>,
        },
        I64 {
            name: String,
            shape: Vec<usize>,
            data: Vec<i64>,
        },
    }

    impl OrtInputTyped {
        pub fn name(&self) -> &str {
            match self {
                Self::F32 { name, .. } | Self::I64 { name, .. } => name,
            }
        }
    }

    /// Run an in-memory ONNX model through ORT with mixed-dtype inputs.
    ///
    /// Returns all outputs that can be extracted as f32 (skips non-f32 outputs).
    pub fn run_onnx_typed(
        model_bytes: &[u8],
        inputs: Vec<OrtInputTyped>,
    ) -> Result<Vec<IntermediateTensor>> {
        run_onnx_typed_impl(None, Some(model_bytes), inputs)
    }

    /// Run a file-based ONNX model through ORT with mixed-dtype inputs.
    ///
    /// Preferred for large models (>100MB) since ORT can load incrementally.
    pub fn run_onnx_file_typed(
        model_path: &std::path::Path,
        inputs: Vec<OrtInputTyped>,
    ) -> Result<Vec<IntermediateTensor>> {
        run_onnx_typed_impl(Some(model_path), None, inputs)
    }

    fn run_onnx_typed_impl(
        model_path: Option<&std::path::Path>,
        model_bytes: Option<&[u8]>,
        inputs: Vec<OrtInputTyped>,
    ) -> Result<Vec<IntermediateTensor>> {
        let mut session = Session::builder().context("failed to create ORT session builder")?;
        let mut session = if let Some(path) = model_path {
            session
                .commit_from_file(path)
                .context("failed to load ONNX model from file into ORT")?
        } else {
            let bytes = model_bytes.expect("either model_path or model_bytes required");
            session
                .commit_from_memory(bytes)
                .context("failed to load ONNX model into ORT")?
        };

        let mut ort_inputs: Vec<(String, ort::value::DynValue)> = Vec::new();
        for inp in &inputs {
            match inp {
                OrtInputTyped::F32 { name, shape, data } => {
                    let shape_i64: Vec<i64> = shape.iter().map(|&d| d as i64).collect();
                    // Zero-element inputs (e.g. first-pass `past.*` KV ports at
                    // sequence length 0) must take the allocator path: ORT's
                    // raw-data constructor rejects any zero-sized dimension.
                    let tensor = if shape.iter().product::<usize>() == 0 {
                        Tensor::<f32>::new(session.allocator(), shape_i64)
                            .context("creating empty f32 ORT input")?
                    } else {
                        Tensor::<f32>::from_array((shape_i64, data.clone()))
                            .context("creating f32 ORT input")?
                    };
                    ort_inputs.push((name.clone(), tensor.into_dyn()));
                }
                OrtInputTyped::I64 { name, shape, data } => {
                    let shape_i64: Vec<i64> = shape.iter().map(|&d| d as i64).collect();
                    let tensor = if shape.iter().product::<usize>() == 0 {
                        Tensor::<i64>::new(session.allocator(), shape_i64)
                            .context("creating empty i64 ORT input")?
                    } else {
                        Tensor::<i64>::from_array((shape_i64, data.clone()))
                            .context("creating i64 ORT input")?
                    };
                    ort_inputs.push((name.clone(), tensor.into_dyn()));
                }
            }
        }

        let outputs = session.run(ort_inputs).context("ORT session run failed")?;

        let mut result = Vec::new();
        for (name, value) in outputs.iter() {
            if let Ok((shape, data)) = value.try_extract_tensor::<f32>() {
                result.push(IntermediateTensor {
                    name: name.to_string(),
                    shape: shape.iter().map(|&d| d as usize).collect(),
                    data: data.to_vec(),
                });
            }
        }
        Ok(result)
    }

    /// Run an in-memory ONNX model (protobuf bytes) through ORT with the given inputs.
    pub fn run_onnx_bytes(model_bytes: &[u8], inputs: Vec<OrtInput>) -> Result<Vec<f32>> {
        let mut session = Session::builder()
            .context("failed to create ORT session builder")?
            .commit_from_memory(model_bytes)
            .context("failed to load ONNX model into ORT")?;

        let tensors: Vec<Tensor<f32>> = inputs
            .iter()
            .map(|inp| {
                let shape: Vec<i64> = inp.shape.iter().map(|&d| d as i64).collect();
                Tensor::<f32>::from_array((shape, inp.data.clone()))
                    .context("creating ORT input tensor")
            })
            .collect::<Result<Vec<_>>>()?;

        let ort_inputs: Vec<(String, ort::value::DynValue)> = inputs
            .iter()
            .zip(tensors)
            .map(|(inp, tensor)| (inp.name.clone(), tensor.into_dyn()))
            .collect();

        let outputs = session.run(ort_inputs).context("ORT session run failed")?;

        let output = outputs.values().next().context("no outputs from ORT")?;

        let (_shape, data) = output
            .try_extract_tensor::<f32>()
            .context("extracting f32 tensor from ORT output")?;

        Ok(data.to_vec())
    }

    /// An intermediate tensor captured from ORT execution.
    pub struct IntermediateTensor {
        pub name: String,
        pub shape: Vec<usize>,
        pub data: Vec<f32>,
    }

    /// Run an ONNX model through ORT, returning ALL named outputs.
    ///
    /// Unlike `run_onnx_bytes()` which returns only the first output's data,
    /// this returns every output tensor with its name and shape. Works best
    /// with models built via `onnx_builder::multi_output_model()` that
    /// already expose intermediate tensors as graph outputs.
    pub fn run_onnx_all_outputs(
        model_bytes: &[u8],
        inputs: Vec<OrtInput>,
    ) -> Result<Vec<IntermediateTensor>> {
        let mut session = Session::builder()
            .context("failed to create ORT session builder")?
            .commit_from_memory(model_bytes)
            .context("failed to load ONNX model into ORT")?;

        let tensors: Vec<Tensor<f32>> = inputs
            .iter()
            .map(|inp| {
                let shape: Vec<i64> = inp.shape.iter().map(|&d| d as i64).collect();
                Tensor::<f32>::from_array((shape, inp.data.clone()))
                    .context("creating ORT input tensor")
            })
            .collect::<Result<Vec<_>>>()?;

        let ort_inputs: Vec<(String, ort::value::DynValue)> = inputs
            .iter()
            .zip(tensors)
            .map(|(inp, tensor)| (inp.name.clone(), tensor.into_dyn()))
            .collect();

        let outputs = session.run(ort_inputs).context("ORT session run failed")?;

        let mut result = Vec::new();
        for (name, value) in outputs.iter() {
            if let Ok((shape, data)) = value.try_extract_tensor::<f32>() {
                result.push(IntermediateTensor {
                    name: name.to_string(),
                    shape: shape.iter().map(|&d| d as usize).collect(),
                    data: data.to_vec(),
                });
            }
        }

        Ok(result)
    }
}

/// Build a minimal single-op ONNX model as raw protobuf bytes.
///
/// This module constructs ONNX protobuf by hand (no dependency on onnx crate)
/// since hologram-ai-onnx's proto module is private.
pub mod onnx_builder {
    /// Build a minimal ONNX model for a unary elementwise op.
    /// Graph: input "X" `[1, size]` -> op -> output "Y" `[1, size]`
    pub fn unary_op(op_type: &str, size: usize) -> Vec<u8> {
        build_model(op_type, &[("X", &[1, size])], &[("Y", &[1, size])], &[])
    }

    /// Build a minimal ONNX model for a binary elementwise op.
    /// Graph: inputs "A" `[1, size]`, "B" `[1, size]` -> op -> output "Y" `[1, size]`
    pub fn binary_op(op_type: &str, size: usize) -> Vec<u8> {
        build_model(
            op_type,
            &[("A", &[1, size]), ("B", &[1, size])],
            &[("Y", &[1, size])],
            &[],
        )
    }

    /// Build a Softmax ONNX model.
    /// Graph: input "X" `[rows, size]` -> Softmax(axis=-1) -> output "Y" `[rows, size]`
    pub fn softmax(rows: usize, size: usize) -> Vec<u8> {
        build_model(
            "Softmax",
            &[("input", &[rows, size])],
            &[("output", &[rows, size])],
            &[("axis", AttrVal::Int(-1))],
        )
    }

    /// Build a MatMul ONNX model.
    /// Graph: inputs "A" `[m, k]`, "B" `[k, n]` -> MatMul -> output "Y" `[m, n]`
    pub fn matmul(m: usize, k: usize, n: usize) -> Vec<u8> {
        build_model(
            "MatMul",
            &[("A", &[m, k]), ("B", &[k, n])],
            &[("Y", &[m, n])],
            &[],
        )
    }

    /// Build a Gemm ONNX model.
    pub fn gemm(
        m: usize,
        k: usize,
        n: usize,
        alpha: f32,
        beta: f32,
        trans_a: bool,
        trans_b: bool,
    ) -> Vec<u8> {
        let a_shape = if trans_a { vec![k, m] } else { vec![m, k] };
        let b_shape = if trans_b { vec![n, k] } else { vec![k, n] };
        build_model(
            "Gemm",
            &[("A", &a_shape), ("B", &b_shape), ("C", &[m, n])],
            &[("Y", &[m, n])],
            &[
                ("alpha", AttrVal::Float(alpha)),
                ("beta", AttrVal::Float(beta)),
                ("transA", AttrVal::Int(trans_a as i64)),
                ("transB", AttrVal::Int(trans_b as i64)),
            ],
        )
    }

    // ── Composite ops (multi-node ONNX graphs) ─────────────────────────────

    /// Build an RmsNorm ONNX model from primitives.
    /// RmsNorm(x, weight, eps) = x / sqrt(mean(x^2) + eps) * weight
    ///
    /// Graph:
    ///   X `[rows, size]`, Weight `[size]` ->
    ///   Pow(X, 2) -> ReduceMean -> Add(eps) -> Sqrt -> Div(X, .) -> Mul(., Weight) -> Y
    pub fn rms_norm(rows: usize, size: usize, epsilon: f32) -> Vec<u8> {
        let nodes = vec![
            Node::new("Pow", &["X", "two"], &["x_sq"]),
            Node::with_attrs(
                "ReduceMean",
                &["x_sq"],
                &["mean_sq"],
                &[
                    ("axes", AttrVal::Ints(vec![-1])),
                    ("keepdims", AttrVal::Int(1)),
                ],
            ),
            Node::new("Add", &["mean_sq", "eps"], &["mean_plus_eps"]),
            Node::new("Sqrt", &["mean_plus_eps"], &["rms"]),
            Node::new("Div", &["X", "rms"], &["normed"]),
            Node::new("Mul", &["normed", "Weight"], &["Y"]),
        ];
        let initializers = vec![
            Initializer::scalar("two", 2.0_f32),
            Initializer::scalar("eps", epsilon),
        ];
        build_multi_node_model(
            &nodes,
            &[("X", &[rows, size]), ("Weight", &[size])],
            &[("Y", &[rows, size])],
            &initializers,
        )
    }

    /// Build a LayerNorm ONNX model from primitives.
    /// LayerNorm(x, weight, bias, eps) = (x - mean(x)) / sqrt(var(x) + eps) * weight + bias
    pub fn layer_norm(rows: usize, size: usize, epsilon: f32) -> Vec<u8> {
        let nodes = vec![
            Node::with_attrs(
                "ReduceMean",
                &["X"],
                &["mean"],
                &[
                    ("axes", AttrVal::Ints(vec![-1])),
                    ("keepdims", AttrVal::Int(1)),
                ],
            ),
            Node::new("Sub", &["X", "mean"], &["x_centered"]),
            Node::new("Pow", &["x_centered", "two"], &["x_sq"]),
            Node::with_attrs(
                "ReduceMean",
                &["x_sq"],
                &["var"],
                &[
                    ("axes", AttrVal::Ints(vec![-1])),
                    ("keepdims", AttrVal::Int(1)),
                ],
            ),
            Node::new("Add", &["var", "eps"], &["var_eps"]),
            Node::new("Sqrt", &["var_eps"], &["std"]),
            Node::new("Div", &["x_centered", "std"], &["normed"]),
            Node::new("Mul", &["normed", "Weight"], &["scaled"]),
            Node::new("Add", &["scaled", "Bias"], &["Y"]),
        ];
        let initializers = vec![
            Initializer::scalar("two", 2.0_f32),
            Initializer::scalar("eps", epsilon),
        ];
        build_multi_node_model(
            &nodes,
            &[("X", &[rows, size]), ("Weight", &[size]), ("Bias", &[size])],
            &[("Y", &[rows, size])],
            &initializers,
        )
    }

    /// Build a multi-node ONNX model where ALL intermediate tensors are
    /// exposed as graph outputs, enabling node-by-node comparison with ORT.
    ///
    /// `nodes` defines the graph topology. All node outputs (intermediate
    /// and final) appear in the graph's output list. Graph inputs and
    /// initializers are passed separately.
    pub fn multi_output_model(
        nodes: &[Node],
        inputs: &[(&str, &[usize])],
        initializers: &[Initializer],
    ) -> Vec<u8> {
        // All node outputs become graph outputs.
        let all_outputs: Vec<(&str, &[usize])> = nodes
            .iter()
            .flat_map(|n| n.outputs.iter().map(|&name| (name, &[][..])))
            .collect();

        build_multi_node_model(nodes, inputs, &all_outputs, initializers)
    }

    /// Build a 4D batched MatMul ONNX model.
    /// A `[batch, heads, m, k]` × B `[batch, heads, k, n]` → Y `[batch, heads, m, n]`
    /// Models the Q@K^T and scores@V patterns in multi-head attention.
    pub fn batched_matmul_4d(batch: usize, heads: usize, m: usize, k: usize, n: usize) -> Vec<u8> {
        build_model(
            "MatMul",
            &[("A", &[batch, heads, m, k]), ("B", &[batch, heads, k, n])],
            &[("Y", &[batch, heads, m, n])],
            &[],
        )
    }

    /// Build a Concat ONNX model that concatenates two 4D tensors along axis 3 (last axis).
    /// A `[batch, heads, seq, dim_a]` ++ B `[batch, heads, seq, dim_b]` → Y `[batch, heads, seq, dim_a+dim_b]`
    /// Models the concat-of-halves pattern in RoPE's rotate_half function.
    pub fn concat_4d_last_axis(
        batch: usize,
        heads: usize,
        seq: usize,
        dim_a: usize,
        dim_b: usize,
    ) -> Vec<u8> {
        let nodes = vec![Node::with_attrs(
            "Concat",
            &["A", "B"],
            &["Y"],
            &[("axis", AttrVal::Int(3))],
        )];
        build_multi_node_model(
            &nodes,
            &[
                ("A", &[batch, heads, seq, dim_a]),
                ("B", &[batch, heads, seq, dim_b]),
            ],
            &[("Y", &[batch, heads, seq, dim_a + dim_b])],
            &[],
        )
    }

    /// Build a Scaled Dot-Product Attention ONNX model.
    /// Q, K, V: `[batch, heads, seq, head_dim]`
    /// Steps: K_T = Transpose(K, perm=`[0,1,3,2]`)
    ///        QK  = Q @ K_T / sqrt(head_dim)
    ///        out = Softmax(QK) @ V
    /// Output: `[batch, heads, seq, head_dim]`
    pub fn scaled_dot_product_attention(
        batch: usize,
        heads: usize,
        seq: usize,
        head_dim: usize,
    ) -> Vec<u8> {
        let scale = 1.0_f32 / (head_dim as f32).sqrt();
        let nodes = vec![
            Node::with_attrs(
                "Transpose",
                &["K"],
                &["K_T"],
                &[("perm", AttrVal::Ints(vec![0, 1, 3, 2]))],
            ),
            Node::new("MatMul", &["Q", "K_T"], &["QK"]),
            Node::new("Mul", &["QK", "scale"], &["QK_scaled"]),
            Node::with_attrs(
                "Softmax",
                &["QK_scaled"],
                &["QK_soft"],
                &[("axis", AttrVal::Int(-1))],
            ),
            Node::new("MatMul", &["QK_soft", "V"], &["AttnOut"]),
        ];
        let initializers = vec![Initializer::scalar("scale", scale)];
        build_multi_node_model(
            &nodes,
            &[
                ("Q", &[batch, heads, seq, head_dim]),
                ("K", &[batch, heads, seq, head_dim]),
                ("V", &[batch, heads, seq, head_dim]),
            ],
            &[("AttnOut", &[batch, heads, seq, head_dim])],
            &initializers,
        )
    }

    /// Build a GQA (Grouped Query Attention) ONNX model.
    ///
    /// Models TinyLlama's GQA expansion pattern where K and V are projected to
    /// n_kv_heads, then repeated to n_heads via Unsqueeze → Expand → Reshape:
    ///
    ///   K_compact `[batch, n_kv_heads, seq, head_dim]`
    ///     → Unsqueeze(axis=2)  → `[batch, n_kv_heads, 1, seq, head_dim]`
    ///     → Expand             → `[batch, n_kv_heads, group_size, seq, head_dim]`
    ///     → Reshape            → `[batch, n_heads, seq, head_dim]`
    ///
    ///   AttnOut = softmax(Q @ K_T / sqrt(head_dim)) @ V_expanded
    ///
    /// This is the canonical ONNX representation of GQA. The ONNX Expand op
    /// requires dim=1 in the input for broadcasting; the Unsqueeze adds that
    /// dimension so the group axis can be broadcast to group_size.
    ///
    /// group_size = n_heads / n_kv_heads (must divide evenly).
    /// A failure here exposes incorrect Expand or Reshape handling for 5D tensors,
    /// which causes the downstream attention output to have wrong element counts.
    pub fn gqa_expand_attention(
        batch: usize,
        n_heads: usize,
        n_kv_heads: usize,
        seq: usize,
        head_dim: usize,
    ) -> Vec<u8> {
        let group_size = n_heads / n_kv_heads;
        let scale = 1.0_f32 / (head_dim as f32).sqrt();
        // Target shape for Expand: [batch, n_kv_heads, group_size, seq, head_dim]
        let expand_shape_k: Vec<i64> = vec![
            batch as i64,
            n_kv_heads as i64,
            group_size as i64,
            seq as i64,
            head_dim as i64,
        ];
        let expand_shape_v = expand_shape_k.clone();

        let nodes = vec![
            // K: [batch, n_kv, seq, hdim] → [batch, n_kv, 1, seq, hdim]
            // Opset 13: axes is a second input tensor, not an attribute.
            Node::new("Unsqueeze", &["K_compact", "unsq_axes"], &["K_unsq"]),
            // K: [batch, n_kv, 1, seq, hdim] → [batch, n_kv, group, seq, hdim]
            Node::new("Expand", &["K_unsq", "expand_shape_k"], &["K_5d"]),
            // K: [batch, n_kv, group, seq, hdim] → [batch, n_heads, seq, hdim]
            Node::new("Reshape", &["K_5d", "attn_shape"], &["K_exp"]),
            // V: same pattern
            Node::new("Unsqueeze", &["V_compact", "unsq_axes"], &["V_unsq"]),
            Node::new("Expand", &["V_unsq", "expand_shape_v"], &["V_5d"]),
            Node::new("Reshape", &["V_5d", "attn_shape"], &["V_exp"]),
            // Attention: Q @ K_T / scale → softmax → @ V
            Node::with_attrs(
                "Transpose",
                &["K_exp"],
                &["K_T"],
                &[("perm", AttrVal::Ints(vec![0, 1, 3, 2]))],
            ),
            Node::new("MatMul", &["Q", "K_T"], &["QK"]),
            Node::new("Mul", &["QK", "scale"], &["QK_scaled"]),
            Node::with_attrs(
                "Softmax",
                &["QK_scaled"],
                &["QK_soft"],
                &[("axis", AttrVal::Int(-1))],
            ),
            Node::new("MatMul", &["QK_soft", "V_exp"], &["AttnOut"]),
        ];
        let attn_shape: Vec<i64> = vec![batch as i64, n_heads as i64, seq as i64, head_dim as i64];
        let initializers = vec![
            Initializer::int64_1d("unsq_axes", vec![2]),
            Initializer::int64_1d("expand_shape_k", expand_shape_k),
            Initializer::int64_1d("expand_shape_v", expand_shape_v),
            Initializer::int64_1d("attn_shape", attn_shape),
            Initializer::scalar("scale", scale),
        ];

        build_multi_node_model(
            &nodes,
            &[
                ("Q", &[batch, n_heads, seq, head_dim]),
                ("K_compact", &[batch, n_kv_heads, seq, head_dim]),
                ("V_compact", &[batch, n_kv_heads, seq, head_dim]),
            ],
            &[("AttnOut", &[batch, n_heads, seq, head_dim])],
            &initializers,
        )
    }

    /// Build a model that tests `Shape` with `start`/`end` attributes (opset 15).
    ///
    /// Graph:
    ///   K `[batch, n_kv, seq, head_dim]`
    ///   Shape(K, start=0, end=1) → batch_dim INT64`[1]`     — first dim only
    ///   Shape(K, start=2, end=4) → seq_hdim INT64`[2]`      — last two dims only
    ///   Cast(batch_dim, to=FLOAT) → batch_f32 `[1]`
    ///   Cast(seq_hdim,  to=FLOAT) → seqhdim_f32 `[2]`
    ///   Concat(`[batch_f32, seqhdim_f32]`, axis=0) → Y `[3]`  — `[batch, seq, head_dim]`
    ///
    /// Expected: Y = `[batch as f32, seq as f32, head_dim as f32]`.
    ///
    /// A failure means `Shape` ignores `start`/`end` and returns all dims instead
    /// of the requested slice, yielding `[batch, n_kv, seq, head_dim, ...]` instead.
    /// This is the root cause regression test for the TinyLlama `A=[40,4096]` bug:
    /// TinyLlama uses `Shape(input_ids, start=0, end=1)` and
    /// `Shape(attention_mask, start=1, end=2)` in its GQA shape computation chain.
    pub fn shape_with_start_end_attrs(
        batch: usize,
        n_kv_heads: usize,
        seq: usize,
        head_dim: usize,
    ) -> Vec<u8> {
        let nodes = vec![
            // Extract only dim 0 (batch).
            Node::with_attrs(
                "Shape",
                &["K"],
                &["batch_dim"],
                &[("start", AttrVal::Int(0)), ("end", AttrVal::Int(1))],
            ),
            // Extract dims 2..4 (seq, head_dim).
            Node::with_attrs(
                "Shape",
                &["K"],
                &["seq_hdim"],
                &[("start", AttrVal::Int(2)), ("end", AttrVal::Int(4))],
            ),
            // Cast to float so we can compare numerically.
            Node::with_attrs(
                "Cast",
                &["batch_dim"],
                &["batch_f"],
                &[("to", AttrVal::Int(1))],
            ),
            Node::with_attrs(
                "Cast",
                &["seq_hdim"],
                &["seqhd_f"],
                &[("to", AttrVal::Int(1))],
            ),
            // Concat: [batch] ++ [seq, head_dim] → [batch, seq, head_dim]
            Node::with_attrs(
                "Concat",
                &["batch_f", "seqhd_f"],
                &["Y"],
                &[("axis", AttrVal::Int(0))],
            ),
        ];
        build_multi_node_model(
            &nodes,
            &[("K", &[batch, n_kv_heads, seq, head_dim])],
            &[("Y", &[3])],
            &[],
        )
    }

    /// Build a GQA K-expand model that uses `Shape` with `start`/`end` attributes
    /// to extract dimensions, matching TinyLlama's exact graph pattern:
    ///
    ///   batch_dim = Shape(input_like, start=0, end=1)  → INT64`[1]` = `[batch]`
    ///   seq_hdim  = Shape(K_compact,  start=2, end=4)  → INT64`[2]` = `[seq, head_dim]`
    ///   expand_shape = Concat(`[batch_dim, nkv_c, group_c, seq_hdim]`)
    ///   K_exp = Reshape(Expand(Unsqueeze(K_compact), expand_shape), reshape_tgt)
    ///
    /// Exposes the bug where `start`/`end` are stripped from `FloatOp::Shape`,
    /// causing `batch_dim` to return `[batch, n_kv_heads, seq, head_dim]`
    /// (all 4 dims) instead of just `[batch]`. This corrupts the Concat-built
    /// expand shape, producing wrong K/V element counts downstream.
    pub fn gqa_k_expand_with_shape_start_end(
        batch: usize,
        n_heads: usize,
        n_kv_heads: usize,
        seq: usize,
        head_dim: usize,
    ) -> Vec<u8> {
        let group_size = n_heads / n_kv_heads;
        let nodes = vec![
            // Use Shape with start/end to extract only dim 0 (batch).
            Node::with_attrs(
                "Shape",
                &["K_compact"],
                &["batch_dim"],
                &[("start", AttrVal::Int(0)), ("end", AttrVal::Int(1))],
            ),
            // Use Shape with start/end to extract dims 2..4 (seq, head_dim).
            Node::with_attrs(
                "Shape",
                &["K_compact"],
                &["seq_hdim"],
                &[("start", AttrVal::Int(2)), ("end", AttrVal::Int(4))],
            ),
            // Build expand shape [batch, n_kv, group, seq, head_dim]
            Node::with_attrs(
                "Concat",
                &["batch_dim", "nkv_c", "group_c", "seq_hdim"],
                &["expand_shape"],
                &[("axis", AttrVal::Int(0))],
            ),
            // Unsqueeze K to [batch, n_kv, 1, seq, hdim] (opset 13 axes-as-tensor).
            Node::new("Unsqueeze", &["K_compact", "unsq_ax2"], &["K_unsq"]),
            // Expand to [batch, n_kv, group, seq, hdim].
            Node::new("Expand", &["K_unsq", "expand_shape"], &["K_5d"]),
            // Build reshape target [batch, n_heads, seq, head_dim].
            Node::with_attrs(
                "Concat",
                &["batch_dim", "nheads_c", "seq_hdim"],
                &["reshape_tgt"],
                &[("axis", AttrVal::Int(0))],
            ),
            // Reshape to [batch, n_heads, seq, head_dim].
            Node::new("Reshape", &["K_5d", "reshape_tgt"], &["K_exp"]),
        ];
        let initializers = vec![
            Initializer::int64_1d("nkv_c", vec![n_kv_heads as i64]),
            Initializer::int64_1d("group_c", vec![group_size as i64]),
            Initializer::int64_1d("nheads_c", vec![n_heads as i64]),
            Initializer::int64_1d("unsq_ax2", vec![2]),
        ];
        build_multi_node_model(
            &nodes,
            &[("K_compact", &[batch, n_kv_heads, seq, head_dim])],
            &[("K_exp", &[batch, n_heads, seq, head_dim])],
            &initializers,
        )
    }

    /// Build a Shape(start,end) model with a **dynamic** `seq` dimension.
    ///
    /// This forces the `FloatOp::Shape` node to survive DataPropagation (which
    /// can only fold Shape ops whose input has fully-concrete dims) and execute
    /// at runtime. A buggy executor that ignores `start`/`end` will return all 4
    /// dims instead of the expected 2, causing the Cast output to be length 4
    /// instead of 2 — which the test detects as a value or shape mismatch vs ORT.
    ///
    /// Graph:
    ///   K `[batch, n_kv_heads, seq_DYN, head_dim]`  ← seq is symbolic ("dyn")
    ///   Shape(K, start=2, end=4) → seq_hdim INT64`[2]`
    ///   Cast(to=FLOAT) → Y f32`[2]`
    ///
    /// Expected: Y = `[seq as f32, head_dim as f32]`
    /// Buggy result (FloatOp::Shape ignores start/end): Y = `[batch, n_kv_heads, seq, head_dim]`
    pub fn shape_start_end_with_dynamic_seq(
        batch: usize,
        n_kv_heads: usize,
        seq: usize,
        head_dim: usize,
    ) -> Vec<u8> {
        let nodes = vec![
            Node::with_attrs(
                "Shape",
                &["K"],
                &["seq_hdim"],
                &[("start", AttrVal::Int(2)), ("end", AttrVal::Int(4))],
            ),
            Node::with_attrs("Cast", &["seq_hdim"], &["Y"], &[("to", AttrVal::Int(1))]),
        ];
        // Build the model manually so we can use `encode_value_info_dyn`
        // to declare `seq` as a dynamic (symbolic) dimension.
        let mut buf = Vec::new();
        let graph_input =
            encode_value_info_dyn("K", &[Some(batch), Some(n_kv_heads), None, Some(head_dim)]);
        let graph_output = encode_value_info("Y", &[2]);

        let mut graph = Vec::new();
        for node in &nodes {
            let encoded = encode_node_struct(node);
            write_field(&mut graph, 1, &encoded);
        }
        write_string(&mut graph, 2, "test_graph");
        write_field(&mut graph, 11, &graph_input);
        write_field(&mut graph, 12, &graph_output);

        write_varint_field(&mut buf, 1, 8); // ir_version = 8
        write_field(&mut buf, 7, &graph);
        let opset = encode_opset(17);
        write_field(&mut buf, 8, &opset);
        let _ = seq; // used only for test invocation, not in ONNX model type
        buf
    }

    /// Build a model that tests the `Shape` op via `Cast` to float.
    ///
    /// Graph: X `[batch, seq, hidden]` → Shape → shape_int64 `[3]` → Cast(to=FLOAT) → Y `[3]`
    ///
    /// ORT should return `[batch as f32, seq as f32, hidden as f32]`.
    /// A failure here means `Shape` returns wrong dimension values (e.g. a scalar
    /// element count instead of per-axis dims), which breaks the
    /// Shape → Slice → Concat → Expand chains in GQA models like TinyLlama.
    pub fn shape_then_cast_to_float(batch: usize, seq: usize, hidden: usize) -> Vec<u8> {
        let nodes = vec![
            Node::new("Shape", &["X"], &["X_shape"]),
            Node::with_attrs("Cast", &["X_shape"], &["Y"], &[("to", AttrVal::Int(1))]),
        ];
        build_multi_node_model(&nodes, &[("X", &[batch, seq, hidden])], &[("Y", &[3])], &[])
    }

    /// Build a model where a Reshape target is computed at runtime via
    /// Shape → Slice → Concat, matching TinyLlama's dynamic shape pattern.
    ///
    /// Graph:
    ///   X `[batch, seq, hidden]`
    ///   → Shape(X)                     → shape `[3]` (INT64)
    ///   → Slice(shape, 0:2)            → first_two `[2]` (INT64 = `[batch, seq]`)
    ///   → Concat(`[first_two, hdim_c]`)  → reshape_tgt `[3]` (INT64 = `[batch, seq, hidden]`)
    ///   → Expand(X, reshape_tgt)       → Y `[batch, seq, hidden]`
    ///
    /// This validates that dynamically computed shape tensors (from Shape op output)
    /// propagate correctly through Slice and Concat and produce the right values in
    /// Expand. A bug in `dispatch_shape` that returns a scalar element count instead
    /// of per-axis dims will cause Slice to produce wrong values and Expand to fail
    /// or produce an incorrectly-sized output.
    pub fn expand_via_dynamic_shape(batch: usize, seq: usize, hidden: usize) -> Vec<u8> {
        let nodes = vec![
            Node::new("Shape", &["X"], &["x_shape"]),
            // Slice the first 2 dims: [batch, seq]
            Node::new(
                "Slice",
                &["x_shape", "slice_s02", "slice_e02", "slice_ax0"],
                &["first_two"],
            ),
            // Concat first two dims + constant hidden → full shape
            Node::with_attrs(
                "Concat",
                &["first_two", "hidden_c"],
                &["reshape_tgt"],
                &[("axis", AttrVal::Int(0))],
            ),
            // Expand X to itself (should be no-op, but exercises the shape chain)
            Node::new("Expand", &["X", "reshape_tgt"], &["Y"]),
        ];
        let initializers = vec![
            Initializer::int64_1d("slice_s02", vec![0]),
            Initializer::int64_1d("slice_e02", vec![2]),
            Initializer::int64_1d("slice_ax0", vec![0]),
            Initializer::int64_1d("hidden_c", vec![hidden as i64]),
        ];
        build_multi_node_model(
            &nodes,
            &[("X", &[batch, seq, hidden])],
            &[("Y", &[batch, seq, hidden])],
            &initializers,
        )
    }

    /// Build a GQA K-expand model where the Expand and Reshape targets are
    /// computed at runtime via Shape → Slice → Concat, matching TinyLlama's
    /// exact dynamic-shape pattern.
    ///
    /// Unlike `gqa_expand_attention` (which uses constant INT64 initializers
    /// for the expand target), this model builds the expand shape at runtime:
    ///
    ///   K_compact `[batch, n_kv_heads, seq, head_dim]`
    ///   Shape(K_compact) → k_shape INT64 `[4]`
    ///   Slice(k_shape, 2:4) → seq_hdim INT64 `[2]` = `[seq, head_dim]`
    ///   Concat(`[batch_c, nkv_c, group_c, seq_hdim]`) → expand_shape INT64 `[5]`
    ///   Unsqueeze(K_compact, `[2]`) → K_unsq `[batch, n_kv, 1, seq, head_dim]`
    ///   Expand(K_unsq, expand_shape) → K_5d `[batch, n_kv, group, seq, head_dim]`
    ///   Concat(`[batch_c, nheads_c, seq_hdim]`) → reshape_tgt INT64 `[4]`
    ///   Reshape(K_5d, reshape_tgt) → K_exp `[batch, n_heads, seq, head_dim]`
    ///
    /// A failure exposes bugs where `Shape(K_compact)` returns wrong values
    /// (e.g. a scalar element count), causing Slice to produce garbage and
    /// Expand to produce wrong element count — the root cause of the
    /// TinyLlama `A=[40,4096]` shape mismatch at NodeId(336).
    pub fn gqa_k_expand_with_dynamic_shape(
        batch: usize,
        n_heads: usize,
        n_kv_heads: usize,
        seq: usize,
        head_dim: usize,
    ) -> Vec<u8> {
        let group_size = n_heads / n_kv_heads;
        let nodes = vec![
            // Extract [seq, head_dim] from K_compact's runtime shape.
            Node::new("Shape", &["K_compact"], &["k_shape"]),
            Node::new(
                "Slice",
                &["k_shape", "slice_s24", "slice_e24", "slice_ax0"],
                &["seq_hdim"],
            ),
            // Unsqueeze K to [batch, n_kv, 1, seq, hdim] (opset 13 axes-as-tensor).
            Node::new("Unsqueeze", &["K_compact", "unsq_ax2"], &["K_unsq"]),
            // Build expand shape [batch, n_kv, group, seq, hdim] from runtime + constants.
            Node::with_attrs(
                "Concat",
                &["batch_c", "nkv_c", "group_c", "seq_hdim"],
                &["expand_shape"],
                &[("axis", AttrVal::Int(0))],
            ),
            // Expand: [batch, n_kv, 1, seq, hdim] → [batch, n_kv, group, seq, hdim]
            Node::new("Expand", &["K_unsq", "expand_shape"], &["K_5d"]),
            // Build reshape shape [batch, n_heads, seq, hdim] from runtime + constants.
            Node::with_attrs(
                "Concat",
                &["batch_c", "nheads_c", "seq_hdim"],
                &["reshape_tgt"],
                &[("axis", AttrVal::Int(0))],
            ),
            // Reshape: [batch, n_kv, group, seq, hdim] → [batch, n_heads, seq, hdim]
            Node::new("Reshape", &["K_5d", "reshape_tgt"], &["K_exp"]),
        ];
        let initializers = vec![
            Initializer::int64_1d("slice_s24", vec![2]),
            Initializer::int64_1d("slice_e24", vec![4]),
            Initializer::int64_1d("slice_ax0", vec![0]),
            Initializer::int64_1d("unsq_ax2", vec![2]),
            Initializer::int64_1d("batch_c", vec![batch as i64]),
            Initializer::int64_1d("nkv_c", vec![n_kv_heads as i64]),
            Initializer::int64_1d("group_c", vec![group_size as i64]),
            Initializer::int64_1d("nheads_c", vec![n_heads as i64]),
        ];
        build_multi_node_model(
            &nodes,
            &[("K_compact", &[batch, n_kv_heads, seq, head_dim])],
            &[("K_exp", &[batch, n_heads, seq, head_dim])],
            &initializers,
        )
    }

    /// Build an ONNX model that exercises Range with i64 scalar inputs.
    ///
    /// Graph: Range(i64_zero, i64_n, i64_one) → positions `[n]` → Cast(to=FLOAT) → output `[n]`
    ///
    /// This tests the case where the Range `limit` input is an 8-byte i64 scalar
    /// (as emitted by the Shape op in model_causal.onnx).  Before the fix, hologram
    /// would call cast_f32() on the i64 bytes, interpreting them as subnormals ≈0,
    /// producing a 1-element output instead of `[0.0, 1.0, ..., n-1.0]`.
    ///
    /// ORT: Range(i64) → i64 `[n]`, Cast → f32 `[0.0..n-1.0]`
    /// hologram (fixed): Range reads i64 inputs correctly → f32 `[0.0..n-1.0]`, Cast = no-op
    pub fn range_i64_then_cast(n: usize) -> Vec<u8> {
        let nodes = vec![
            Node::new("Range", &["start", "limit", "delta"], &["positions"]),
            Node::with_attrs(
                "Cast",
                &["positions"],
                &["output"],
                &[("to", AttrVal::Int(1))], // to=FLOAT (1)
            ),
        ];
        let initializers = vec![
            Initializer::int64_scalar("start", 0),
            Initializer::int64_scalar("limit", n as i64),
            Initializer::int64_scalar("delta", 1),
        ];
        build_multi_node_model(&nodes, &[], &[("output", &[n])], &initializers)
    }

    /// Build an ONNX model that computes `LessOrEqual(row, col)` → Cast to float.
    ///
    /// `row` has shape `[seq, 1]` and `col` has shape `[1, seq]`, both holding
    /// `[0.0, 1.0, …, seq-1.0]`.  The orthogonal broadcast produces `[seq, seq]`
    /// where `entry[i,j] = if i <= j { 1.0 } else { 0.0 }` (upper-triangular mask).
    ///
    /// This exercises the case where `out_len = seq² > seq = max(a.len(), b.len())`.
    /// The stale-shape guard in `binary_compare_broadcast` incorrectly treats this
    /// as inflation and falls back to element cycling, producing a `[seq]` all-1.0
    /// tensor instead of the correct `[seq, seq]` matrix.
    ///
    /// This is the exact pattern used by `model_causal.onnx` to build the causal
    /// attention mask:
    ///   query_pos = Unsqueeze(arange, axis=1) → `[seq, 1]`
    ///   key_pos   = Unsqueeze(arange, axis=0) → `[1, seq]`
    ///   mask      = LessOrEqual(query_pos, key_pos) → `[seq, seq]`
    ///
    /// Inputs: none (constants baked in as initializers).
    /// Output: float `[seq, seq]` — upper-triangular 0/1 mask.
    pub fn causal_mask_less_equal(seq: usize) -> Vec<u8> {
        let row_data: Vec<f32> = (0..seq).map(|i| i as f32).collect(); // [seq, 1]
        let col_data: Vec<f32> = (0..seq).map(|i| i as f32).collect(); // [1, seq]
        let nodes = vec![
            Node::new("LessOrEqual", &["row", "col"], &["mask_bool"]),
            Node::with_attrs(
                "Cast",
                &["mask_bool"],
                &["output"],
                &[("to", AttrVal::Int(1))], // to=FLOAT (1)
            ),
        ];
        let initializers = vec![
            Initializer {
                name: "row",
                data: InitData::Float(row_data),
                shape: vec![seq, 1],
            },
            Initializer {
                name: "col",
                data: InitData::Float(col_data),
                shape: vec![1, seq],
            },
        ];
        build_multi_node_model(&nodes, &[], &[("output", &[seq, seq])], &initializers)
    }

    /// Build an ONNX model that computes SwiGLU: `silu(gate) * up`.
    ///
    /// The equivalent ONNX graph is:
    ///   gate → Sigmoid → sig_gate
    ///   Mul(gate, sig_gate) → silu_gate      (= silu(gate) = gate * sigmoid(gate))
    ///   Mul(silu_gate, up)  → output
    ///
    /// This is the SwiGLU FFN activation used in TinyLlama/LLaMA GGUF models.
    /// hologram compiles this as the fused `FloatOp::FusedSwiGLU` kernel.
    /// A mismatch here indicates either the ONNX lowering or the fused kernel is wrong.
    ///
    /// Inputs: gate `[rows, cols]`, up `[rows, cols]`
    /// Output: `[rows, cols]`
    pub fn swiglu(rows: usize, cols: usize) -> Vec<u8> {
        let nodes = vec![
            // sig_gate = Sigmoid(gate)
            Node::new("Sigmoid", &["gate"], &["sig_gate"]),
            // silu_gate = gate * sig_gate  (= silu(gate))
            Node::new("Mul", &["gate", "sig_gate"], &["silu_gate"]),
            // output = silu_gate * up
            Node::new("Mul", &["silu_gate", "up"], &["output"]),
        ];
        build_multi_node_model(
            &nodes,
            &[("gate", &[rows, cols]), ("up", &[rows, cols])],
            &[("output", &[rows, cols])],
            &[],
        )
    }

    /// Build an ONNX model for GQA with flat inputs (GGUF/LLaMA format) and causal mask.
    ///
    /// Inputs arrive as flat `[seq, n_heads * head_dim]` rather than pre-split
    /// `[batch, n_heads, seq, head_dim]`. This matches what the hologram GGUF
    /// import produces: Q/K/V outputs of `Gemm(hidden, W)` → flat.
    ///
    /// The reference ONNX graph:
    ///   Q flat `[seq, n_q*head_dim]`  → Reshape `[seq, n_q, head_dim]` → Transpose `[n_q, seq, head_dim]`
    ///   K flat `[seq, n_kv*head_dim]` → Reshape `[seq, n_kv, head_dim]` → Transpose `[n_kv, seq, head_dim]`
    ///   V flat `[seq, n_kv*head_dim]` → Reshape → Transpose
    ///   For each query-head group (group_size = n_q / n_kv):
    ///     Gather Q-slice, Gather KV slice, SDPA + causal mask
    ///   Concat → Transpose → Reshape → output `[seq, n_q*head_dim]`
    ///
    /// Because the full gather+loop cannot be expressed in a single ONNX graph
    /// for variable n_q, this builder targets the common single-KV-head case
    /// (n_kv_heads=1, n_q_heads=n_heads) to keep the ONNX simple. For the
    /// general GQA case the ONNX `gqa_expand_attention` builder handles it with
    /// compact-input format. This test validates the flat input path specifically.
    ///
    /// For n_kv_heads=1 (all queries share a single KV head):
    ///   K is repeated to `[n_heads, seq, head_dim]` via Expand after Transpose.
    ///
    /// Inputs: Q `[seq, n_q*head_dim]`, K `[seq, head_dim]`, V `[seq, head_dim]`
    /// Output: `[seq, n_q*head_dim]`
    pub fn gqa_flat_single_kv(n_q_heads: usize, seq: usize, head_dim: usize) -> Vec<u8> {
        let scale = 1.0_f32 / (head_dim as f32).sqrt();
        // K/V come as [seq, head_dim] (single KV head, flat) — same as Q per head.
        // Q comes as [seq, n_q*head_dim] — all Q heads concatenated.
        //
        // Step 1: Reshape Q → [seq, n_q, head_dim], Transpose → [n_q, seq, head_dim]
        // Step 2: Reshape K → [1, seq, head_dim], Expand → [n_q, seq, head_dim]
        // Step 3: QK^T → scale → + causal_mask → Softmax → V → Transpose → Reshape
        let q_shape: Vec<i64> = vec![seq as i64, n_q_heads as i64, head_dim as i64];
        let q_t_shape: Vec<i64> = vec![n_q_heads as i64, seq as i64, head_dim as i64];
        let k_shape_1: Vec<i64> = vec![1, seq as i64, head_dim as i64];
        let out_flat_shape: Vec<i64> = vec![seq as i64, (n_q_heads * head_dim) as i64];

        // Build lower-triangular causal mask for [seq, seq]: 0 on/below diagonal, -inf above.
        let causal_data: Vec<f32> = (0..seq)
            .flat_map(|i| (0..seq).map(move |j| if j > i { f32::NEG_INFINITY } else { 0.0_f32 }))
            .collect();

        let nodes = vec![
            // Q: [seq, n_q*head_dim] → [seq, n_q, head_dim] → [n_q, seq, head_dim]
            Node::new("Reshape", &["Q_flat", "q_shape"], &["Q_3d"]),
            Node::with_attrs(
                "Transpose",
                &["Q_3d"],
                &["Q_t"],
                &[("perm", AttrVal::Ints(vec![1, 0, 2]))],
            ),
            // K: [seq, head_dim] → [1, seq, head_dim] → [n_q, seq, head_dim]
            Node::new("Reshape", &["K_flat", "k_shape_1"], &["K_1sq"]),
            Node::new("Expand", &["K_1sq", "q_t_shape"], &["K_exp"]),
            // K^T for QK matmul: [n_q, seq, head_dim] → [n_q, head_dim, seq]
            Node::with_attrs(
                "Transpose",
                &["K_exp"],
                &["K_T"],
                &[("perm", AttrVal::Ints(vec![0, 2, 1]))],
            ),
            // V: [seq, head_dim] → [1, seq, head_dim] → [n_q, seq, head_dim]
            Node::new("Reshape", &["V_flat", "k_shape_1_v"], &["V_1sq"]),
            Node::new("Expand", &["V_1sq", "q_t_shape_v"], &["V_exp"]),
            // QK^T: [n_q, seq, seq]
            Node::new("MatMul", &["Q_t", "K_T"], &["QK"]),
            // Scale
            Node::new("Mul", &["QK", "scale"], &["QK_s"]),
            // Causal mask: add lower-triangular 0/-inf mask
            Node::new("Add", &["QK_s", "causal_mask"], &["QK_masked"]),
            // Softmax over last axis
            Node::with_attrs(
                "Softmax",
                &["QK_masked"],
                &["scores"],
                &[("axis", AttrVal::Int(-1))],
            ),
            // scores @ V: [n_q, seq, seq] × [n_q, seq, head_dim] → [n_q, seq, head_dim]
            Node::new("MatMul", &["scores", "V_exp"], &["AttnOut_t"]),
            // Transpose back: [n_q, seq, head_dim] → [seq, n_q, head_dim]
            Node::with_attrs(
                "Transpose",
                &["AttnOut_t"],
                &["AttnOut_3d"],
                &[("perm", AttrVal::Ints(vec![1, 0, 2]))],
            ),
            // Reshape → [seq, n_q*head_dim]
            Node::new("Reshape", &["AttnOut_3d", "out_flat_shape"], &["output"]),
        ];

        let initializers = vec![
            Initializer::int64_1d("q_shape", q_shape),
            Initializer::int64_1d("q_t_shape", q_t_shape.clone()),
            Initializer::int64_1d("q_t_shape_v", q_t_shape),
            Initializer::int64_1d("k_shape_1", k_shape_1.clone()),
            Initializer::int64_1d("k_shape_1_v", k_shape_1),
            Initializer::int64_1d("out_flat_shape", out_flat_shape),
            Initializer::scalar("scale", scale),
            Initializer {
                name: "causal_mask",
                data: InitData::Float(causal_data),
                shape: vec![seq, seq],
            },
        ];

        build_multi_node_model(
            &nodes,
            &[
                ("Q_flat", &[seq, n_q_heads * head_dim]),
                ("K_flat", &[seq, head_dim]),
                ("V_flat", &[seq, head_dim]),
            ],
            &[("output", &[seq, n_q_heads * head_dim])],
            &initializers,
        )
    }

    /// Build an ONNX model for GQA with flat inputs and multiple KV heads.
    ///
    /// Generalizes `gqa_flat_single_kv` to arbitrary `n_kv_heads > 1`.
    /// This matches the input format produced by GGUF import:
    ///   Q `[seq, n_q_heads * head_dim]`, K `[seq, n_kv_heads * head_dim]`, V `[seq, n_kv_heads * head_dim]`
    ///
    /// The reference computation:
    ///   1. Reshape Q → `[n_q_heads, seq, head_dim]`
    ///   2. Reshape K → `[n_kv_heads, seq, head_dim]`, Expand to `[n_q_heads, seq, head_dim]`
    ///   3. Reshape V → `[n_kv_heads, seq, head_dim]`, Expand to `[n_q_heads, seq, head_dim]`
    ///   4. QK^T → scale → causal_mask → Softmax → @V
    ///   5. Reshape output → `[seq, n_q_heads * head_dim]`
    ///
    /// group_size = n_q_heads / n_kv_heads (must divide evenly).
    /// K/V are repeated group_size times along the heads axis via Unsqueeze+Expand+Reshape.
    pub fn gqa_flat_multi_kv(
        n_q_heads: usize,
        n_kv_heads: usize,
        seq: usize,
        head_dim: usize,
    ) -> Vec<u8> {
        assert!(
            n_q_heads.is_multiple_of(n_kv_heads),
            "n_q_heads must be divisible by n_kv_heads"
        );
        let group_size = n_q_heads / n_kv_heads;
        let scale = 1.0_f32 / (head_dim as f32).sqrt();

        // Shape constants
        let q_reshape: Vec<i64> = vec![seq as i64, n_q_heads as i64, head_dim as i64];
        let kv_reshape: Vec<i64> = vec![seq as i64, n_kv_heads as i64, head_dim as i64];
        // After transpose: [n_kv_heads, seq, head_dim] → unsqueeze → [n_kv_heads, 1, seq, head_dim]
        // Expand to [n_kv_heads, group_size, seq, head_dim] → reshape [n_q_heads, seq, head_dim]
        let kv_expand: Vec<i64> = vec![
            n_kv_heads as i64,
            group_size as i64,
            seq as i64,
            head_dim as i64,
        ];
        let kv_final: Vec<i64> = vec![n_q_heads as i64, seq as i64, head_dim as i64];
        let out_flat: Vec<i64> = vec![seq as i64, (n_q_heads * head_dim) as i64];

        // Causal mask: 0 on/below diagonal, -inf above
        let causal_data: Vec<f32> = (0..seq)
            .flat_map(|i| (0..seq).map(move |j| if j > i { f32::NEG_INFINITY } else { 0.0_f32 }))
            .collect();

        let nodes = vec![
            // Q: [seq, n_q*head_dim] → [seq, n_q, head_dim] → [n_q, seq, head_dim]
            Node::new("Reshape", &["Q_flat", "q_reshape"], &["Q_3d"]),
            Node::with_attrs(
                "Transpose",
                &["Q_3d"],
                &["Q_t"],
                &[("perm", AttrVal::Ints(vec![1, 0, 2]))],
            ),
            // K: [seq, n_kv*head_dim] → [seq, n_kv, head_dim] → [n_kv, seq, head_dim]
            Node::new("Reshape", &["K_flat", "kv_reshape_k"], &["K_3d"]),
            Node::with_attrs(
                "Transpose",
                &["K_3d"],
                &["K_t"],
                &[("perm", AttrVal::Ints(vec![1, 0, 2]))],
            ),
            // Expand K: [n_kv, seq, hd] → [n_kv, 1, seq, hd] → [n_kv, gs, seq, hd] → [n_q, seq, hd]
            // Opset 13+: axes is a tensor input, not an attribute.
            Node::new("Unsqueeze", &["K_t", "unsq_axes_k"], &["K_4d"]),
            Node::new("Expand", &["K_4d", "kv_expand_k"], &["K_exp4"]),
            Node::new("Reshape", &["K_exp4", "kv_final_k"], &["K_exp"]),
            // V: same expansion as K
            Node::new("Reshape", &["V_flat", "kv_reshape_v"], &["V_3d"]),
            Node::with_attrs(
                "Transpose",
                &["V_3d"],
                &["V_t"],
                &[("perm", AttrVal::Ints(vec![1, 0, 2]))],
            ),
            Node::new("Unsqueeze", &["V_t", "unsq_axes_v"], &["V_4d"]),
            Node::new("Expand", &["V_4d", "kv_expand_v"], &["V_exp4"]),
            Node::new("Reshape", &["V_exp4", "kv_final_v"], &["V_exp"]),
            // K^T for QK matmul: [n_q, seq, head_dim] → [n_q, head_dim, seq]
            Node::with_attrs(
                "Transpose",
                &["K_exp"],
                &["K_T"],
                &[("perm", AttrVal::Ints(vec![0, 2, 1]))],
            ),
            // QK^T: [n_q, seq, seq]
            Node::new("MatMul", &["Q_t", "K_T"], &["QK"]),
            Node::new("Mul", &["QK", "scale"], &["QK_s"]),
            Node::new("Add", &["QK_s", "causal_mask"], &["QK_masked"]),
            Node::with_attrs(
                "Softmax",
                &["QK_masked"],
                &["scores"],
                &[("axis", AttrVal::Int(-1))],
            ),
            // scores @ V: [n_q, seq, head_dim]
            Node::new("MatMul", &["scores", "V_exp"], &["AttnOut_t"]),
            // Transpose back and flatten: [n_q, seq, hd] → [seq, n_q, hd] → [seq, n_q*hd]
            Node::with_attrs(
                "Transpose",
                &["AttnOut_t"],
                &["AttnOut_3d"],
                &[("perm", AttrVal::Ints(vec![1, 0, 2]))],
            ),
            Node::new("Reshape", &["AttnOut_3d", "out_flat"], &["output"]),
        ];

        let initializers = vec![
            Initializer::int64_1d("q_reshape", q_reshape),
            Initializer::int64_1d("kv_reshape_k", kv_reshape.clone()),
            Initializer::int64_1d("kv_reshape_v", kv_reshape),
            Initializer::int64_1d("unsq_axes_k", vec![1]),
            Initializer::int64_1d("unsq_axes_v", vec![1]),
            Initializer::int64_1d("kv_expand_k", kv_expand.clone()),
            Initializer::int64_1d("kv_expand_v", kv_expand),
            Initializer::int64_1d("kv_final_k", kv_final.clone()),
            Initializer::int64_1d("kv_final_v", kv_final),
            Initializer::int64_1d("out_flat", out_flat),
            Initializer::scalar("scale", scale),
            Initializer {
                name: "causal_mask",
                data: InitData::Float(causal_data),
                shape: vec![seq, seq],
            },
        ];

        build_multi_node_model(
            &nodes,
            &[
                ("Q_flat", &[seq, n_q_heads * head_dim]),
                ("K_flat", &[seq, n_kv_heads * head_dim]),
                ("V_flat", &[seq, n_kv_heads * head_dim]),
            ],
            &[("output", &[seq, n_q_heads * head_dim])],
            &initializers,
        )
    }

    // ── Mini transformer fixture ────────────────────────────────────────────

    /// Synthetic mini transformer with a fully dynamic `seq` dimension.
    ///
    /// Input:  `X [dyn_seq, hidden]`   f32  (2-D, no batch dim)
    /// Output: `Y [dyn_seq, vocab]`    f32
    ///
    /// Architecture (~18 nodes, flat attention, tiny weights):
    /// - Q/K/V projections (MatMul, dynamic first dim)
    /// - Flat scaled dot-product attention (QK^T → scale → Softmax → V)
    /// - Output projection + residual Add
    /// - FFN SwiGLU (Sigmoid-gated)
    /// - LM head
    ///
    /// No Reshape ops — all shape projections are derivable by the
    /// ShapeContextGraph walker without value-propagation through shape tensors.
    /// This makes it a reliable fast CI fixture for variable-seq correctness.
    ///
    /// Weights: ~50 KB. Compile: <100 ms. Execute at seq=128: <5 ms.
    pub fn mini_transformer_dyn(
        hidden: usize,
        _n_heads: usize,
        ffn_dim: usize,
        vocab: usize,
    ) -> Vec<u8> {
        let scale = 1.0_f32 / (hidden as f32).sqrt();

        let mk_w = |n: usize, offset: f32| -> Vec<f32> {
            (0..n)
                .map(|i| ((i % 64) as f32 * 0.02 - 0.6) + offset)
                .collect()
        };

        let nodes = vec![
            // ── QKV projections: X [seq, hidden] → Q/K/V [seq, hidden] ──
            Node::new("MatMul", &["X", "w_q"], &["Q"]),
            Node::new("MatMul", &["X", "w_k"], &["K"]),
            Node::new("MatMul", &["X", "w_v"], &["V"]),
            // ── K^T: [hidden, seq] ──
            Node::with_attrs(
                "Transpose",
                &["K"],
                &["K_T"],
                &[("perm", AttrVal::Ints(vec![1, 0]))],
            ),
            // ── Scaled dot-product attention ──
            // QK^T: [seq, seq]
            Node::new("MatMul", &["Q", "K_T"], &["QK"]),
            Node::new("Mul", &["QK", "scale_s"], &["QK_s"]),
            Node::with_attrs(
                "Softmax",
                &["QK_s"],
                &["attn_w"],
                &[("axis", AttrVal::Int(-1))],
            ),
            // attn_out: [seq, hidden]
            Node::new("MatMul", &["attn_w", "V"], &["attn_out"]),
            // ── Output projection + residual ──
            Node::new("MatMul", &["attn_out", "w_o"], &["o_proj"]),
            Node::new("Add", &["X", "o_proj"], &["h2"]),
            // ── FFN SwiGLU: silu(gate) * up → down ──
            Node::new("MatMul", &["h2", "w_gate"], &["gate"]),
            Node::new("Sigmoid", &["gate"], &["gate_s"]),
            Node::new("Mul", &["gate", "gate_s"], &["gate_silu"]),
            Node::new("MatMul", &["h2", "w_up"], &["up"]),
            Node::new("Mul", &["gate_silu", "up"], &["ffn_h"]),
            Node::new("MatMul", &["ffn_h", "w_down"], &["h3"]),
            Node::new("Add", &["h2", "h3"], &["Y_pre"]),
            // ── LM head: [seq, hidden] → [seq, vocab] ──
            Node::new("MatMul", &["Y_pre", "w_lm"], &["Y"]),
        ];

        let initializers = vec![
            Initializer {
                name: "w_q",
                data: InitData::Float(mk_w(hidden * hidden, 0.00)),
                shape: vec![hidden, hidden],
            },
            Initializer {
                name: "w_k",
                data: InitData::Float(mk_w(hidden * hidden, 0.10)),
                shape: vec![hidden, hidden],
            },
            Initializer {
                name: "w_v",
                data: InitData::Float(mk_w(hidden * hidden, 0.20)),
                shape: vec![hidden, hidden],
            },
            Initializer {
                name: "w_o",
                data: InitData::Float(mk_w(hidden * hidden, 0.30)),
                shape: vec![hidden, hidden],
            },
            Initializer {
                name: "w_gate",
                data: InitData::Float(mk_w(hidden * ffn_dim, 0.00)),
                shape: vec![hidden, ffn_dim],
            },
            Initializer {
                name: "w_up",
                data: InitData::Float(mk_w(hidden * ffn_dim, 0.15)),
                shape: vec![hidden, ffn_dim],
            },
            Initializer {
                name: "w_down",
                data: InitData::Float(mk_w(ffn_dim * hidden, 0.05)),
                shape: vec![ffn_dim, hidden],
            },
            Initializer {
                name: "w_lm",
                data: InitData::Float(mk_w(hidden * vocab, 0.00)),
                shape: vec![hidden, vocab],
            },
            Initializer::scalar("scale_s", scale),
        ];

        build_multi_node_model_dyn(
            &nodes,
            &[("X", &[None, Some(hidden)])], // [dyn_seq, hidden]
            &[("Y", &[vocab])],              // placeholder output shape
            &initializers,
        )
    }

    /// Multi-head attention with Unsqueeze/Reshape/Transpose patterns + dynamic seq.
    ///
    /// Exercises the identity-op shape changes (Unsqueeze, Squeeze) that caused
    /// TinyLlama failures. Input is `[dyn_seq, hidden]`. The graph does:
    ///
    /// 1. QKV projections:  X @ W_q/k/v → Q/K/V  `[seq, hidden]`
    /// 2. Reshape to heads:  Reshape(`[seq, hidden]`) → `[seq, n_heads, head_dim]`
    /// 3. Transpose to head-first: `[n_heads, seq, head_dim]`
    /// 4. Unsqueeze K: `[1, n_kv_heads, seq, head_dim]` (batch dim for broadcast)
    /// 5. Attention:  Q @ K^T → softmax → @ V
    /// 6. Transpose back + Reshape → `[seq, hidden]`
    /// 7. Output projection + residual
    ///
    /// hidden=32, n_heads=4, n_kv_heads=4, head_dim=8.
    /// Weights: ~20 KB. Compile: <50 ms. Execute: <2 ms.
    pub fn multihead_attention_dyn(hidden: usize, n_heads: usize, head_dim: usize) -> Vec<u8> {
        assert_eq!(hidden, n_heads * head_dim);
        let scale = 1.0_f32 / (head_dim as f32).sqrt();

        let mk_w = |rows: usize, cols: usize, offset: f32| -> Vec<f32> {
            (0..rows * cols)
                .map(|i| ((i % 64) as f32 * 0.02 - 0.5) + offset)
                .collect()
        };

        // Reshape target shapes as i64 initializers.
        // [seq, n_heads, head_dim] — but seq is dynamic so we use Shape→Concat.
        // For simplicity, we use a fixed reshape target [0, n_heads, head_dim]
        // where 0 means "infer from input".
        let reshape_to_heads: Vec<i64> = vec![-1, n_heads as i64, head_dim as i64];
        let reshape_to_flat: Vec<i64> = vec![-1, hidden as i64];
        let perm_to_head_first: Vec<i64> = vec![1, 0, 2]; // [seq, heads, hd] → [heads, seq, hd]
        let perm_to_seq_first: Vec<i64> = vec![1, 0, 2]; // [heads, seq, hd] → [seq, heads, hd]
        let nodes = vec![
            // ── QKV projections ──
            Node::new("MatMul", &["X", "w_q"], &["Q_flat"]),
            Node::new("MatMul", &["X", "w_k"], &["K_flat"]),
            Node::new("MatMul", &["X", "w_v"], &["V_flat"]),
            // ── Reshape to [seq, n_heads, head_dim] ──
            Node::new("Reshape", &["Q_flat", "shape_heads"], &["Q_3d"]),
            Node::new("Reshape", &["K_flat", "shape_heads"], &["K_3d"]),
            Node::new("Reshape", &["V_flat", "shape_heads"], &["V_3d"]),
            // ── Transpose to head-first: [n_heads, seq, head_dim] ──
            Node::with_attrs(
                "Transpose",
                &["Q_3d"],
                &["Q_hf"],
                &[("perm", AttrVal::Ints(perm_to_head_first.clone()))],
            ),
            Node::with_attrs(
                "Transpose",
                &["K_3d"],
                &["K_hf"],
                &[("perm", AttrVal::Ints(perm_to_head_first.clone()))],
            ),
            Node::with_attrs(
                "Transpose",
                &["V_3d"],
                &["V_hf"],
                &[("perm", AttrVal::Ints(perm_to_head_first))],
            ),
            // ── Unsqueeze K for broadcast: [1, n_kv, seq, hd] ──
            // Opset 13+: axes is a tensor input, not an attribute.
            Node::new("Unsqueeze", &["K_hf", "unsq_axes"], &["K_4d"]),
            // ── Squeeze back: [n_kv, seq, hd] ──
            Node::new("Squeeze", &["K_4d", "sq_axes"], &["K_sq"]),
            // ── K^T: [n_heads, head_dim, seq] ──
            Node::with_attrs(
                "Transpose",
                &["K_sq"],
                &["K_T"],
                &[("perm", AttrVal::Ints(vec![0, 2, 1]))],
            ),
            // ── Scaled dot-product attention ──
            // QK^T: [n_heads, seq, seq]
            Node::new("MatMul", &["Q_hf", "K_T"], &["QK"]),
            Node::new("Mul", &["QK", "scale_s"], &["QK_s"]),
            Node::with_attrs(
                "Softmax",
                &["QK_s"],
                &["attn_w"],
                &[("axis", AttrVal::Int(-1))],
            ),
            // attn_out: [n_heads, seq, head_dim]
            Node::new("MatMul", &["attn_w", "V_hf"], &["attn_hf"]),
            // ── Transpose back to [seq, n_heads, head_dim] ──
            Node::with_attrs(
                "Transpose",
                &["attn_hf"],
                &["attn_sf"],
                &[("perm", AttrVal::Ints(perm_to_seq_first))],
            ),
            // ── Reshape to [seq, hidden] ──
            Node::new("Reshape", &["attn_sf", "shape_flat"], &["attn_flat"]),
            // ── Output projection + residual ──
            Node::new("MatMul", &["attn_flat", "w_o"], &["o_proj"]),
            Node::new("Add", &["X", "o_proj"], &["Y"]),
        ];

        let initializers = vec![
            Initializer {
                name: "w_q",
                data: InitData::Float(mk_w(hidden, hidden, 0.00)),
                shape: vec![hidden, hidden],
            },
            Initializer {
                name: "w_k",
                data: InitData::Float(mk_w(hidden, hidden, 0.10)),
                shape: vec![hidden, hidden],
            },
            Initializer {
                name: "w_v",
                data: InitData::Float(mk_w(hidden, hidden, 0.20)),
                shape: vec![hidden, hidden],
            },
            Initializer {
                name: "w_o",
                data: InitData::Float(mk_w(hidden, hidden, 0.30)),
                shape: vec![hidden, hidden],
            },
            Initializer {
                name: "shape_heads",
                data: InitData::Int64(reshape_to_heads),
                shape: vec![3],
            },
            Initializer {
                name: "shape_flat",
                data: InitData::Int64(reshape_to_flat),
                shape: vec![2],
            },
            Initializer {
                name: "unsq_axes",
                data: InitData::Int64(vec![0]),
                shape: vec![1],
            },
            Initializer {
                name: "sq_axes",
                data: InitData::Int64(vec![0]),
                shape: vec![1],
            },
            Initializer::scalar("scale_s", scale),
        ];

        build_multi_node_model_dyn(
            &nodes,
            &[("X", &[None, Some(hidden)])], // [dyn_seq, hidden]
            &[("Y", &[hidden])],             // placeholder
            &initializers,
        )
    }

    // ── Dynamic-seq builder helpers ────────────────────────────────────────

    /// Build a multi-node ONNX model where some graph inputs have dynamic dims.
    ///
    /// `dyn_inputs`: `(name, shape)` where `None` dims are symbolic (not folded by DataProp).
    /// `concrete_outputs`: `(name, shape)` with fully-concrete output shapes for graph output decl.
    pub fn build_multi_node_model_dyn(
        nodes: &[Node],
        dyn_inputs: &[(&str, &[Option<usize>])],
        concrete_outputs: &[(&str, &[usize])],
        initializers: &[Initializer],
    ) -> Vec<u8> {
        let mut buf = Vec::new();

        let graph_inputs: Vec<Vec<u8>> = dyn_inputs
            .iter()
            .map(|(name, shape)| encode_value_info_dyn(name, shape))
            .collect();
        let graph_outputs: Vec<Vec<u8>> = concrete_outputs
            .iter()
            .map(|(name, shape)| encode_value_info(name, shape))
            .collect();

        let mut graph = Vec::new();
        for node in nodes {
            let encoded = encode_node_struct(node);
            write_field(&mut graph, 1, &encoded);
        }
        write_string(&mut graph, 2, "test_graph");
        for init in initializers {
            let encoded = encode_initializer(init);
            write_field(&mut graph, 5, &encoded);
        }
        for inp in &graph_inputs {
            write_field(&mut graph, 11, inp);
        }
        for out in &graph_outputs {
            write_field(&mut graph, 12, out);
        }

        write_varint_field(&mut buf, 1, 8);
        write_field(&mut buf, 7, &graph);
        write_field(&mut buf, 8, &encode_opset(17));
        buf
    }

    /// Softmax model with dynamic seq dimension.
    ///
    /// Input:  X  [batch=1, DYN_seq, hidden] (seq is symbolic/dynamic)
    /// Output: Y  [batch=1, DYN_seq, hidden] (same shape)
    ///
    /// Used to verify that `resolve_dynamic_sizes()` correctly patches the Softmax
    /// `size` parameter at runtime when the compiled archive has `size=1` (from
    /// concretize_all_dims) but the actual input has seq>1.
    pub fn softmax_dyn_seq(hidden: usize) -> Vec<u8> {
        let nodes = vec![Node::with_attrs(
            "Softmax",
            &["X"],
            &["Y"],
            &[("axis", AttrVal::Int(-1))],
        )];
        // seq=None → dynamic/symbolic in ONNX
        build_multi_node_model_dyn(
            &nodes,
            &[("X", &[Some(1), None, Some(hidden)])],
            &[("Y", &[hidden])], // output shape hint (not critical for comparison)
            &[],
        )
    }

    /// MatMul model with dynamic seq dimension.
    ///
    /// Input:  X  [batch=1, DYN_seq, k] (seq is symbolic/dynamic)
    ///         W  `[k, n]`                (concrete weight)
    /// Output: Y  [batch=1, DYN_seq, n]
    ///
    /// Used to verify that the MatMul kernel correctly infers `m` from the input
    /// buffer size when the compiled archive has `m=1` (from concretize_all_dims)
    /// but the actual input has seq>1.
    pub fn matmul_dyn_seq(k: usize, n: usize) -> Vec<u8> {
        let nodes = vec![Node::new("MatMul", &["X", "W"], &["Y"])];
        build_multi_node_model_dyn(
            &nodes,
            &[("X", &[Some(1), None, Some(k)]), ("W", &[Some(k), Some(n)])],
            &[("Y", &[n])], // output shape hint
            &[],
        )
    }

    /// Reshape model that unpacks hidden_dim into `[heads, head_dim]` with dynamic seq.
    ///
    /// Input:  X  [batch=1, DYN_seq, num_heads*head_dim]
    /// Shape computation: Shape(X) → Slice → Concat → shape tensor `[1, num_heads, seq, head_dim]`
    /// Output: Y  [batch=1, num_heads, DYN_seq, head_dim]
    ///
    /// This is the exact pattern used in TinyLlama's transformer attention layers.
    /// It fails at seq>1 because `concretize_all_dims` + `DataPropagation` constant-folds
    /// the Shape op output to `[1, 1, num_heads*head_dim]` (seq=1), so the Reshape
    /// target shape tensor contains seq=1 permanently.
    ///
    /// The test using this model at seq>1 is expected to fail until shape-polymorphic
    /// compilation is fully implemented (ShapeContextGraph Plan 008 completion).
    pub fn reshape_unpack_heads_dyn_seq(num_heads: usize, head_dim: usize) -> Vec<u8> {
        // Graph:
        //   Shape(X) → x_shape [3]  (int64: [1, seq, num_heads*head_dim])
        //   Slice(x_shape, 1:2) → seq_val [1]  (int64: [seq])
        //   Concat([batch_c, num_heads_c, seq_val, head_dim_c]) → reshape_target [4]
        //   Reshape(X, reshape_target) → Y [1, num_heads, seq, head_dim]
        let nodes = vec![
            Node::new("Shape", &["X"], &["x_shape"]),
            Node::new(
                "Slice",
                &["x_shape", "slice_s1", "slice_e2", "slice_ax0"],
                &["seq_val"],
            ),
            Node::with_attrs(
                "Concat",
                &["batch_c", "num_heads_c", "seq_val", "head_dim_c"],
                &["reshape_target"],
                &[("axis", AttrVal::Int(0))],
            ),
            Node::new("Reshape", &["X", "reshape_target"], &["Y"]),
        ];
        let initializers = vec![
            Initializer::int64_1d("slice_s1", vec![1]),
            Initializer::int64_1d("slice_e2", vec![2]),
            Initializer::int64_1d("slice_ax0", vec![0]),
            Initializer::int64_1d("batch_c", vec![1]),
            Initializer::int64_1d("num_heads_c", vec![num_heads as i64]),
            Initializer::int64_1d("head_dim_c", vec![head_dim as i64]),
        ];
        build_multi_node_model_dyn(
            &nodes,
            &[("X", &[Some(1), None, Some(num_heads * head_dim)])],
            &[("Y", &[num_heads * head_dim])], // placeholder output shape
            &initializers,
        )
    }

    // ── Vision op builders ──────────────────────────────────────────────────

    /// Shape and strides for [`conv2d`] model builder.
    #[derive(Debug, Clone, Copy)]
    pub struct Conv2dSpec {
        pub n: usize,
        pub ic: usize,
        pub h: usize,
        pub w: usize,
        pub oc: usize,
        pub kh: usize,
        pub kw: usize,
        pub stride: usize,
        pub pad: usize,
    }

    impl Conv2dSpec {
        /// New spec with default `stride = 1` and `pad = 0`.
        pub fn new(
            n: usize,
            ic: usize,
            h: usize,
            w: usize,
            oc: usize,
            kh: usize,
            kw: usize,
        ) -> Self {
            Self {
                n,
                ic,
                h,
                w,
                oc,
                kh,
                kw,
                stride: 1,
                pad: 0,
            }
        }

        pub fn with_stride(mut self, stride: usize) -> Self {
            self.stride = stride;
            self
        }

        pub fn with_pad(mut self, pad: usize) -> Self {
            self.pad = pad;
            self
        }
    }

    /// Build a Conv ONNX model with initializer weights.
    /// Graph: input "X" `[n, ic, h, w]` + initializer "W" `[oc, ic, kh, kw]` → Conv → "Y"
    pub fn conv2d(spec: Conv2dSpec) -> Vec<u8> {
        let Conv2dSpec {
            n,
            ic,
            h,
            w,
            oc,
            kh,
            kw,
            stride,
            pad,
        } = spec;
        let h_out = (h + 2 * pad - kh) / stride + 1;
        let w_out = (w + 2 * pad - kw) / stride + 1;
        let weight_len = oc * ic * kh * kw;
        let weight_data: Vec<f32> = (0..weight_len).map(|i| ((i as f32) * 0.01).sin()).collect();
        let nodes = vec![Node::with_attrs(
            "Conv",
            &["X", "W"],
            &["Y"],
            &[
                ("kernel_shape", AttrVal::Ints(vec![kh as i64, kw as i64])),
                ("strides", AttrVal::Ints(vec![stride as i64, stride as i64])),
                (
                    "pads",
                    AttrVal::Ints(vec![pad as i64, pad as i64, pad as i64, pad as i64]),
                ),
            ],
        )];
        let initializers = vec![Initializer::float_nd(
            "W",
            weight_data,
            vec![oc, ic, kh, kw],
        )];
        build_multi_node_model(
            &nodes,
            &[("X", &[n, ic, h, w])],
            &[("Y", &[n, oc, h_out, w_out])],
            &initializers,
        )
    }

    /// Build a Conv+Relu+GlobalAveragePool model (no FC layer).
    pub fn conv_relu_gap(ic: usize, h: usize, w: usize, oc: usize) -> Vec<u8> {
        let kh = 3;
        let kw = 3;
        let weight_len = oc * ic * kh * kw;
        let weight_data: Vec<f32> = (0..weight_len).map(|i| ((i as f32) * 0.01).sin()).collect();
        let nodes = vec![
            Node::with_attrs(
                "Conv",
                &["X", "conv_W"],
                &["conv_out"],
                &[("kernel_shape", AttrVal::Ints(vec![kh as i64, kw as i64]))],
            ),
            Node::new("Relu", &["conv_out"], &["relu_out"]),
            Node::new("GlobalAveragePool", &["relu_out"], &["Y"]),
        ];
        let initializers = vec![Initializer::float_nd(
            "conv_W",
            weight_data,
            vec![oc, ic, kh, kw],
        )];
        build_multi_node_model(
            &nodes,
            &[("X", &[1, ic, h, w])],
            &[("Y", &[1, oc, 1, 1])],
            &initializers,
        )
    }

    /// Build a Conv+Relu+GlobalAveragePool+Flatten+Gemm (mini classifier) model.
    /// This exercises the full ResNet-style pipeline at tiny scale.
    pub fn mini_vision_classifier(
        ic: usize,
        h: usize,
        w: usize,
        oc: usize,
        num_classes: usize,
    ) -> Vec<u8> {
        let kh = 3;
        let kw = 3;
        let conv_weight_len = oc * ic * kh * kw;
        let conv_weight: Vec<f32> = (0..conv_weight_len)
            .map(|i| ((i as f32) * 0.01).sin())
            .collect();
        // Gemm weight: [num_classes, oc] and bias: [num_classes]
        let gemm_weight: Vec<f32> = (0..num_classes * oc)
            .map(|i| ((i as f32) * 0.005).cos())
            .collect();
        let gemm_bias: Vec<f32> = (0..num_classes).map(|i| (i as f32) * 0.01).collect();

        let h_out = h - kh + 1; // no padding
        let w_out = w - kw + 1;
        // GlobalAveragePool: [1, oc, h_out, w_out] → [1, oc, 1, 1]

        let nodes = vec![
            Node::with_attrs(
                "Conv",
                &["X", "conv_W"],
                &["conv_out"],
                &[("kernel_shape", AttrVal::Ints(vec![kh as i64, kw as i64]))],
            ),
            Node::new("Relu", &["conv_out"], &["relu_out"]),
            Node::new("GlobalAveragePool", &["relu_out"], &["pool_out"]),
            Node::with_attrs(
                "Flatten",
                &["pool_out"],
                &["flat_out"],
                &[("axis", AttrVal::Int(1))],
            ),
            Node::with_attrs(
                "Gemm",
                &["flat_out", "gemm_W", "gemm_B"],
                &["Y"],
                &[("transB", AttrVal::Int(1))],
            ),
        ];
        let initializers = vec![
            Initializer::float_nd("conv_W", conv_weight, vec![oc, ic, kh, kw]),
            Initializer::float_nd("gemm_W", gemm_weight, vec![num_classes, oc]),
            Initializer::float_nd("gemm_B", gemm_bias, vec![num_classes]),
        ];
        // Note: output shape for ORT doesn't need to be exact — ORT infers it.
        // We provide a best-effort shape for the value_info.
        let _ = (h_out, w_out); // used for documentation only
        build_multi_node_model(
            &nodes,
            &[("X", &[1, ic, h, w])],
            &[("Y", &[1, num_classes])],
            &initializers,
        )
    }

    // ── Protobuf encoding helpers ───────────────────────────────────────────

    pub enum AttrVal {
        Int(i64),
        Float(f32),
        Ints(Vec<i64>),
    }

    pub struct Node {
        pub op_type: &'static str,
        pub inputs: Vec<&'static str>,
        pub outputs: Vec<&'static str>,
        pub attrs: Vec<(&'static str, AttrVal)>,
    }

    impl Node {
        pub fn new(
            op_type: &'static str,
            inputs: &[&'static str],
            outputs: &[&'static str],
        ) -> Self {
            Self {
                op_type,
                inputs: inputs.to_vec(),
                outputs: outputs.to_vec(),
                attrs: vec![],
            }
        }

        pub fn with_attrs(
            op_type: &'static str,
            inputs: &[&'static str],
            outputs: &[&'static str],
            attrs: &[(&'static str, AttrVal)],
        ) -> Self {
            Self {
                op_type,
                inputs: inputs.to_vec(),
                outputs: outputs.to_vec(),
                attrs: attrs.iter().map(|(n, v)| (*n, v.clone())).collect(),
            }
        }
    }

    pub enum InitData {
        Float(Vec<f32>),
        Int64(Vec<i64>),
    }

    pub struct Initializer {
        pub name: &'static str,
        pub data: InitData,
        pub shape: Vec<usize>,
    }

    impl Initializer {
        pub fn scalar(name: &'static str, val: f32) -> Self {
            Self {
                name,
                data: InitData::Float(vec![val]),
                shape: vec![],
            }
        }

        /// 1-D INT64 initializer — used for shape inputs (e.g. Expand's `shape` argument).
        pub fn int64_1d(name: &'static str, vals: Vec<i64>) -> Self {
            let n = vals.len();
            Self {
                name,
                data: InitData::Int64(vals),
                shape: vec![n],
            }
        }

        /// Scalar (rank-0) INT64 initializer — used for Range start/limit/delta.
        pub fn int64_scalar(name: &'static str, val: i64) -> Self {
            Self {
                name,
                data: InitData::Int64(vec![val]),
                shape: vec![],
            }
        }

        /// N-D float initializer — used for Conv2d weights, biases, etc.
        pub fn float_nd(name: &'static str, data: Vec<f32>, shape: Vec<usize>) -> Self {
            Self {
                name,
                data: InitData::Float(data),
                shape,
            }
        }
    }

    impl Clone for AttrVal {
        fn clone(&self) -> Self {
            match self {
                Self::Int(v) => Self::Int(*v),
                Self::Float(v) => Self::Float(*v),
                Self::Ints(v) => Self::Ints(v.clone()),
            }
        }
    }

    fn build_model(
        op_type: &str,
        inputs: &[(&str, &[usize])],
        outputs: &[(&str, &[usize])],
        attrs: &[(&str, AttrVal)],
    ) -> Vec<u8> {
        let mut buf = Vec::new();

        // Single-node graph
        let node = encode_single_node(
            op_type,
            &inputs.iter().map(|(n, _)| *n).collect::<Vec<_>>(),
            &outputs.iter().map(|(n, _)| *n).collect::<Vec<_>>(),
            attrs,
        );

        let graph_inputs: Vec<Vec<u8>> = inputs
            .iter()
            .map(|(name, shape)| encode_value_info(name, shape))
            .collect();
        let graph_outputs: Vec<Vec<u8>> = outputs
            .iter()
            .map(|(name, shape)| encode_value_info(name, shape))
            .collect();

        let mut graph = Vec::new();
        write_field(&mut graph, 1, &node);
        write_string(&mut graph, 2, "test_graph");
        for inp in &graph_inputs {
            write_field(&mut graph, 11, inp);
        }
        for out in &graph_outputs {
            write_field(&mut graph, 12, out);
        }

        write_varint_field(&mut buf, 1, 8);
        write_field(&mut buf, 7, &graph);
        write_field(&mut buf, 8, &encode_opset(17));
        buf
    }

    fn encode_single_node(
        op_type: &str,
        inputs: &[&str],
        outputs: &[&str],
        attrs: &[(&str, AttrVal)],
    ) -> Vec<u8> {
        let mut node = Vec::new();
        for name in inputs {
            write_string(&mut node, 1, name);
        }
        for name in outputs {
            write_string(&mut node, 2, name);
        }
        write_string(&mut node, 4, op_type);
        for (name, val) in attrs {
            let attr = encode_attr(name, val);
            write_field(&mut node, 5, &attr);
        }
        node
    }

    pub fn build_multi_node_model(
        nodes: &[Node],
        inputs: &[(&str, &[usize])],
        outputs: &[(&str, &[usize])],
        initializers: &[Initializer],
    ) -> Vec<u8> {
        let mut buf = Vec::new();

        // Graph inputs (ValueInfoProto)
        let graph_inputs: Vec<Vec<u8>> = inputs
            .iter()
            .map(|(name, shape)| encode_value_info(name, shape))
            .collect();

        // Graph outputs (ValueInfoProto)
        let graph_outputs: Vec<Vec<u8>> = outputs
            .iter()
            .map(|(name, shape)| encode_value_info(name, shape))
            .collect();

        // GraphProto (onnx.proto3 field numbers)
        let mut graph = Vec::new();
        // field 1: node (repeated)
        for node in nodes {
            let encoded = encode_node_struct(node);
            write_field(&mut graph, 1, &encoded);
        }
        // field 2: name
        write_string(&mut graph, 2, "test_graph");
        // field 5: initializer (repeated TensorProto)
        for init in initializers {
            let encoded = encode_initializer(init);
            write_field(&mut graph, 5, &encoded);
        }
        // field 11: input (repeated ValueInfoProto)
        for inp in &graph_inputs {
            write_field(&mut graph, 11, inp);
        }
        // field 12: output (repeated ValueInfoProto)
        for out in &graph_outputs {
            write_field(&mut graph, 12, out);
        }

        // ModelProto
        // field 1: ir_version (int64) = 8
        write_varint_field(&mut buf, 1, 8);
        // field 7: graph
        write_field(&mut buf, 7, &graph);
        // field 8: opset_import
        let opset = encode_opset(17);
        write_field(&mut buf, 8, &opset);

        buf
    }

    fn encode_node_struct(node: &Node) -> Vec<u8> {
        let mut buf = Vec::new();
        // field 1: input (repeated string)
        for name in &node.inputs {
            write_string(&mut buf, 1, name);
        }
        // field 2: output (repeated string)
        for name in &node.outputs {
            write_string(&mut buf, 2, name);
        }
        // field 4: op_type
        write_string(&mut buf, 4, node.op_type);
        // field 5: attribute (repeated)
        for (name, val) in &node.attrs {
            let attr = encode_attr(name, val);
            write_field(&mut buf, 5, &attr);
        }
        buf
    }

    fn encode_attr(name: &str, val: &AttrVal) -> Vec<u8> {
        let mut attr = Vec::new();
        // field 1: name
        write_string(&mut attr, 1, name);
        match val {
            AttrVal::Int(v) => {
                // field 3: i (int64)
                write_varint_field(&mut attr, 3, *v as u64);
                // field 20: type = INT (2)
                write_varint_field(&mut attr, 20, 2);
            }
            AttrVal::Float(v) => {
                // field 2: f (float)
                write_fixed32_field(&mut attr, 2, v.to_bits());
                // field 20: type = FLOAT (1)
                write_varint_field(&mut attr, 20, 1);
            }
            AttrVal::Ints(vals) => {
                // field 8: ints (repeated int64)
                for v in vals {
                    write_varint_field(&mut attr, 8, *v as u64);
                }
                // field 20: type = INTS (7)
                write_varint_field(&mut attr, 20, 7);
            }
        }
        attr
    }

    /// Encode a TensorProto initializer (constant tensor).
    fn encode_initializer(init: &Initializer) -> Vec<u8> {
        let mut tp = Vec::new();
        // field 1: dims (repeated int64)
        for &d in &init.shape {
            write_varint_field(&mut tp, 1, d as u64);
        }
        match &init.data {
            InitData::Float(data) => {
                // field 2: data_type = FLOAT (1)
                write_varint_field(&mut tp, 2, 1);
                // field 4: float_data (raw bytes, little-endian)
                let mut float_bytes = Vec::with_capacity(data.len() * 4);
                for &v in data {
                    float_bytes.extend_from_slice(&v.to_le_bytes());
                }
                write_field(&mut tp, 4, &float_bytes);
            }
            InitData::Int64(data) => {
                // field 2: data_type = INT64 (7)
                write_varint_field(&mut tp, 2, 7);
                // field 7: int64_data (repeated int64 varints)
                for &v in data {
                    write_varint_field(&mut tp, 7, v as u64);
                }
            }
        }
        // field 8: name
        write_string(&mut tp, 8, init.name);
        tp
    }

    /// Like `encode_value_info` but accepts `None` for fully-dynamic dimensions.
    ///
    /// A `None` dim is encoded as an **empty** TensorShapeProto.Dimension message
    /// (no fields written).  prost decodes `value = None` → `Dim::Dynamic` in
    /// hologram-ai's ONNX importer, which DataPropagation cannot concretize.
    /// This ensures `FloatOp::Shape` nodes survive to runtime so start/end
    /// slicing is exercised.
    fn encode_value_info_dyn(name: &str, shape: &[Option<usize>]) -> Vec<u8> {
        let mut vi = Vec::new();
        write_string(&mut vi, 1, name);
        let mut type_proto = Vec::new();
        let mut tensor_type = Vec::new();
        write_varint_field(&mut tensor_type, 1, 1); // elem_type = FLOAT (1)
        let mut shape_proto = Vec::new();
        for &dim in shape {
            let mut dim_proto = Vec::new();
            if let Some(v) = dim {
                write_varint_field(&mut dim_proto, 1, v as u64); // dim_value
            } // None → empty → Dim::Dynamic (not folded)
            write_field(&mut shape_proto, 1, &dim_proto);
        }
        write_field(&mut tensor_type, 2, &shape_proto);
        write_field(&mut type_proto, 1, &tensor_type);
        write_field(&mut vi, 2, &type_proto);
        vi
    }

    fn encode_value_info(name: &str, shape: &[usize]) -> Vec<u8> {
        let mut vi = Vec::new();
        // field 1: name
        write_string(&mut vi, 1, name);

        // field 2: type (TypeProto)
        let mut type_proto = Vec::new();
        // TypeProto field 1: tensor_type
        let mut tensor_type = Vec::new();
        // TensorTypeProto field 1: elem_type = FLOAT (1)
        write_varint_field(&mut tensor_type, 1, 1);
        // TensorTypeProto field 2: shape (TensorShapeProto)
        let mut shape_proto = Vec::new();
        for &dim in shape {
            // Dimension field 1: dim_value (int64)
            let mut dim_proto = Vec::new();
            write_varint_field(&mut dim_proto, 1, dim as u64);
            write_field(&mut shape_proto, 1, &dim_proto);
        }
        write_field(&mut tensor_type, 2, &shape_proto);
        write_field(&mut type_proto, 1, &tensor_type);
        write_field(&mut vi, 2, &type_proto);

        vi
    }

    fn encode_opset(version: u64) -> Vec<u8> {
        let mut opset = Vec::new();
        // field 1: domain (string, empty = default ONNX domain)
        write_string(&mut opset, 1, "");
        // field 2: version (int64)
        write_varint_field(&mut opset, 2, version);
        opset
    }

    // ── Low-level protobuf encoding ─────────────────────────────────────────

    fn write_varint(buf: &mut Vec<u8>, val: u64) {
        let mut v = val;
        loop {
            let byte = (v & 0x7F) as u8;
            v >>= 7;
            if v == 0 {
                buf.push(byte);
                break;
            }
            buf.push(byte | 0x80);
        }
    }

    fn write_field(buf: &mut Vec<u8>, field: u32, data: &[u8]) {
        // wire type 2 (length-delimited)
        write_varint(buf, ((field as u64) << 3) | 2);
        write_varint(buf, data.len() as u64);
        buf.extend_from_slice(data);
    }

    fn write_string(buf: &mut Vec<u8>, field: u32, s: &str) {
        write_field(buf, field, s.as_bytes());
    }

    fn write_varint_field(buf: &mut Vec<u8>, field: u32, val: u64) {
        // wire type 0 (varint)
        write_varint(buf, (field as u64) << 3);
        write_varint(buf, val);
    }

    fn write_fixed32_field(buf: &mut Vec<u8>, field: u32, val: u32) {
        // wire type 5 (32-bit)
        write_varint(buf, ((field as u64) << 3) | 5);
        buf.extend_from_slice(&val.to_le_bytes());
    }
}
