/-!
  lean/Core/Axioms.lean
  Quarantined axioms and FFI bindings for the zero-Mathlib core.
-/

namespace Core.Axioms

/-- FFI Axiom Proxy: Ingests the cryptographic stability certificate 
    generated by Kani bounded model checking over exact rational intervals. -/
@[extern "check_cdsi_stability"]
axiom kani_stability_certificate (norm_num norm_den lip_num lip_den : Nat) : Bool

end Core.Axioms
