-- @generated by uor-lean from uor-ontology — do not edit manually
--
-- UOR Foundation — Lean 4 formalization root.

import Core.UOR
import Core.UOR.Enums
import Core.UOR.Structures
import Core.UOR.Individuals
import Core.UOR.Enforcement
import Core.UOR.Pipeline
import Core.UOR.Examples
import Core.UOR.Test
import Core.UOR.Prelude
