import Foundations.UOR.Individuals.Schema
import Foundations.UOR.Individuals.Op
import Foundations.UOR.Individuals.Resolver
import Foundations.UOR.Individuals.Type_
import Foundations.UOR.Individuals.Foundation
import Foundations.UOR.Individuals.Observable
import Foundations.UOR.Individuals.Homology
import Foundations.UOR.Individuals.Cohomology
import Foundations.UOR.Individuals.Proof
import Foundations.UOR.Individuals.Trace
import Foundations.UOR.Individuals.Morphism
import Foundations.UOR.Individuals.State
import Foundations.UOR.Individuals.Reduction
import Foundations.UOR.Individuals.Convergence
import Foundations.UOR.Individuals.Division
import Foundations.UOR.Individuals.Predicate
import Foundations.UOR.Individuals.Conformance_

-- @generated by uor-lean from uor-ontology — do not edit manually
--
-- UOR Foundation — individual constant namespaces (aggregator).

