// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @notice Interface for the Groth16/Plonk ZK Verifier generated by Circom for UORMatMul
interface IUORMatMulVerifier {
    function verifyProof(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[1] memory input
    ) external view returns (bool);
}

/**
 * @title PhaseMirror Anchor Contract
 * @notice The ultimate settlement layer for the Universal Atomic Calculator (UAC).
 * @dev Enforces the Consensus Boundary (Pathway 3).
 *
 * This contract anchors the `Fit` state of a node/community on-chain.
 * It strictly refuses any state transitions unless accompanied by a cryptographically 
 * valid zero-knowledge proof (ZK-SNARK) demonstrating that the new state was reached 
 * through integer-exact UOR MatMul operations under the K_MAX ceiling (133144).
 */
contract AnchorContract {
    address public immutable owner;
    IUORMatMulVerifier public immutable zkVerifier;

    // The current anchored geometric state hash of the community/node
    bytes32 public currentPhaseState;

    event StateAnchored(bytes32 indexed oldState, bytes32 indexed newState, uint256 accumValue);
    event SymmetryConfinementRejected(bytes32 attemptedState);

    constructor(address _verifier, bytes32 _initialState) {
        owner = msg.sender;
        zkVerifier = IUORMatMulVerifier(_verifier);
        currentPhaseState = _initialState;
    }

    /**
     * @notice Propose a state update generated by the Rust `pirtm-engine` and `CRMFWitness`.
     * @param newState The hash of the newly computed tensor state.
     * @param expectedAccum The exact integer accumulation generated by the UAC.
     * @param a ZK Proof Parameter A
     * @param b ZK Proof Parameter B
     * @param c ZK Proof Parameter C
     */
    function anchorState(
        bytes32 newState,
        uint256 expectedAccum,
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c
    ) external {
        // Construct the public inputs array expected by the Circom Verifier
        // In UORMatMul.circom, the single public output/input is the expected_accum
        uint256[1] memory publicInputs = [expectedAccum];

        // The Consensus Boundary: Verify the ZK Proof
        bool isValid = zkVerifier.verifyProof(a, b, c, publicInputs);
        
        if (!isValid) {
            emit SymmetryConfinementRejected(newState);
            revert("L3_MonsterSymmetryConfinement: Invalid ZK Proof. State drift detected.");
        }

        // If the proof is valid, the mathematics are sound. Anchor the state.
        bytes32 oldState = currentPhaseState;
        currentPhaseState = newState;

        emit StateAnchored(oldState, newState, expectedAccum);
    }
}
