// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;
pragma experimental ABIEncoderV2;

// NOTE: These verifiers will be generated by build-circuits.mjs and scripts/generate-verifiers.mjs
// Temporarily commented out for initial compilation
// import "./RootVerifier.sol";
// import "./RecoveryVerifier.sol";
// import "./MillerRabinVerifier.sol";
// Per-circuit verifier interfaces (use the fixed-size public-input shapes generated by snarkJS)
interface IRootVerifier {
    function verifyProof(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[5] memory input
    ) external view returns (bool);
}

interface IRecoveryVerifier {
    function verifyProof(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[6] memory input
    ) external view returns (bool);
}

interface IMillerRabinVerifier {
    function verifyProof(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[1] memory input
    ) external view returns (bool);
}
import "./Poseidon.sol";
import "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol";
import "./interfaces/IGovernance.sol";

contract MTPI_Core {
    IRootVerifier public immutable rootVerifier;
    IRecoveryVerifier public immutable recoveryVerifier;
    IMillerRabinVerifier public immutable millerRabinVerifier;
    Poseidon public immutable poseidon;
    IGovernance public governance;
    address public admin;

    uint256 public constant MIN_PRIME_INDEX = 2;
    uint256 public constant MAX_DRIFT = 3e17;
    bool public inSilentRecovery;
    bytes32 public currentState;

    struct XiState {
        bytes32 currentHash;
        uint256 lastPrimeIndex;
        uint256[] primeGates;
        mapping(address => bytes32) identityRegistry;
        mapping(uint256 => bool) usedProofHashes;
    }

    XiState private _state;

    event XiStateTransition(
        bytes32 indexed previousState,
        bytes32 indexed newState,
        address indexed executor,
        uint256 timestamp,
        bytes32 proofHash
    );
    event PrimeGateActivation(uint256 indexed primeIndex, address indexed activator, bytes32 proofHash);
    event IdentityRegistered(address indexed entity, bytes32 identityHash);
    event RecoveryModeActivated(uint256 timestamp);

    error InvalidProof();
    error StasisViolation();
    error DuplicateIdentity();
    error PrimeOrderViolation(uint256 provided, uint256 required);
    error UnregisteredIdentity();
    error InvalidPrime(uint256 value);
    error ExcessiveDrift(uint256 drift);
    error ReusedProof(bytes32 proofHash);
    error InRecoveryMode();

    constructor(
        address rootVerifier_,
        address recoveryVerifier_,
        address millerRabinVerifier_,
        address poseidon_,
        bytes32 genesisState
    ) {
        require(rootVerifier_ != address(0), "Zero root verifier");
        require(recoveryVerifier_ != address(0), "Zero recovery verifier");
        require(millerRabinVerifier_ != address(0), "Zero millerRabin verifier");
        require(poseidon_ != address(0), "Zero poseidon");

        rootVerifier = IRootVerifier(rootVerifier_);
        recoveryVerifier = IRecoveryVerifier(recoveryVerifier_);
        millerRabinVerifier = IMillerRabinVerifier(millerRabinVerifier_);
        poseidon = Poseidon(poseidon_);
        admin = msg.sender;

        _state.currentHash = genesisState;
        currentState = genesisState;
        _state.lastPrimeIndex = MIN_PRIME_INDEX;
        _state.primeGates.push(MIN_PRIME_INDEX);
    }

    modifier onlyAdmin() {
        require(msg.sender == admin, "not-admin");
        _;
    }

    function setGovernance(address gov) external onlyAdmin {
        require(gov != address(0), "governance=0");
        governance = IGovernance(gov);
    }

    function quantumTransition(
      uint256[2] memory a,
      uint256[2][2] memory b,
      uint256[2] memory c,
      uint256[] memory input,
      bytes32 proofHash
    ) external returns (bytes32) {
      if (address(governance) != address(0)) {
          require(governance.isApproved(msg.sender), "Gov: actor not approved");
      }
    require(input.length > 0, "No public signals");

    // Anti-replay: Check if proof has been used before
      uint256 proofHashUint = uint256(proofHash);
      if (_state.usedProofHashes[proofHashUint]) revert ReusedProof(proofHash);
      
      // Root verifier expects 5 public-inputs ([state, ...]) in generated verifiers.
      // Normalise the dynamic input into a fixed-length 5-tuple (zero pad if shorter)
      uint256[5] memory rootInput;
      for (uint256 i = 0; i < 5 && i < input.length; i++) {
          rootInput[i] = input[i];
      }
      require(rootVerifier.verifyProof(a, b, c, rootInput), "InvalidProof");
      
      // Mark proof as used
      _state.usedProofHashes[proofHashUint] = true;

      bytes32 prev = currentState;
      bytes32 newState = bytes32(input[0]);
      currentState = newState;

      emit XiStateTransition(prev, newState, msg.sender, block.timestamp, proofHash);
      return newState;
    }


    function registerIdentity(bytes32 identityHash, bytes32 zkProofHash) external {
        if (inSilentRecovery) revert InRecoveryMode();
        if (_state.identityRegistry[msg.sender] != bytes32(0)) revert DuplicateIdentity();
        if (zkProofHash == bytes32(0)) revert InvalidProof();

        _state.identityRegistry[msg.sender] = identityHash;
        emit IdentityRegistered(msg.sender, identityHash);
        emit PrimeGateActivation(0, msg.sender, zkProofHash);
    }

    function activatePrimeGate(uint256 primeIndex, bytes32 proofHash) external {
        if (inSilentRecovery) revert InRecoveryMode();
        if (_state.identityRegistry[msg.sender] == bytes32(0)) revert UnregisteredIdentity();
        if (proofHash == bytes32(0)) revert InvalidProof();
        if (primeIndex <= _state.lastPrimeIndex) revert PrimeOrderViolation(primeIndex, _state.lastPrimeIndex + 1);
        if (!_isCertifiedPrime(primeIndex)) revert InvalidPrime(primeIndex);

        uint256[1] memory input1;
        input1[0] = primeIndex;
        uint256[2] memory zeroA = [uint256(0), uint256(0)];
        uint256[2][2] memory zeroB = [[uint256(0), uint256(0)], [uint256(0), uint256(0)]];
        uint256[2] memory zeroC = [uint256(0), uint256(0)];
        if (!millerRabinVerifier.verifyProof(zeroA, zeroB, zeroC, input1)) revert InvalidProof();

        _state.primeGates.push(primeIndex);
        _state.lastPrimeIndex = primeIndex;
        emit PrimeGateActivation(primeIndex, msg.sender, proofHash);
    }

    function enterSilentRecovery(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[6] calldata input,
        bytes32 proofHash
    ) external {
        if (_state.identityRegistry[msg.sender] == bytes32(0)) revert UnregisteredIdentity();
        // If we're already in silent recovery, block further entry attempts immediately
        if (inSilentRecovery) revert InRecoveryMode();
        if (proofHash == bytes32(0)) revert InvalidProof();
        
        // Anti-replay: Check if proof has been used before
        uint256 proofHashUint = uint256(proofHash);
        if (_state.usedProofHashes[proofHashUint]) revert ReusedProof(proofHash);
        
        // The generated RecoveryVerifier expects a fixed 6-length public input; pass the calldata fixed array directly.
        if (!recoveryVerifier.verifyProof(a, b, c, input)) revert InvalidProof();
        
        // Mark proof as used
        _state.usedProofHashes[proofHashUint] = true;

        inSilentRecovery = true;
        emit RecoveryModeActivated(block.timestamp);
    }

    function getCurrentState() external view returns (bytes32) {
        return currentState;
    }

    function checkPrimeAccess(address entity, uint256 primeIndex) external view returns (bool) {
        return _state.identityRegistry[entity] != bytes32(0) && primeIndex <= _state.lastPrimeIndex;
    }

    function getPrimeGates() external view returns (uint256[] memory) {
        return _state.primeGates;
    }

    function calculateDrift(bytes32 a, bytes32 b) public view returns (uint256) {
        uint256[2] memory inputs;
        inputs[0] = uint256(a);
        inputs[1] = uint256(b);
        return poseidon.hashToField(inputs) % MAX_DRIFT;
    }

    function _isCertifiedPrime(uint256 n) internal pure returns (bool) {
        if (n <= 1) return false;
        if (n <= 3) return true;
        if (n % 2 == 0 || n % 3 == 0) return false;
        uint256 i = 5;
        uint256 w = 2;
        while (i * i <= n) {
            if (n % i == 0) return false;
            i += w;
            w = 6 - w;
        }
        return true;
    }
}
