[package]
name = "uac"
version = "0.1.0"
edition = "2021"

[dependencies]
num-rational = "0.4"
num-integer = "0.1"
num-traits = "0.2"

[dev-dependencies]
# Kani is only needed for bounded model checking; it is a dev‑dependency.



[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)'] }
