#!/usr/bin/env bash
set -euo pipefail

# Run the Rust extraction binary to produce extracted.json
BIN="$(pwd)/engine/target/release/extract-constants"
if [[ ! -x "$BIN" ]]; then
  echo "Error: extraction binary $BIN not found or not executable" >&2
  exit 1
fi
"$BIN" > extracted.json

# Path to JSON produced by the extraction binary
JSON_FILE="$(pwd)/extracted.json"

# Ensure the JSON exists
if [[ ! -f "$JSON_FILE" ]]; then
  echo "Error: $JSON_FILE not found" >&2
  exit 1
fi

# Output Lean file
OUTPUT="src/Analytic/ExtractedValues.lean"

# Helper to extract a value from JSON using jq
jq_val() {
  jq -r ".${1}" "$JSON_FILE"
}

cat > "$OUTPUT" <<EOF
import Analytic.FloatModel
open FloatModel

/-! Auto‑generated constants from extracted.json -/

/-! Real certified bounds -/

def η_min : ℝ := $(jq_val η_min)

def C_bound : ℝ := $(jq_val C_bound)

def τ_star : ℝ := $(jq_val τ_star)

def K₀ : ℝ := $(jq_val K₀)

def A_param : ℝ := $(jq_val A_param)

def T₀ : ℝ := $(jq_val T₀)

def some_positive_term : ℝ := $(jq_val some_positive_term)

def δ_pos : ℝ := $(jq_val δ_pos)

def hK₀ : Bool := $(jq_val hK₀)

/-! End of autogenerated constants -/
EOF

echo "Generated $OUTPUT from $JSON_FILE"
