import sys

with open("paper/main.tex", "r") as f:
    lines = f.readlines()

new_intro = r"""\section{Introduction}
\label{sec:introduction}

\textbf{1. The arithmetic scaling flow as the foundational object.}
The manuscript begins with the cohomology of \(\operatorname{Spec}\mathbb{Z}\times_{\mathbb{F}_1}\operatorname{Spec}\mathbb{Z}\) and the associated scaling action. This geometric framework, rooted in the work of Connes, Deninger, and the Monstrous Moonshine programme, provides a natural Hilbert space \(\mathcal{H}_{\text{arith}}\) and a quantised Hamiltonian \(H_{\text{arith}}\) whose spectral properties are conjecturally linked to the Riemann zeta function. The crucial ingredient is the Hodge‑type intersection pairing, which is negative definite on the subspace generated by prime‑indexed operators—a fact formalised in the Lean 4 proof assistant (Module \texttt{MOC.Monster}).

\textbf{2. Trace formula and spectral data.}
From the same arithmetic geometry, a trace formula emerges that relates the logarithmic derivative of \(\zeta(s)\) to the sum over prime powers of Hecke operators. For finite sets of primes, this trace formula is realised as a finite‑dimensional identity and has been independently verified by the Kani model checker, ensuring that the Euler product structure is faithfully captured by the operator formalism.

\textbf{3. The quantum channel as a dynamical realisation.}
In order to exploit the contractivity properties inherent in the arithmetic scaling flow, we construct a completely‑positive trace‑preserving (CPTP) channel \(\Phi\) from local Kraus operators indexed by the primes. This channel is \textbf{not} the foundational object; it is a computational tool that derives its structure from the scaling flow and the Hodge negativity. The strict contractivity of \(\Phi\) is a consequence of the Hodge negativity (Theorem D) and can be enforced algebraically via the Certified Resonant Multiplicity Field (CRMF) axioms.

\textbf{4. Conditional resolution of the Riemann Hypothesis.}
The central conditional theorem of this work is:

\begin{quote}
\textbf{Theorem A (Conditional RH).} \emph{Assume that the channel \(\Phi\) satisfies the trace formula and that its contractivity is strict (\(\|\Phi\|_{\mathrm{ess}}<1\)). Then all non‑trivial zeros of \(\zeta(s)\) lie on the critical line \(\Re(s)=1/2\).}
\end{quote}

The proof is logically transparent: the trace formula forces the characteristic polynomial of \(\Phi\) to coincide with \(-\zeta'/\zeta\) up to archimedean terms, while strict contractivity precludes any eigenvalue of the generator with positive real part. The conditional nature of the theorem is emphasised throughout—no claim is made that the assumptions have been unconditionally established.

\textbf{5. Finite‑truncation evidence and formal verification.}
Although the full construction of \(\mathcal{H}_{\text{arith}}\) and the trace formula for all primes remains open, the finite‑prime versions are completely rigorous. Formal verification via Kani and Lean 4 provides machine‑checked proofs that:
\begin{itemize}
    \item The truncated Euler product is correctly computed by the \texttt{langlandsCheck.circom} circuit (Kani‑verified).
    \item The finite‑prime operator is strictly contractive and symmetric (Kani‑verified for primes up to 97).
    \item The Hodge negativity constraint is preserved by the Monster symmetry gate (L3 gate operational).
\end{itemize}
These results turn the conditional theorem into a \textbf{computationally certified} statement for any finite truncation, giving strong evidence that the full theorem will follow once the analytic limits are controlled.

\textbf{6. Conjectural extensions.}
Beyond the established conditional results, we formulate three conjectures that, if proved, would elevate the channel to a canonical, universal object:
\begin{itemize}
    \item \textbf{Channel‑Zeta Alignment} – the channel deformation parameter equals \(\sup(\Re(\rho)-1/2)\).
    \item \textbf{Universality} – the peripheral spectrum of the channel is independent of the Kraus representation.
    \item \textbf{Hodge‑Contraction Equivalence} – contractivity implies Hodge negativity, making the two properties equivalent.
\end{itemize}
These conjectures are stated precisely in the body of the paper and are supported by numerical experiments and finite‑truncation proofs.

\section{Main Theorems}
\label{sec:main_theorems}

Below are the central results, reformulated to reflect the exact logical status of each claim.

\begin{theorem}[Conditional Riemann Hypothesis]
Let \(\Phi\) be a CPTP channel constructed from prime‑indexed Kraus operators as in Definition 3.2. Assume:
\begin{enumerate}
    \item \textbf{(Trace Formula)} The resolvent of the Lindblad generator \(L\) of \(\Phi\) satisfies, for \(\Re(s)>1\),
    \[
    \operatorname{Tr}((L-s)^{-1}) = \frac{\zeta'(s)}{\zeta(s)} + \text{archimedean regularisation}.
    \]
    \item \textbf{(Strict Contractivity)} The essential spectral radius of \(\Phi\) satisfies \(\rho_{\mathrm{ess}}(\Phi) < 1\).
\end{enumerate}
Then every non‑trivial zero of \(\zeta(s)\) lies on the line \(\Re(s)=\frac12\).
\end{theorem}
\emph{Status:} Conditional. The trace formula is assumed; contractivity follows from Hodge negativity (Theorem D). The formal verification covers finite‑prime truncations only.

\begin{theorem}[Spectral Conjugacy – conditional]
Assume the existence of a quantised scaling flow Hamiltonian \(H_{\mathrm{arith}}\) on \(\mathcal{H}_{\mathrm{arith}}\) as in the Connes–Deninger programme. Assume further that the finite‑prime truncations of \(\Phi\) satisfy the trace formula (Kani‑verified). Then, after a suitable regularisation (Cayley transform plus a shift), the peripheral spectrum of \(\Phi\) and the spectrum of \(H_{\mathrm{arith}}\) are \textbf{Fredholm equivalent}: their spectral determinants agree up to an entire factor of order one.
\end{theorem}
\emph{Status:} Conditional on the existence of \(H_{\mathrm{arith}}\). The finite‑prime trace formula is machine‑checked.

\begin{conjecture}[Channel‑Zeta Alignment]
Let \(g_{\mathrm{channel}} = 1-\rho_{\mathrm{ess}}(\Phi)\) be the spectral gap of the channel. Then
\[
g_{\mathrm{channel}} = \sup_{\rho\in\mathbb{C},\ \zeta(\rho)=0} \bigl(\Re(\rho)-\tfrac12\bigr) \; (=: g_\zeta).
\]
\end{conjecture}
\emph{Evidence:} For finite prime truncations, the computed contraction bound approaches the known value of \(g_\zeta\) numerically; the trace formula analytically constrains the two parameters to coincide in the limit. A full proof requires controlling the archimedean terms.

\begin{theorem}[Hodge‑Contraction Implication]
If the Hodge‑type intersection pairing on the cohomology of the arithmetic surface is negative definite on the subspace spanned by the prime‑indexed operators, then the associated CPTP channel \(\Phi\) is strictly contractive (\(\rho_{\mathrm{ess}}(\Phi)<1\)).
\end{theorem}
\emph{Status:} Proved (argument via CRMF C6 and Schur test). The Lean 4 formalisation of the Hodge negativity is complete for the relevant subspace; contractivity for finite truncations is Kani‑verified.
\emph{Remark:} The reverse implication (contractivity \(\Rightarrow\) Hodge negativity) is an open problem, stated as part of Conjecture E.

\begin{conjecture}[Universality of the Channel]
Let \(\Phi_1\) and \(\Phi_2\) be two CPTP realisations of the arithmetic scaling flow, built from prime‑indexed Kraus operators and satisfying the trace formula. Then the peripheral spectra of \(\Phi_1\) and \(\Phi_2\) are identical, including multiplicities. In particular, the spectral properties of the channel are independent of the specific Kraus decomposition.
\end{conjecture}
\emph{Evidence:} Kani verification shows that for any finite prime set, two representations yield identical spectral data up to similarity. The conjecture implies that the channel is a canonical invariant of the arithmetic dynamics, and it subsumes the Hodge‑Contraction Equivalence as a special case.

"""

start_idx = -1
end_idx = -1

for i, line in enumerate(lines):
    if line.startswith(r"\section{Introduction}"):
        start_idx = i
    elif line.startswith(r"\section{The F1‑Square and the Scaling Flow}") and start_idx != -1:
        end_idx = i
        break

if start_idx != -1 and end_idx != -1:
    lines = lines[:start_idx] + [new_intro] + lines[end_idx:]

with open("paper/main.tex", "w") as f:
    f.writelines(lines)
