#!/usr/bin/env python3
"""PIRTM Audit Tool: pirtm audit <trace.log>

Reads an audit trail (JSONL) and prints a human-readable summary.

Usage:
  pirtm audit trace.log

The trace log is generated by the audit trail system in the runtime and
transpiler. Each line is a JSON object representing a single audit event.

This tool is part of the ADR-023 Audit Trail Enforcer.
"""

import argparse
import json
from pathlib import Path
import sys


def format_event(event: dict) -> str:
    """Format a single audit event for human output."""
    ts = event.get("timestamp", "<no-timestamp>")
    stage = event.get("stage", "<stage>")
    comp = event.get("component", "<component>")
    evt = event.get("event", "<event>")
    details = event.get("details", {})

    detail_pairs = []
    for k, v in sorted(details.items()):
        detail_pairs.append(f"{k}={v}")

    details_str = "; ".join(detail_pairs)

    return f"[{ts}] {stage}/{comp}::{evt} -- {details_str}"


def main(argv=None) -> int:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="PIRTM audit log viewer (ADR-023 Audit Trail Enforcer)"
    )
    parser.add_argument("trace_log", help="Path to audit trace log (JSONL)")
    parser.add_argument(
        "--limit",
        type=int,
        default=0,
        help="Limit number of events printed (0 = all)",
    )
    args = parser.parse_args(argv)

    path = Path(args.trace_log)
    if not path.exists():
        print(f"Error: File not found: {path}", file=sys.stderr)
        return 1

    try:
        with open(path, "r", encoding="utf-8") as f:
            for idx, line in enumerate(f):
                line = line.strip()
                if not line:
                    continue
                try:
                    event = json.loads(line)
                except json.JSONDecodeError as e:
                    print(f"Invalid JSON on line {idx+1}: {e}", file=sys.stderr)
                    continue

                print(format_event(event))

                if args.limit > 0 and idx + 1 >= args.limit:
                    break
    except Exception as e:
        print(f"Error reading audit trail: {e}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
