import { useEffect, useMemo, useRef, useState } from "react";
import {
  CompiledArchive,
  loadSessionMeta,
  KnownModelStatus,
  cancelGeneration,
  generate,
  listCompiledArchives,
  listKnownModels,
  onProcessLine,
} from "../ipc";
import { countTokens } from "../holo";
import { MessageBody } from "../components/MessageBody";

interface Message {
  role: "user" | "assistant";
  text: string;
}

// Strip tokenizer special tokens (e.g. `<|im_end|>`, `<|endoftext|>`),
// turn `<br>` into newlines, drop stray HTML tags, and remove the CLI's
// trailing benchmark summary line before display. Models occasionally
// surface these in their output; the raw stream is still preserved in
// the Logs tab.
//
// Special-token regex matches any of `<|name|>`, `<|name|`, `<|name` — the
// CLI's stop-string detection often cuts the trailing `>` (and sometimes
// the trailing `|`) before suppressing emission, so the truncated forms
// still show up in the streamed text. Restricting the body to
// `[A-Za-z0-9_]` avoids chewing up unrelated `<|` sequences from user
// content.
//
// HTML-tag stripping kicks in *outside* fenced code blocks. Base
// (non-instruct) models tend to regurgitate scraped HTML (`<div …>`,
// `<a href=…>`, `</p>`) which clutters the bubble; legitimate HTML inside
// triple-backtick code blocks is preserved so users can ask "show me an
// `<input>`" and still see the markup.
//
// Stats-line regex matches the CLI's `\n\n[N tokens | TTFT Xms | decode N
// tok in Xs (Xtok/s) | weights X GiB]` footer. Leaving it in would both
// clutter the bubble *and* be replayed verbatim into the next multi-turn
// prompt as part of the prior assistant message.
function cleanAssistantText(s: string): string {
  let out = s;
  out = out.replace(/<\|[A-Za-z0-9_]*\|?>?/g, "");
  out = out.replace(/<br\s*\/?>/gi, "\n");
  out = stripHtmlOutsideCodeBlocks(out);
  out = stripBaseModelArtifactsOutsideCodeBlocks(out);
  out = out.replace(/\n*\[\d+ tokens \| TTFT[^\]\n]*\]\s*$/g, "");
  return out.trimEnd();
}

// Split the text on triple-backtick fences (and `~~~` fences) so that
// HTML/XML tags inside fenced code blocks are left intact, while tags in
// prose are stripped. Odd-indexed segments are the fenced blocks
// themselves (preserved verbatim).
function stripHtmlOutsideCodeBlocks(s: string): string {
  const parts = s.split(/(```[\s\S]*?```|~~~[\s\S]*?~~~)/g);
  const tagPattern = /<\/?[A-Za-z][A-Za-z0-9-]*(?:\s+[^<>]*)?\/?>/g;
  return parts
    .map((part, i) => (i % 2 === 1 ? part : part.replace(tagPattern, "")))
    .join("");
}

// Strip a few classes of training-data leakage that base (non-instruct)
// models tend to emit. None of these are valid markdown, none are
// generated by chat-tuned models in normal use, and all of them clutter
// the bubble. Code fences are preserved as-is.
//   - `\start\foo{...}\endfoo`   — Jupyter notebook export markers
//   - `\start\foo{...}\endfoo>`  — same, with stray angle bracket
//   - `\command{...}`            — bare LaTeX-style commands that aren't
//                                    inside an actual `$…$` math block
//   - stray closing `>` with no matching `<` on the line
function stripBaseModelArtifactsOutsideCodeBlocks(s: string): string {
  const parts = s.split(/(```[\s\S]*?```|~~~[\s\S]*?~~~|\$\$[\s\S]*?\$\$|\$[^\n$]+\$)/g);
  return parts
    .map((part, i) => {
      if (i % 2 === 1) return part;
      let p = part;
      p = p.replace(/\\start\\[A-Za-z]+\{[^}]*\}\\end[A-Za-z]+>?/g, "");
      p = p.replace(/(^|\s)\\[A-Za-z]+\{[^}]*\}/g, "$1");
      p = p.replace(/(^|\s)>+(\s|$)/g, "$1$2");
      return p;
    })
    .join("");
}

// Generic "between turns" separator for archives that aren't matched against
// any catalogue entry. The plain `User:` / `Assistant:` labelling is a format
// most chat-tuned models recognise even when their canonical template uses
// different delimiters — it gives us memory by default rather than no memory.
const GENERIC_TURN_SEPARATOR = "\n\nAssistant: {response}\n\nUser: ";

// Build the `{prompt}` slot for a multi-turn conversation. The compile-time
// prompt template wraps the *outer* user/assistant turn; we inject prior
// turns inside the slot using `separator` (which carries `{response}`
// substituted with the prior assistant message).
//
// `messages` contains every prior user+assistant pair *plus* the new pending
// user message at the tail. With only the pending message (no history),
// this returns just the user text — same as a single-turn prompt.
function buildMultiTurnPrompt(messages: Message[], separator: string): string {
  if (messages.length === 0) return "";
  if (messages.length === 1) return messages[0].text;
  // Pair off prior user/assistant turns. A trailing user message without a
  // matching assistant reply is the *new* turn the model is about to answer.
  const parts: string[] = [];
  for (let i = 0; i + 1 < messages.length; i += 2) {
    const u = messages[i];
    const a = messages[i + 1];
    if (u.role !== "user" || a.role !== "assistant") {
      // Out-of-order — fall back to single-turn rather than emit nonsense.
      return messages[messages.length - 1].text;
    }
    parts.push(u.text);
    parts.push(separator.replace("{response}", a.text));
  }
  // Final pending user turn (the message we're about to send).
  const last = messages[messages.length - 1];
  if (last.role !== "user") return messages[messages.length - 1].text;
  parts.push(last.text);
  return parts.join("");
}

// Resolve which catalogue entry (if any) corresponds to the selected
// archive path, by matching the archive's filename stem against the
// catalogue id, or its parent dir against the model's HF repo name.
function findKnownModel(
  archivePath: string,
  known: KnownModelStatus[],
): KnownModelStatus | undefined {
  const lower = archivePath.toLowerCase();
  return known.find((m) => {
    if (m.compiledArchive && m.compiledArchive === archivePath) return true;
    if (lower.includes(`/${m.id.toLowerCase()}.holo`)) return true;
    const repoName = m.hfId.split("/").pop()?.toLowerCase();
    if (repoName && lower.includes(`/${repoName}/`)) return true;
    return false;
  });
}

export function Chat() {
  const [archives, setArchives] = useState<CompiledArchive[]>([]);
  const [archive, setArchive] = useState<string>("");
  const [knownModels, setKnownModels] = useState<KnownModelStatus[]>([]);
  const [prompt, setPrompt] = useState("");

  const [temperature, setTemperature] = useState(0.7);
  const [running, setRunning] = useState(false);
  const [messages, setMessages] = useState<Message[]>([]);
  const [sessionMeta, setSessionMeta] = useState<{ contextLength: number | null; tokenizer?: Uint8Array } | null>(null);
  // Narration of the work behind the first token (window compiles, stage
  // materialization) — shown in the streaming placeholder so a large model's
  // honest startup is visible, never a silent hang.
  const [genStatus, setGenStatus] = useState("");
  const transcriptRef = useRef<HTMLDivElement>(null);
  const streamingRef = useRef<string>("");

  useEffect(() => {
    listCompiledArchives().then((a) => {
      setArchives(a);
      if (a.length && !archive) setArchive(a[0].path);
    });
    listKnownModels().then(setKnownModels);
  }, []);

  // Load the model's own context window + tokenizer once per archive (never in
  // the send hot path). This is what bounds the session — the model's limits.
  useEffect(() => {
    if (!archive) {
      setSessionMeta(null);
      return;
    }
    let live = true;
    loadSessionMeta(archive)
      .then((m) => {
        if (live) setSessionMeta(m);
      })
      .catch(() => {
        if (live) setSessionMeta(null);
      });
    return () => {
      live = false;
    };
  }, [archive]);

  const selectedKnown = useMemo(
    () => (archive ? findKnownModel(archive, knownModels) : undefined),
    [archive, knownModels],
  );
  const turnSeparator =
    selectedKnown?.chatTurnSeparator ?? GENERIC_TURN_SEPARATOR;

  // Subscribe to chat lines once.
  useEffect(() => {
    let timeoutId: number | null = null;
    let isFlushing = false;
    
    const flushText = () => {
      if (!isFlushing) return;
      isFlushing = false;
      
      setMessages((prev) => {
        const last = prev[prev.length - 1];
        if (last && last.role === "assistant") {
          const updated = [...prev];
          updated[updated.length - 1] = { role: "assistant", text: streamingRef.current };
          return updated;
        }
        return [...prev, { role: "assistant", text: streamingRef.current }];
      });
    };

    const unlistenStatus = onProcessLine("chat://status", (l) => {
      if (l.stream === "stderr") return;
      setGenStatus(l.line);
    });
    const unlisten = onProcessLine("chat://line", (l) => {
      if (l.stream === "stderr") return;
      if (l.line) setGenStatus("");
      // Each event is a cumulative SNAPSHOT of the whole completion so far
      // (the generation loop re-decodes the full token sequence each step for
      // correct BPE spacing) — replace, never append: appending garbles the
      // stored turn and poisons every subsequent multi-turn prompt.
      streamingRef.current = l.line;

      if (!isFlushing) {
        isFlushing = true;
        timeoutId = window.setTimeout(flushText, 50);
      }
    });
    
    return () => {
      unlisten.then((un) => un());
      unlistenStatus.then((un) => un());
      if (timeoutId !== null) window.clearTimeout(timeoutId);
    };
  }, []);

  useEffect(() => {
    transcriptRef.current?.scrollTo({
      top: transcriptRef.current.scrollHeight,
      behavior: "smooth",
    });
  }, [messages]);

  async function onSend() {
    if (!archive || !prompt.trim() || running) return;
    const userText = prompt.trim();
    // Build the full transcript (cleaned assistant turns + new user turn) so
    // the model sees the conversation history. We clean assistant text to
    // strip leaked special tokens *before* feeding it back, otherwise stray
    // `<|im_end|>`/`</s>` would terminate the next turn early.
    const history: Message[] = [
      ...messages.map((m) =>
        m.role === "assistant"
          ? { role: "assistant" as const, text: cleanAssistantText(m.text) }
          : m,
      ),
      { role: "user", text: userText },
    ];
    // Session trimming (row session-window): the model's own context is the
    // only limit — a transcript that outgrows it drops oldest turn pairs so
    // the conversation continues rather than dead-ending. Uses the model's
    // own context + tokenizer, loaded once when the archive is selected
    // (`sessionMeta`) — never OPFS/wasm in the click hot path.
    let workingHistory = history;
    let promptForModel = buildMultiTurnPrompt(workingHistory, turnSeparator);
    const ctx = sessionMeta?.contextLength ?? null;
    const tok = sessionMeta?.tokenizer;
    if (ctx && tok) {
      const applyTemplate = (t: string | null | undefined, slot: string) =>
        t ? (t.includes("{prompt}") ? t.replace("{prompt}", slot) : t + slot) : slot;
      try {
        let tokens = await countTokens(tok, applyTemplate(selectedKnown?.promptTemplate, promptForModel));
        while (tokens > ctx && workingHistory.length > 2) {
          workingHistory = workingHistory.slice(2); // oldest user+assistant pair
          promptForModel = buildMultiTurnPrompt(workingHistory, turnSeparator);
          tokens = await countTokens(tok, applyTemplate(selectedKnown?.promptTemplate, promptForModel));
        }
      } catch {
        // Counting unavailable: send untrimmed — the engine still fails loud
        // if the prompt exceeds the model's context.
      }
    }

    setMessages((prev) => [...prev, { role: "user", text: userText }]);
    setPrompt("");
    setRunning(true);
    streamingRef.current = "";
    // Stop strings: catalogue archives ship their native stop tokens
    // (e.g. Qwen2 ChatML's `<|im_end|>`); for non-catalogue / generic-
    // separator fallback, pass `\nUser:` / `\nAssistant:` so base models
    // can't keep writing fake turns past end-of-response.
    const stopStrings = selectedKnown?.stop?.length
      ? selectedKnown.stop
      : ["\nUser:", "\nAssistant:"];
    // Prompt template: templates are no longer baked into the `.holo` at
    // compile time, so we forward the catalogue's `prompt_template`
    // (containing `{prompt}`) every run. The CLI substitutes our
    // multi-turn `promptForModel` into the `{prompt}` slot.
    try {
      await generate({
        archive,
        prompt: promptForModel,
        // No fixed cap: absent an explicit per-model setting, generation is
        // bounded by stop conditions, the remaining context, and Cancel.
        maxTokens: selectedKnown?.maxTokens,
        temperature,
        stop: stopStrings,
        promptTemplate: selectedKnown?.promptTemplate ?? undefined,
      });
      // Commit the final streamed text SYNCHRONOUSLY: the token stream's
      // debounced flush may still be pending, and the next turn's history
      // is built from `messages` — a turn sent inside that 50 ms window
      // would otherwise assemble its prompt one flush short (CI caught
      // turn-3 prompts missing the last characters of turn 2).
      setMessages((prev) => {
        const last = prev[prev.length - 1];
        if (last && last.role === "assistant" && last.text !== streamingRef.current) {
          const updated = [...prev];
          updated[updated.length - 1] = { role: "assistant", text: streamingRef.current };
          return updated;
        }
        if (last && last.role === "assistant") return prev;
        return [...prev, { role: "assistant", text: streamingRef.current }];
      });
      // Commit the final completion SYNCHRONOUSLY before the composer
      // re-enables: the streaming path batches transcript updates behind a
      // debounce, and a send that lands before the last flush would build
      // the next prompt from a truncated assistant turn (a real one-token
      // loss caught by the handshake reference gate in CI). The debounced
      // flush that follows writes identical content — idempotent.
      const finalText = streamingRef.current;
      if (finalText) {
        setMessages((prev) => {
          const last = prev[prev.length - 1];
          if (last && last.role === "assistant") {
            const updated = [...prev];
            updated[updated.length - 1] = { role: "assistant", text: finalText };
            return updated;
          }
          return [...prev, { role: "assistant", text: finalText }];
        });
      }
    } catch (e) {
      setMessages((prev) => [
        ...prev,
        { role: "assistant", text: `error: ${String(e)}` },
      ]);
    } finally {
      setRunning(false);
      setGenStatus("");
    }
  }

  async function onCancel() {
    await cancelGeneration();
  }

  function onResetChat() {
    if (running) return;
    setMessages([]);
    streamingRef.current = "";
  }

  return (
    <div className="page chat">
      <div className="page-header">
        <h1>Chat</h1>
        <div className="row">
          <select
            value={archive}
            onChange={(e) => setArchive(e.target.value)}
            disabled={running}
            style={{ minWidth: 260 }}
          >
            {archives.length === 0 && <option value="">No compiled archives</option>}
            {archives.map((a) => (
              <option key={a.path} value={a.path}>
                {a.name}
              </option>
            ))}
          </select>
          <input
            type="number"
            value={temperature}
            step={0.1}
            min={0}
            max={2}
            onChange={(e) => setTemperature(Number(e.target.value))}
            style={{ width: 70 }}
            disabled={running}
            title="temperature"
          />
          <button
            onClick={onResetChat}
            disabled={running || messages.length === 0}
            title="Clear conversation history"
          >
            New chat
          </button>
        </div>
      </div>

      <div className="transcript" ref={transcriptRef}>
        {messages.length === 0 ? (
          <div className="empty">Pick an archive and send a prompt.</div>
        ) : (
          messages.map((m, i) => {
            const text =
              m.role === "assistant" ? cleanAssistantText(m.text) : m.text;
            const isStreamingPlaceholder =
              !text && running && i === messages.length - 1;
            return (
              <div key={i} className={`bubble ${m.role}`}>
                <div className="role">{m.role}</div>
                {isStreamingPlaceholder ? (
                  <div className="md">{genStatus ? `${genStatus} …` : "…"}</div>
                ) : (
                  <MessageBody text={text} />
                )}
              </div>
            );
          })
        )}
      </div>

      <div className="composer">
        <textarea
          placeholder="Ask anything…  (Cmd/Ctrl+Enter to send)"
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) {
              e.preventDefault();
              onSend();
            }
          }}
          disabled={running || !archive}
        />
        {running ? (
          <button onClick={onCancel}>Cancel</button>
        ) : (
          <button onClick={onSend} disabled={!archive || !prompt.trim()}>
            Send
          </button>
        )}
      </div>
    </div>
  );
}
