/-!
# Foundations.CompletionAdjunction.Core — Free Universal Closure Completion

Constructs the free syntax magma with closure, partial relations congruence,
and the quotient setoid representing the free completion space $X^*$.
-/

namespace Foundations.CompletionAdjunction

/-- Partial Universal Closure structure. -/
structure PartialUC (X : Type u) where
  compose_p : X → X → Option X
  closure_p : X → Option X

/-- Free magma syntax tree generated by carrier elements, composition, and closure. -/
inductive UCTerm (X : Type u) where
  | var     : X → UCTerm X
  | compose : UCTerm X → UCTerm X → UCTerm X
  | close   : UCTerm X → UCTerm X

/-- Partial relation congruence on terms. -/
inductive UCCongruence {X : Type u} (P : PartialUC X) : UCTerm X → UCTerm X → Prop where
  | comp_lawful (x y z : X) :
      P.compose_p x y = some z →
      UCCongruence P (UCTerm.compose (UCTerm.var x) (UCTerm.var y)) (UCTerm.var z)
  | close_lawful (x y : X) :
      P.closure_p x = some y →
      UCCongruence P (UCTerm.close (UCTerm.var x)) (UCTerm.var y)
  | close_idempotent (t : UCTerm X) :
      UCCongruence P (UCTerm.close (UCTerm.close t)) (UCTerm.close t)
  | refl (t : UCTerm X) : UCCongruence P t t
  | symm (t₁ t₂ : UCTerm X) : UCCongruence P t₁ t₂ → UCCongruence P t₂ t₁
  | trans (t₁ t₂ t₃ : UCTerm X) :
      UCCongruence P t₁ t₂ → UCCongruence P t₂ t₃ → UCCongruence P t₁ t₃
  | comp_congr (t₁ t₁' t₂ t₂' : UCTerm X) :
      UCCongruence P t₁ t₁' → UCCongruence P t₂ t₂' →
      UCCongruence P (UCTerm.compose t₁ t₂) (UCTerm.compose t₁' t₂')
  | close_congr (t t' : UCTerm X) :
      UCCongruence P t t' → UCCongruence P (UCTerm.close t) (UCTerm.close t')

/-- Constructive Setoid on UCTerms. -/
def UCTerm.setoid {X : Type u} (P : PartialUC X) : Setoid (UCTerm X) where
  r := UCCongruence P
  iseqv := {
    refl := UCCongruence.refl
    symm := UCCongruence.symm _ _
    trans := UCCongruence.trans _ _ _
  }

/-- The Free Universal Completion Space $X^*$. -/
def FreeCompletion {X : Type u} (P : PartialUC X) : Type u :=
  Quotient (UCTerm.setoid P)

/-- Canonical embedding $\eta : X \to X^*$. -/
def embed {X : Type u} (P : PartialUC X) (x : X) : FreeCompletion P :=
  Quotient.mk (UCTerm.setoid P) (UCTerm.var x)

/-- Theorem: Embed is well-defined. -/
theorem embed_refl {X : Type u} (P : PartialUC X) (x : X) :
    embed P x = embed P x := rfl

end Foundations.CompletionAdjunction
