//! Rust port of the meta-theorem basis tooling.
//!
//! Ports three Python scripts that previously lived under
//! `crates/materia_commons/meta-theorem/` (removed after porting):
//!
//! * `export_basis.py` — enumerate the multiplicative basis generated by a
//!   prime list up to a maximum exponent and emit `basis_factors.json`,
//! * `gen_real_basis.py` — turn that JSON into `RealBasis.lean`
//!   (`SemanticArithmetic.RealBasis`: `primes`, `basisNumbers`,
//!   `basisValuations`, `N_states`, `valuationOf`),
//! * `generate_rust_vals.py` — turn the same JSON into a Rust static array for
//!   the Kani-proofed Hamiltonian.
//!
//! The three ports live in [`basis`], [`python_json`], [`lean`], and
//! [`rust_array`]. The JSON and codegen output are byte-identical to the
//! Python originals for the production basis (`primes = [2, 3, 5, 7]`,
//! `max_exp = 3`, 256 states) — see `tests/fidelity.rs`.

#![forbid(unsafe_code)]

pub mod basis;
pub mod lean;
pub mod model;
pub mod python_json;
pub mod rust_array;