// Sync the Hologram brand kit into src/brand/ at a PINNED revision.
//
// The kit (Hologram-Technologies/hologram-brand-kit, branch `develop`) is
// the single source of visual truth: its DTCG tokens generate
// brand/css/hologram-warm.css (the Hologram brand layer), and this script
// vendors that theme - namespaced and re-scoped for this app - plus the web
// fonts, the logomark and the wordmark. To update the brand everywhere:
//   1. bump KIT_REV below to a `develop` commit,
//   2. npm run sync:brand,
//   3. review the diff of src/brand/ and commit.
//
// Output is deterministic for a given KIT_REV: running the script twice
// produces no diff. No dependencies beyond Node 18+ (global fetch).
//
// Transformations applied to the kit CSS (mechanical, so the kit stays the
// source of truth):
//   - every custom property is namespaced: --background -> --holo-background
//     (the app's own semantic layer in styles.css uses colliding names);
//   - the kit's `:root` (light) block is re-scoped to
//     `:root[data-theme="light"]` and its `.dark` block to `:root`, because
//     this app is dark-by-default with a data-theme toggle;
//   - theme-independent tokens (radius, font stacks, tracking) live only in
//     the kit's light block, so copies are hoisted into a base `:root`.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const KIT_REPO = "Hologram-Technologies/hologram-brand-kit";
const KIT_REV = "bce3bdf59de120e125754bfaef437d18aca14673"; // develop, 2026-08-28

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "src", "brand");
mkdirSync(join(out, "fonts"), { recursive: true });

const RAW = `https://raw.githubusercontent.com/${KIT_REPO}/${KIT_REV}`;

async function fetchBytes(path) {
  const response = await fetch(`${RAW}/${path}`);
  if (!response.ok) throw new Error(`${path}: HTTP ${response.status}`);
  return Buffer.from(await response.arrayBuffer());
}
const fetchText = async (path) => (await fetchBytes(path)).toString("utf8");

const banner = (source) => `/* GENERATED by scripts/sync-brand.mjs - DO NOT EDIT.
 * Source: ${KIT_REPO}@${KIT_REV.slice(0, 12)}
 * File:   ${source}
 */\n\n`;

// ---- theme css: namespace + rescope + hoist ---------------------------
let theme = await fetchText("brand/css/hologram-warm.css");
theme = theme.replace(/--([a-z0-9-]+)/g, "--holo-$1");
theme = theme.replace(/^:root\s*\{/m, ':root[data-theme="light"] {');
theme = theme.replace(/^\.dark\s*\{/m, ":root {");
const hoisted = [...theme.matchAll(/^\s*(--holo-(?:radius|font-[a-z]+|tracking-[a-z]+)):\s*([^;]+);/gm)]
  .map(([, name, value]) => `  ${name}: ${value};`)
  .join("\n");
theme += `\n/* hoisted theme-independent tokens (sync-brand.mjs) */\n:root {\n${hoisted}\n}\n`;
writeFileSync(join(out, "theme.css"), banner("brand/css/hologram-warm.css") + theme);

// ---- tokens (reference copy for tooling and audits) -------------------
writeFileSync(join(out, "tokens.json"), await fetchText("brand/tokens/hologram-tokens.json"));

// ---- fonts ------------------------------------------------------------
const FONTS = [
  ["Geist-Regular.woff2", "Geist", 400],
  ["Geist-Medium.woff2", "Geist", 500],
  ["Geist-SemiBold.woff2", "Geist", 600],
  ["Geist-Bold.woff2", "Geist", 700],
  ["GeistMono-Regular.woff2", "Geist Mono", 400],
  ["GeistMono-Medium.woff2", "Geist Mono", 500],
  ["Archivo-Medium.woff2", "Archivo", 500],
  ["Archivo-SemiBold.woff2", "Archivo", 600],
  ["Archivo-Bold.woff2", "Archivo", 700],
];
let fontCss = banner("brand/fonts/web/* (SIL OFL 1.1, see brand/fonts/OFL*.txt)");
for (const [file, family, weight] of FONTS) {
  writeFileSync(join(out, "fonts", file), await fetchBytes(`brand/fonts/web/${file}`));
  fontCss += `@font-face {
  font-family: "${family}";
  src: url("./fonts/${file}") format("woff2");
  font-weight: ${weight};
  font-style: normal;
  font-display: swap;
}\n`;
}
writeFileSync(join(out, "fonts.css"), fontCss);

// ---- marks ------------------------------------------------------------
for (const [src, dst] of [
  ["brand/logos/svg/logomark/Hologram_Logomark_White.svg", "logomark-white.svg"],
  ["brand/logos/svg/logomark/Hologram_Logomark_Black.svg", "logomark-black.svg"],
  ["brand/logos/svg/wordmark/Hologram_Wordmark_White.svg", "wordmark-white.svg"],
  ["brand/logos/svg/wordmark/Hologram_Wordmark_Black.svg", "wordmark-black.svg"],
]) {
  writeFileSync(join(out, dst), await fetchBytes(src));
}

// ---- application icon ---------------------------------------------------
// The app icon is the kit's white logomark on the brand layer's dark ground,
// composed here so it re-derives with the kit. Tauri regenerates the platform
// icon set from it: `npx tauri icon icon.svg` (run from apps/desktop).
{
  const logomark = (await fetchText("brand/logos/svg/logomark/Hologram_Logomark_White.svg"))
    .replace(/<title>[^<]*<\/title>\s*/, "");
  const inner = logomark.match(/<svg[^>]*>([\s\S]*)<\/svg>/)?.[1]?.trim();
  if (!inner) throw new Error("logomark: unexpected SVG shape");
  const ground = theme.match(/^:root \{[\s\S]*?--holo-background:\s*(#[0-9a-f]{6})/m)?.[1];
  if (!ground) throw new Error("theme: dark --holo-background not found");
  // 1024 tile, 22% corner radius; the 208-unit logomark fills 68% of the side.
  const scale = ((1024 * 0.68) / 208).toFixed(4);
  const icon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" role="img" aria-label="Hologram">
<title>Hologram</title>
<rect width="1024" height="1024" rx="225" fill="${ground}"/>
<g transform="translate(512 512) scale(${scale})">
${inner}
</g>
</svg>
`;
  writeFileSync(join(here, "..", "icon.svg"), icon);
}

console.log(`brand synced from ${KIT_REPO}@${KIT_REV.slice(0, 12)} into src/brand/`);
