//! Euclidean arithmetic operations.
//!
//! Implements:
//! - Integer classification (unit, number, prime, composite)
//! - Trial-division prime factorization
//! - Euclidean Non-Closure: for any finite set S of primes,
//!   there exists a new prime q dividing N_S = ∏p∈S p + 1

use super::types::{DivisorPoset, Factorization, IntegerClass, MultiplicityProfile};

/// Classify an integer n > 0 into the Euclidean hierarchy.
///
/// # Invariant
///
/// Every positive integer falls into exactly one class.
pub fn classify(n: u64) -> IntegerClass {
    match n {
        0 => unreachable!("classify requires n > 0"),
        1 => IntegerClass::Unit,
        _ => {
            if is_prime(n) {
                IntegerClass::Prime
            } else {
                IntegerClass::Composite
            }
        }
    }
}

/// Trial-division primality test.  Sound for all u64 values.
pub fn is_prime(n: u64) -> bool {
    match n {
        0 | 1 => false,
        2 | 3 => true,
        _ if n % 2 == 0 => false,
        _ => {
            let mut p = 3u64;
            while p * p <= n {
                if n % p == 0 {
                    return false;
                }
                p += 2;
            }
            true
        }
    }
}

/// Prime factorization via trial division.
///
/// Returns `None` if n = 0 or n = 1 (no prime factors).
pub fn factorize(n: u64) -> Option<Factorization> {
    match n {
        0 | 1 => None,
        _ => {
            let mut factors = Vec::new();
            let mut temp = n;
            let mut p = 2u64;
            while p * p <= temp {
                if temp % p == 0 {
                    let mut count = 0u64;
                    while temp % p == 0 {
                        temp /= p;
                        count += 1;
                    }
                    factors.push((p, count));
                }
                p += 1;
            }
            if temp > 1 {
                factors.push((temp, 1));
            }
            Some(Factorization::new(factors))
        }
    }
}

/// Compute the full multiplicity profile of n.
///
/// Returns `None` for n = 0 or n = 1 (no meaningful factorization).
pub fn profile(n: u64) -> Option<MultiplicityProfile> {
    let factorization = factorize(n)?;
    let class = classify(n);
    let divisor_poset = DivisorPoset::new(n);
    let tau = factorization.tau();
    let sigma = factorization.sigma();
    let omega = factorization.omega();
    let big_omega = factorization.big_omega();
    Some(MultiplicityProfile {
        n,
        class,
        factorization,
        divisor_poset,
        tau,
        sigma,
        omega,
        big_omega,
    })
}

/// Find a prime q ∉ S that divides N_S = ∏p∈S p + 1.
///
/// **Euclidean Non-Closure Principle (ADR-0004 §XII):**
/// For any finite set S of primes, the system generated by S cannot
/// contain all of its own irreducible generators.
///
/// Returns `None` only if S is empty (degenerate case) or if N_S = 1
/// (also degenerate).
pub fn euclid_nonclosure(s: &[u64]) -> Option<u64> {
    if s.is_empty() {
        return None;
    }
    let product: u64 = s.iter().product();
    let n_s = product + 1;
    if n_s <= 1 {
        return None;
    }
    // Find any prime factor of N_S that is not in S.
    let factors = factorize(n_s)?;
    for (p, _) in factors.factors {
        if !s.contains(&p) {
            return Some(p);
        }
    }
    None
}

/// Compute τ(n) = ∏(a_i + 1) from prime factorization.
pub fn tau_from_factorization(factors: &[(u64, u64)]) -> u64 {
    factors.iter().map(|(_, a)| a + 1).product()
}

/// Compute ω(n) = number of distinct prime factors.
pub fn omega_from_factorization(factors: &[(u64, u64)]) -> usize {
    factors.len()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn classify_unit() {
        assert_eq!(classify(1), IntegerClass::Unit);
    }

    #[test]
    fn classify_primes() {
        assert_eq!(classify(2), IntegerClass::Prime);
        assert_eq!(classify(3), IntegerClass::Prime);
        assert_eq!(classify(17), IntegerClass::Prime);
    }

    #[test]
    fn classify_composites() {
        assert_eq!(classify(4), IntegerClass::Composite);
        assert_eq!(classify(60), IntegerClass::Composite);
    }

    #[test]
    fn factorize_small() {
        let f = factorize(60).unwrap();
        assert_eq!(f.factors, vec![(2, 2), (3, 1), (5, 1)]);
    }

    #[test]
    fn factorize_prime() {
        let f = factorize(17).unwrap();
        assert_eq!(f.factors, vec![(17, 1)]);
    }

    #[test]
    fn profile_60() {
        let p = profile(60).unwrap();
        assert_eq!(p.tau, 12);
        assert_eq!(p.sigma, 168);
        assert_eq!(p.omega, 3);
        assert_eq!(p.big_omega, 4);
    }

    #[test]
    fn euclid_nonclosure_small() {
        // S = {2, 3}, N_S = 7, 7 is prime and 7 ∉ {2, 3}
        let q = euclid_nonclosure(&[2, 3]).unwrap();
        assert_eq!(q, 7);
    }

    #[test]
    fn euclid_nonclosure_composite() {
        // S = {2, 3, 5}, N_S = 31, prime
        let q = euclid_nonclosure(&[2, 3, 5]).unwrap();
        assert_eq!(q, 31);
    }

    #[test]
    fn divisor_poset_12() {
        let poset = DivisorPoset::new(12);
        let values: Vec<u64> = poset.nodes.iter().map(|n| n.value).collect();
        assert_eq!(values, vec![1, 2, 3, 4, 6, 12]);
    }

    #[test]
    fn tau_formula_360() {
        let f = Factorization::new(vec![(2, 3), (3, 2), (5, 1)]);
        assert_eq!(tau_from_factorization(&f.factors), 24);
        assert_eq!(f.tau(), 24);
    }
}
