import { ADR, ADRRegistry, ADRStatus } from './adr-types';

export const FOUNDRY_ADR_SETS: Record<string, ADR[]> = {
  core: [
    {
      id: 'ADR-001',
      title: 'Integer Jordan Bond Governance',
      status: 'Superseded',
      context: 'Floating-point non-determinism introduces drift and spoliation risk in state transitions across distributed nodes.',
      decision: 'Enforce fixed-point integer Jordan bond arithmetic scaled by N = 1024 at the kernel boundary.',
      consequences: ['Arithmetic determinism guaranteed across heterogeneous nodes', 'Floating point drift strictly eliminated'],
      supersedes: null,
      links: [
        { uri: 'PhaseMirror.Care.Scale', kind: 'LeanDeclaration', description: 'Canonical fixed-point scale N = 1024' },
        { uri: 'Care.lean', kind: 'SourceFile', description: 'Integer fixed-point operations' },
      ],
    },
    {
      id: 'ADR-002',
      title: 'Sedona Spine Retention Engine Sole Source of Truth',
      status: 'Accepted',
      context: 'Decentralized litigation hold rules risk spoliation drift if computed independently by UI or client agents.',
      decision: 'All ESI preservation risk logic must route exclusively through the Sedona Spine Rust Engine and WASM SDK.',
      consequences: ['Zero drift in litigation hold calculations', 'Mandatory provenance chain: Policy → Event → Kernel → Witness'],
      supersedes: null,
      links: [
        { uri: 'models/legalese-scopist/CONTRACT.md', kind: 'SpecificationDoc', description: 'Preservation alert protocol' },
        { uri: 'models/legalese-scopist/', kind: 'SourceFile', description: 'Rust Engine Core implementation' },
      ],
    },
    {
      id: 'ADR-003',
      title: 'Per-Triad Resonance Floors (Audit v2)',
      status: 'Accepted',
      context: 'Aggregate mean resonance floor in ADR-001 permitted averaging blind spots where individual triads could fall below viability.',
      decision: 'Strengthen viability audit to require every individual triad to meet or exceed ResFloor = 870.',
      consequences: ['Eliminates averaging blind spot proved by averaging_blind_spot theorem', 'Preserves backward compatibility with audit v1'],
      supersedes: null,
      links: [
        { uri: 'ADR/Theorems/CareViability.lean', kind: 'SourceFile', description: 'Formalization of v2 thresholds' },
        { uri: 'PhaseMirror.CareViability.phase_mirror_audit_v2', kind: 'LeanDeclaration', description: 'Per-triad binary audit' },
      ],
    },
    {
      id: 'ADR-004',
      title: 'Meet-Semilattice Partition Refinement & LCR Operator',
      status: 'Accepted',
      context: 'SPMD distributed execution requires a formal refinement order over tensor sharding states.',
      decision: 'Enforce pointwise meet operator (⊓) over logical mesh axes with idempotent, associative, commutative semantics.',
      consequences: ['Deterministic least common refinement across distributed execution paths', 'Fail-closed immediate rejection of conflicting sharding schedules'],
      supersedes: null,
      links: [
        { uri: 'specs/p2c_petc_v12.md', kind: 'SpecificationDoc', description: 'P²C PETC v1.2 Specification Section 2.3' },
        { uri: 'packages/rust/pirtm-compiler/src/sharding.rs', kind: 'SourceFile', description: 'LCR Meet Operator Implementation' },
      ],
    },
    {
      id: 'ADR-005',
      title: 'BLAKE2b-16 Personalization & Canonical Bytecode Wire Format',
      status: 'Accepted',
      context: 'Witness bytecode streams require compact, tamper-evident framing with low verification overhead.',
      decision: 'Standardize binary wire format on header magic P2CWITv2, version 0x0102, LEB128/ZigZag varints, trailer 0xAA 0x55.',
      consequences: ['Bit-flip and truncation detection at frame boundary', 'Allocation-free stack-based decoding in high-performance runtimes'],
      supersedes: null,
      links: [
        { uri: 'specs/p2c_petc_v12.md', kind: 'SpecificationDoc', description: 'P²C PETC v1.2 Binary Wire Format Section 3' },
        { uri: 'packages/rust/core/src/petc.rs', kind: 'SourceFile', description: 'Bytecode Frame Parser' },
      ],
    },
    {
      id: 'ADR-006',
      title: 'MultiContract Atomic Contraction with PartialSum Tokens',
      status: 'Accepted',
      context: 'Contraction over sharded tensor dimensions produces partial sums requiring explicit collective reductions.',
      decision: 'Standardize opcode 0x05 (MultiContract) to atomically verify dual signatures and emit PartialSum(mesh_axis) tokens.',
      consequences: ['Prevents unreduced partial sum escapes in SPMD graphs', 'Simultaneous atomic multi-axis tensor contractions in O(k) time'],
      supersedes: null,
      links: [
        { uri: 'specs/p2c_petc_v12.md', kind: 'SpecificationDoc', description: 'P²C PETC v1.2 Opcode Semantics Section 4' },
        { uri: 'packages/rust/engine/src/petc.rs', kind: 'SourceFile', description: 'MultiContract Evaluator' },
      ],
    },
    {
      id: 'ADR-007',
      title: 'Commutative Collective Transformers for Deterministic Sharding Commit',
      status: 'Accepted',
      context: 'Multi-mesh collective operations must yield identical global sharding states regardless of topological scheduling order.',
      decision: 'Define collective transformers T_m that transition axis m to Replicated, and formally verify operator commutativity.',
      consequences: ['Topology-invariant global sharding commitment', 'Eliminates deadlocks and non-determinism in multi-axis reduction pipelines'],
      supersedes: null,
      links: [
        { uri: 'specs/p2c_petc_v12.md', kind: 'SpecificationDoc', description: 'P²C PETC v1.2 Section 2.3 Collective Transformers' },
        { uri: 'lean/Multiplicity/PETC.lean', kind: 'LeanDeclaration', description: 'Collective transformer commutation' },
      ],
    },
    {
      id: 'ADR-008',
      title: 'Prime Signature Canonical Monoid as Exclusive Rust Kernel Substrate',
      status: 'Accepted',
      context: 'All multiplicity computations must share a single, deterministic representation to prevent representational drift.',
      decision: 'The only permitted representation is a finitely supported map from primes to exponents with free commutative monoid structure.',
      consequences: ['Signature equality is decidable by structural comparison', 'Multiplicity product is strictly associative and commutative', 'Foreign representations must convert at kernel boundary or be rejected'],
      supersedes: null,
      links: [
        { uri: 'PhaseMirror.PrimeSignature', kind: 'LeanDeclaration', description: 'Formal specification of signature monoid' },
        { uri: 'packages/rust/multiplicity/multiplicity-core/src/signature.rs', kind: 'SourceFile', description: 'Target Rust implementation' },
      ],
    },
    {
      id: 'ADR-009',
      title: 'Mandatory Contraction Witness & Spectral Radius Verification Before Emission Gate',
      status: 'Accepted',
      context: 'Unconstrained recurrence or agent emission can produce unbounded Lyapunov drift.',
      decision: 'No signal may pass the Emission Gate unless a machine-checkable ContractionWitness proves spectral radius < 1.',
      consequences: ['EmissionGate returns Suppress or Hold when no valid witness present', 'SpectralGovernor is sole authority to mint ContractionWitness', 'Any bypass constitutes a hard kernel violation'],
      supersedes: null,
      links: [
        { uri: 'PhaseMirror.SpectralGovernor', kind: 'LeanDeclaration', description: 'Formal contract of spectral governor' },
        { uri: 'packages/rust/ramanujan-multiplicity', kind: 'SourceFile', description: 'Witness generation site' },
      ],
    },
    {
      id: 'ADR-010',
      title: 'Axiom-Clean Kernel Boundary and Manifested Proof Debt Policy',
      status: 'Accepted',
      context: 'Unmanifested sorry, todo!, or commented-out critical paths create verification leakage.',
      decision: 'The kernel boundary must be axiom-clean. Every open proof obligation must be fully discharged or explicitly manifested.',
      consequences: ['CI rejects any increase in manifested or unmanifested sorry count', 'Kernel startup performs static honesty manifest check', 'Research surfaces may contain open obligations only when quarantined'],
      supersedes: null,
      links: [
        { uri: '.github/workflows/adr-verify.yml', kind: 'SpecificationDoc', description: 'Honesty audit workflow' },
        { uri: 'docs/CURRENT_TRUTH.md', kind: 'SpecificationDoc', description: 'Living honesty ledger' },
      ],
    },
  ],
  governance: [
    {
      id: 'ADR-0013',
      title: 'UOR Civic Infrastructure',
      status: 'Accepted',
      context: 'The Foundry DAO progresses through three strategic developmental epochs.',
      decision: 'Adopt the canonical BCS wire format for the UnsignedCrmfEnvelope, the PWEH integrity binding, the contractivity gate, and fail-closed governance.',
      consequences: ['Deterministic cross-language canonical byte streams', 'Path-dependent tamper resistance across PWEH chain', 'Fail-closed governance: unmodeled defect halts L0', 'Integer-only wire: floating point structurally excluded'],
      supersedes: null,
      links: [
        { uri: 'docs/papers/UOR Civic Infrastructure_.docx', kind: 'SourceFile', description: 'UOR Civic Infrastructure' },
        { uri: 'lean/MTPI/ADR0013.lean', kind: 'SourceFile', description: 'Canonical BCS wire format formalized as Lean 4 theorems' },
        { uri: 'packages/rust/crmf/src/canonical.rs', kind: 'SourceFile', description: 'Canonical BCS wire format (Kani-verified)' },
      ],
    },
    {
      id: 'ADR-0017',
      title: 'Reinitialization — 90-Day Operating Plan and Volunteer Talent Model',
      status: 'Accepted',
      context: 'UOR Foundation must reinitialize under volunteer-led, no-funding assumption.',
      decision: 'Adopt 90-Day Operating Plan: one primary objective, Day Zero two-week mobilization, five workstreams max.',
      consequences: ['Execution capped by WIP limits', 'No-funding assumption binding', 'Cycle either closes deliverables or fails exit rule loudly'],
      supersedes: null,
      links: [
        { uri: 'docs/papers/UOR_Final_90_Day_Operating_Plan.docx', kind: 'SourceFile', description: '90-Day Operating Plan' },
      ],
    },
    {
      id: 'ADR-0113',
      title: 'Universal Closure Calculator — Unified Kernel Surface',
      status: 'Accepted',
      context: 'The Foundry hosts several independently verified surfaces with no single accepted decision binding them.',
      decision: 'Adopt the UCC sextuple as the canonical integration surface and wire every verified Foundry surface to it.',
      consequences: ['Every closure call returns Closure, Defect, Receipt, and Levers', 'Unlawful transitions fail closed at L0', 'Proof debt is explicit and bounded', 'Integer-only wire: floating point excluded'],
      supersedes: null,
      links: [
        { uri: 'docs/specs/ucc_sextuple_v1.md', kind: 'SpecificationDoc', description: 'Canonical sextuple wire format' },
        { uri: 'contracts/universal_closure.yaml', kind: 'SpecificationDoc', description: 'Declarative associator tolerance' },
        { uri: 'ADR/Theorems/Homestead_UCC_Care_Bridge.lean', kind: 'LeanDeclaration', description: 'L0 gate soundness' },
        { uri: 'ADR/Properties.lean', kind: 'LeanDeclaration', description: 'Property/concurrency tests' },
        { uri: 'scripts/check_adr_sorry.py', kind: 'SourceFile', description: 'Manifest-aware proof-debt gate' },
      ],
    },
    {
      id: 'ADR-0151',
      title: 'OSCAL and PrismPM Mapping and Traceability',
      status: 'Accepted',
      context: 'OSCAL provides a public grammar for compliance but alone permits silent exclusions. PrismPM provides the non-weakenable C-control baseline. Current scope is portal inventory at Modeled ceiling.',
      decision: 'Use OSCAL as filing cabinet, PrismPM as the lock. Overlay cannot exclude C-controls (C-10). Implemented/Assessed/Accepted/Certified forbidden on current inventory. 5-step traceability: Requirement → Party → Model → Subject → Evidence.',
      consequences: ['Fail-closed on weakening (F-01, F-07)', 'Visible POA&Ms for modeled-vs-deployed divergence', 'Accurate scope claims; Foundation is not one SSP', 'Certified-by-Prism and FedRAMP-ready retired', 'Advancing above Modeled requires recorded rung-change'],
      supersedes: null,
      links: [
        { uri: 'papers/OSCAL_PrismPM_Mapping_and_Traceability_v1.0.docx', kind: 'SourceFile', description: 'Source Document' },
        { uri: 'artifacts/adr/ADR-0123-OSCAL-PrismPM-Mapping.md', kind: 'SourceFile', description: 'OSCAL PrismPM Mapping ADR' },
        { uri: 'ADR/ADR_0151_OSCAL_PrismPM_Mapping.lean', kind: 'LeanDeclaration', description: 'Formal ADR definition and claim-ladder proofs' },
      ],
    },
    {
      id: 'ADR-0152',
      title: 'PIRTM and Foundry Kiln and Clay',
      status: 'Accepted',
      context: 'PIRTM is the dynamical substrate (prime-indexed tensors, contractive bounds). Foundry is the open bench. Year-one product is UCC, not PIRTM. Calling them already "uncheatable certified architecture" skips the claim ladder.',
      decision: 'Keep computational L0 (c < 1, ||G||1 < 1.0) off civic L0. Primes index primitives not members. Exact rationals at kernel boundary (ADR-001, N=1024). SIG_GOV_KILL stays WardMonitor. NODE_CAP = 12 is the halt.',
      consequences: ['Clean plane separation: computational vs civic L0', 'No vote weight from exponents', 'SIG_GOV_KILL reserved for WardMonitor', 'Float in SedonaRiskModel named as continuing defect', 'No Hall of Record until SS-001 split-ESI is built'],
      supersedes: null,
      links: [
        { uri: 'papers/PIRTM_and_Foundry_Kiln_and_Clay_v1.0.docx', kind: 'SourceFile', description: 'Source Document' },
        { uri: 'ADR/ADR_0152_PIRTM_Foundry_Kiln_Clay.lean', kind: 'LeanDeclaration', description: 'Formal ADR definition and plane-separation proofs' },
        { uri: 'Governance/ADR/accepted/ADR-0153-Phase_Mirror_Five_Step_Loop_an.md', kind: 'SpecificationDoc', description: 'Adjacent compilers ADR' },
      ],
    },
    {
      id: 'ADR-0153',
      title: 'Phase Mirror Five Step Loop and PWEH',
      status: 'Accepted',
      context: 'The five-step diagnostic loop extracts claims, maps cracks, produces levers, and asks one precision question. PWEH is a proposed receipt spine, not one coat with the Mirror.',
      decision: 'Keep five-step loop (Extract, Map, Rank, Produce, Precision Question) as diagnostic. Keep PWEH as proposed spine (PM-PWEH-001). SIG_GOV_KILL stays WardMonitor. BN254+Ed25519 labeled pre-quantum. Contractivity stays UCC.',
      consequences: ['Clean separation: Mirror (diagnostic) and PWEH (receipt) are distinct machines', 'No silent halts; SIG_GOV_KILL reserved for WardMonitor', 'BN254+Ed25519 labeled pre-quantum', 'Contractivity isolation: Mirror does not evaluate Lipschitz', 'UnsignedCrmfEnvelope remains specification draft'],
      supersedes: null,
      links: [
        { uri: 'papers/Phase_Mirror_Five_Step_Loop_and_PWEH_v1.0.docx', kind: 'SourceFile', description: 'Source Document' },
        { uri: 'ADR/ADR_0153_Five_Step_Loop_PWEH.lean', kind: 'LeanDeclaration', description: 'Formal ADR definition and loop invariant proofs' },
      ],
    },
    {
      id: 'ADR-0154',
      title: 'Phase Mirror Honesty Engine and Foundry Orchestration',
      status: 'Accepted',
      context: 'Phase Mirror is a build-time diagnostic that names dissonance and pins owners. It is not a runtime firewall, token minter, or halt mechanism. SIG_GOV_KILL stays WardMonitor. NODE_CAP = 12.',
      decision: 'Structural replacement of management: zero-boss orchestration with intent as inspectable artifact. L0/L1/L2 callable oracle tiers (100ns, 1ms, 100ms). Three-way metric card. Credits are not interest. person_id excluded from prime ledger.',
      consequences: ['Zero boss: intent decoupled from execution', 'No token politics: Phase Mirror does not mint/freeze tokens', 'Halt reservation: SIG_GOV_KILL/L0_HALT stay on their respective machines', 'Node cap integrity: NODE_CAP=12, Mirror does not raise to 27', 'Economic honesty: metric card columns do not average'],
      supersedes: null,
      links: [
        { uri: 'papers/Phase_Mirror_Honesty_Engine_and_Foundry_Orchestration_v1.0.docx', kind: 'SourceFile', description: 'Source Document' },
        { uri: 'ADR/ADR_0154_PHonesty_Orchestration.lean', kind: 'LeanDeclaration', description: 'Formal ADR definition and zero-boss proofs' },
      ],
    },
    {
      id: 'ADR-0155',
      title: 'PrismPM OSCAL Workflow Cryptographic Module',
      status: 'Accepted',
      context: 'PrismPM is the SDK and lifecycle compiler, not a GRC website or badge printer. Certified is off the lock bar (C-24). Portal inventory stays Modeled only. A crypto module is a second bounded system.',
      decision: 'Seven CLI verbs: model check, catalog pin, profile resolve, oscal export, chain show, ladder, mirror. FIPS catalogs are additive imports. prismpm export never emits Certified (F-16). Hosting provider unbound (C-11). person_id not in Hundian K.',
      consequences: ['Clean tool separation: PrismPM is the compiler, not a badge printer', 'Profile integrity: imports additive, silent deletion is F-01', 'Portal integrity: stays Modeled only until C-08/C-11 bindings', 'Economic honesty: Certified does not print from any prismpm verb', 'Node cap integrity: NODE_CAP=12, no raise to 27'],
      supersedes: null,
      links: [
        { uri: 'papers/PrismPM_OSCAL_Workflow_Cryptographic_Module_v1.0.docx', kind: 'SourceFile', description: 'Source Document' },
        { uri: 'ADR/ADR_0155_OSCAL_Workflow_Crypto_Module.lean', kind: 'LeanDeclaration', description: 'Formal ADR definition and workflow guardrail proofs' },
        { uri: 'Governance/ADR/accepted/ADR-0151-OSCAL_PrismPM_Mapping_and_Trac.md', kind: 'SpecificationDoc', description: 'Parent lock: PrismPM-BP-001, OSCAL-PM-001' },
      ],
    },
    {
      id: 'ADR-0156',
      title: 'PrismPM PIRTM Adjacent Compilers',
      status: 'Accepted',
      context: 'PrismPM (process law) and PIRTM (dynamical law) are adjacent, not fused. Both can say no, neither says yes for the other. Proof-to-Executable is a research paradigm.',
      decision: 'Keep PrismPM and PIRTM as distinct adjacent compilers. PrismPM owns F-01-F-18, PIRTM owns compile/link refuse. WardMonitor owns SIG_GOV_KILL. H2P is draft (H2P-draft). prismpm never prints Certified (F-16).',
      consequences: ['Jurisdictional integrity: four no names, one per owner', 'No false certainty: Proof-to-Executable is research paradigm', 'Envelope draft: H2P remains H2P-draft until ADR-bound', 'Open core: handwritten code ban is kiln aspiration, hundian keeps bench open', 'Portal stays Modeled only; prismpm never prints Certified'],
      supersedes: null,
      links: [
        { uri: 'papers/PrismPM_PIRTM_Adjacent_Compilers_v1.0.docx', kind: 'SourceFile', description: 'Source Document' },
        { uri: 'ADR/ADR_0156_Adjacent_Compilers.lean', kind: 'LeanDeclaration', description: 'Formal ADR definition and jurisdiction proofs' },
        { uri: 'Governance/ADR/accepted/ADR-0155-PrismPM_OSCAL_Workflow_Cryptog.md', kind: 'SpecificationDoc', description: 'Parent workflow' },
      ],
    },
    {
      id: 'ADR-0157',
      title: 'Ratify Board Resolution and Capital Authorization',
      status: 'Accepted',
      context: 'Members ratify, not a shadow board. USD 1,000,000 ceiling for Livermore parcel (resolves USD 750k/1M drift). Phase 2 barn excluded. Four doors only. Dual-control at USD 2,500.',
      decision: 'Member resolution packet (BR-CA-001). Single ceiling after drift resolved. Dual-control on every wire over USD 2,500, no closing exception. Title in association. Mandatory quarterly three-way card (dignity, outcome, solvency). Kill-switch: two consecutive fails pause draws.',
      consequences: ['Decentralized ratification: members vote after 14-day notice', 'Strict capital control: USD 2,500 dual-control, four-door funding, no exception', 'Asset protection: association title locks prevent equity extraction', 'Automated accountability: kill-switch halts on dignity/outcome failure'],
      supersedes: null,
      links: [
        { uri: 'papers/Ratify_Board_Resolution_and_Capital_Authorization_v1.0.docx', kind: 'SourceFile', description: 'Source Document' },
        { uri: 'ADR/ADR_0157_Ratify_Resolution_Capital.lean', kind: 'LeanDeclaration', description: 'Formal ADR definition and capital-control proofs' },
        { uri: 'Governance/ADR/accepted/ADR-0151-OSCAL_PrismPM_Mapping_and_Trac.md', kind: 'SpecificationDoc', description: 'Parent: OSCAL/PrismPM claim ladder' },
      ],
    },
    {
      id: 'ADR-0158',
      title: 'Sedona Spine Records and Kiln Privacy',
      status: 'Accepted',
      context: 'The Sedona Spine retention engine manages ESI preservation risk across distributed nodes. The kiln privacy boundary separates record classification metadata from record content at the kernel boundary. Retention schedules must be fail-closed.',
      decision: 'Sedona Spine retains only records with explicit machine-classifiable schedules. Records without classification fall to quarantine. The kiln privacy boundary enforces metadata-content isolation. All retention decisions require a UCC receipt link.',
      consequences: ['Fail-closed retention: unclassified records are quarantined', 'Privacy boundary: classification metadata isolated from content', 'Audit surface: every retention decision has a UCC receipt', 'No default retention: absence of schedule is refusal', 'Kiln boundary: no metadata leaks across the privacy seal'],
      supersedes: null,
      links: [
        { uri: 'papers/Sedona_Spine_Records_Kiln_Privacy_v1.0.docx', kind: 'SourceFile', description: 'Source Document' },
        { uri: 'ADR/ADR_0158_Sedona_Spine_Records_Kiln_Priv.lean', kind: 'LeanDeclaration', description: 'Formal ADR definition and privacy-boundary proofs' },
        { uri: 'ADR/lex.lean', kind: 'LeanDeclaration', description: 'Shared lexical formalization primitives' },
      ],
    },
    {
      id: 'ADR-0159',
      title: 'Two Persons, Not Present Tense, 501(c)(3)',
      status: 'Accepted',
      context: 'The 501(c)(3) form requires no single person controls capital disposition. The two-person rule requires two distinct legal persons for any wire, halt, or certification. The present-tense rule rejects resolutions not binding persons at execution time.',
      decision: 'Every capital action requires two distinct legal persons in present tense. person_id is excluded from prime ledger as a seating key. Conditional or future-tense authorizations are refused. SIG_GOV_KILL requires two signatures.',
      consequences: ['No single-person capital moves: dual-control enforced', 'Present-tense binding: conditional authorizations refused', 'Person exclusion: person_id never a seating key', 'SIG_GOV_KILL requires two distinct person signatures', '501(c)(3) compliance: no private inurement'],
      supersedes: null,
      links: [
        { uri: 'papers/Two_Persons_Not_Present_Tense_501c3_v1.0.docx', kind: 'SourceFile', description: 'Source Document' },
        { uri: 'ADR/ADR_0159_Two_Persons_501c3.lean', kind: 'LeanDeclaration', description: 'Formal ADR definition and dual-control proofs' },
        { uri: 'ADR/lex.lean', kind: 'LeanDeclaration', description: 'DualControlThreshold = 2500' },
      ],
    },
    {
      id: 'ADR-0160',
      title: 'UCC and Foundry Kernel on the Same L0',
      status: 'Accepted',
      context: 'The UCC sextuple defines the canonical integration surface for verified Foundry surfaces. The Foundry kernel operates on civic L0 with integer-only wire. UCC and kernel share L0, but UCC is the integration surface, not a new L0 plane.',
      decision: 'UCC is the sole integration surface between Foundry kernel and civic L0. No new L0 widening is permitted. Kernel contractivity grounded in verified receipts, not float sums. Float manifests remain a continuing defect.',
      consequences: ['L0 integrity: UCC is the integration surface', 'Integer-only wire: floating point excluded', 'Contractivity: kernel receipts machine-checkable', 'Dual-control: USD 2,500 enforced at every UCC boundary', 'Kill-switch: two consecutive fails pause draws'],
      supersedes: null,
      links: [
        { uri: 'papers/UCC_and_Foundry_Kernel_on_the_Same_L0_v1.0.docx', kind: 'SourceFile', description: 'Source Document' },
        { uri: 'ADR/ADR_0160_UCC_Foundry_Kernel_L0.lean', kind: 'LeanDeclaration', description: 'Formal ADR definition and L0-integration proofs' },
        { uri: 'specifications/ucc_sextuple_v1.md', kind: 'SpecificationDoc', description: 'UCC sextuple specification' },
      ],
    },
    {
      id: 'ADR-0161',
      title: 'UOR Final 90-Day Operating Plan',
      status: 'Accepted',
      context: 'UOR technology is ahead of its operating structure. The 90-Day Baseline Cycle requires Day Zero mobilization to complete before the clock starts. The cycle objective is exactly one governed, testable value-layer baseline. Scope freeze prohibits new foundations without exception.',
      decision: 'Day Zero completion records before the 90-day clock commences. The cycle produces exactly one Core Value Profile, canonical vectors, verifier, and evaluated pilot. Scope freeze is binding; exceptions require explicit ADR.',
      consequences: ['Clock integrity: 90 days start after recorded Day Zero', 'Single baseline: exactly one value-layer baseline per cycle', 'Scope freeze: no new foundations without exception', 'Evidence posture: E0-E6 scale with owner and limitations', 'Exit rule: below 3 active volunteers pauses release claim'],
      supersedes: null,
      links: [
        { uri: 'papers/UOR_Final_90_Day_Operating_Plan_v1.0.docx', kind: 'SourceFile', description: 'Source Document' },
        { uri: 'ADR/ADR_0161_90_Day_Operating_Plan.lean', kind: 'LeanDeclaration', description: 'Formal ADR definition and cycle-clock proofs' },
        { uri: 'ADR/lex.lean', kind: 'LeanDeclaration', description: 'NodeCap = 12 constant' },
      ],
    },
    {
      id: 'ADR-0162',
      title: 'UOR Final Executive Decision Brief',
      status: 'Accepted',
      context: 'UOR technology is ahead of its operating structure. The Conditional Go procedure establishes Day Zero, the 90-day baseline cycle, scope freeze, and evidence posture. The decision is binary: go or no-go, with no partial authorizations.',
      decision: 'Conditional Go: upon Day Zero completion, the 90-day clock commences and scope freeze is binding. If Day Zero conditions fail, no partial authorization is issued. Explicit non-claims are binding.',
      consequences: ['Binary gate: no partial authorizations from Conditional Go', 'Scope freeze: new foundations require explicit exception', 'Evidence posture: E0-E6 scale with owner and limitations', 'Non-claims are binding: security/AI claims refused', 'Authority: central mission, delegated technical decisions'],
      supersedes: null,
      links: [
        { uri: 'papers/UOR_Final_Executive_Decision_Brief_v1.0.docx', kind: 'SourceFile', description: 'Source Document' },
        { uri: 'ADR/ADR_0162_Executive_Decision_Brief.lean', kind: 'LeanDeclaration', description: 'Formal ADR definition and gate invariant proofs' },
        { uri: 'ADR/lex.lean', kind: 'LeanDeclaration', description: 'L0Plane and ClaimCeiling types' },
      ],
    },
    {
      id: 'ADR-0163',
      title: 'UOR Final Technology Portfolio',
      status: 'Accepted',
      context: 'UOR Foundation possesses ontology, addressing, conformance, registry, and application-model assets. Without portfolio classification, assets drift into claims of production readiness. Four classes: Normative, Reference, Experimental, Historical.',
      decision: 'Every asset must be classified into one portfolio class at baseline freeze. Only Normative and Reference assets are part of year-one product. Experimental and Historical are documented but not product surface.',
      consequences: ['Classification: every asset has exactly one portfolio class', 'Baseline integrity: only Normative/Reference enter product', 'Drift prevention: unclassified assets refused at merge', 'Evidence trace: classification links to E0-E6 evidence grade', 'Scope control: Experimental/Historical excluded from claims'],
      supersedes: null,
      links: [
        { uri: 'papers/UOR_Final_Technology_Portfolio_v1.0.docx', kind: 'SourceFile', description: 'Source Document' },
        { uri: 'ADR/ADR_0163_Technology_Portfolio.lean', kind: 'LeanDeclaration', description: 'Formal ADR definition and portfolio-class proofs' },
        { uri: 'ADR/lex.lean', kind: 'LeanDeclaration', description: 'ClaimCeiling type for portfolio classification' },
      ],
    },
    {
      id: 'ADR-0164',
      title: 'UOR Foundry and Citizen Gardens UNA',
      status: 'Accepted',
      context: 'The Foundry operates on civic L0 under the 501(c)(3) stewardship of Citizen Gardens UNA. Operator LLC manages day-to-day execution. Legal person and computational plane must remain distinct.',
      decision: 'Citizen Gardens UNA holds title; Operator LLC manages execution; Foundry operates on civic L0. Three distinct entities. person_id never a seating key. All capital moves require two persons.',
      consequences: ['Legal separation: UNA holds title, Operator LLC manages, Foundry computes', 'Plane integrity: civic L0 and computational L0 stay distinct', 'Person exclusion: person_id never binds prime ledger', 'Two-person rule: all capital moves require two legal persons', 'No sole ownership: computational artifacts cannot name legal person alone'],
      supersedes: null,
      links: [
        { uri: 'papers/UOR_Foundry_and_Citizen_Gardens_v1.0.docx', kind: 'SourceFile', description: 'Source Document' },
        { uri: 'ADR/ADR_0164_Foundry_Citizen_Gardens.lean', kind: 'LeanDeclaration', description: 'Formal ADR definition and entity-separation proofs' },
        { uri: 'Governance/ADR/accepted/ADR-0159-Two_Persons_Not_Present_Tense_.md', kind: 'SpecificationDoc', description: 'Parent: two-person rule' },
      ],
    },
    {
      id: 'ADR-0165',
      title: 'Unified Civic Infrastructure Operating Model',
      status: 'Accepted',
      context: 'The civic infrastructure must operate as a unified model on civic L0. Including Sedona Spine, WardMonitor, registry, and claim ladder. Must not absorb computational L0 or research L0-Q.',
      decision: 'Civic infrastructure operates as one unified model on civic L0. Exposes Sedona Spine, WardMonitor, registry, and UCC sextuple as four subsystems. Computational L0 and L0-Q are adjacent compilers.',
      consequences: ['Unified surface: civic L0 is one bounded model', 'No absorption: computational L0 stays adjacent', 'Subsystem integrity: four subsystems, no fifth', 'SIG_GOV_KILL stays WardMonitor', 'NODE_CAP = 12 enforced at every civic boundary'],
      supersedes: null,
      links: [
        { uri: 'papers/Unified_Civic_Infrastructure_Operating_Model_v1.0.docx', kind: 'SourceFile', description: 'Source Document' },
        { uri: 'ADR/ADR_0165_Unified_Civic_Infrastructure.lean', kind: 'LeanDeclaration', description: 'Formal ADR definition and L0-bounding proofs' },
        { uri: 'ADR/lex.lean', kind: 'LeanDeclaration', description: 'L0Plane type for civic boundary' },
      ],
    },
    {
      id: 'ADR-0166',
      title: 'Verified Action Lifecycle RI1',
      status: 'Accepted',
      context: 'Every civic action follows the RI1 lifecycle: Proposed, Modeled, Implemented, Accepted. Each rung requires a UCC receipt. Backward or skipping transitions are refused.',
      decision: 'RI1 lifecycle is strictly ordered. Transitions require a UCC receipt from the previous rung. SIG_GOV_KILL is the only backward transition, owned by WardMonitor. Phase Mirror is diagnostic only.',
      consequences: ['Ordered transitions: forward only', 'Receipt binding: each rung requires UCC receipt', 'No skipping: cannot jump rungs without recorded transition', 'Diagnostic separation: Phase Mirror does not mutate RI1', 'Kill-switch boundary: SIG_GOV_KILL is sole backward path'],
      supersedes: null,
      links: [
        { uri: 'papers/Verified_Action_Lifecycle_RI1_v1.0.docx', kind: 'SourceFile', description: 'Source Document' },
        { uri: 'ADR/ADR_0166_Verified_Action_Lifecycle.lean', kind: 'LeanDeclaration', description: 'Formal ADR definition and lifecycle-state proofs' },
        { uri: 'ADR/lex.lean', kind: 'LeanDeclaration', description: 'L0Plane enum for plane classification' },
      ],
    },
    {
      id: 'ADR-0167',
      title: 'schema.org Import Discipline',
      status: 'Accepted',
      context: 'schema.org provides public grammar for evidence metadata. It is an additive import, not a baseline. Cannot override C-controls or widen the claim ladder ceiling. Certified-by-Prism and FedRAMP-ready retired.',
      decision: 'schema.org is an additive input layer. Metadata enriches evidence records but does not widen the claim ladder or override C-controls. prismpm export never emits Certified from schema.org metadata alone.',
      consequences: ['Additive only: schema.org enriches, never overrides C-controls', 'Claim ladder integrity: schema.org cannot raise ceiling', 'No silent exclusions: missing schema fields visible', 'Certified discipline: prismpm export never emits Certified', 'Terminology hygiene: Certified-by-Prism retired'],
      supersedes: null,
      links: [
        { uri: 'papers/schema_org_Import_Discipline_v1.0.docx', kind: 'SourceFile', description: 'Source Document' },
        { uri: 'ADR/ADR_0167_schema_import.lean', kind: 'LeanDeclaration', description: 'Formal ADR definition and import-integrity proofs' },
        { uri: 'Governance/ADR/accepted/ADR-0151-OSCAL_PrismPM_Mapping_and_Trac.md', kind: 'SpecificationDoc', description: 'Parent: OSCAL/PrismPM claim ladder' },
      ],
    },
    {
      id: 'ADR-0168',
      title: 'PM-FORGE-001 — Twelve-Card Forge Workbench',
      status: 'Proposed',
      context: 'The Forge is a proposed twelve-step workbench over the five VL-001 stations. PrismPM kiln incentive is process law, not idea generation. Phase Mirror is five steps that name a contradiction. Genius v2 is unbound and refused as L0. Certified is C-24.',
      decision: 'The Forge is a workbench view, not a legal person, compiler, receipt, or ensemble. Twelve cards across four bands. Each card binds an existing artifact. No card trains weights. Refinement = re-walk of Band B on the same addressed packet.',
      consequences: ['Velocity without integrity loss: twelve cards serve velocity over seated machines', 'Genius v2 refuse is visible at the door', 'Five-step and five-link remain on separate bands', 'Refinement is re-walk, not gradient update or ensemble vote', 'G remains 0 until precision question answered by artifact'],
      supersedes: null,
      links: [
        { uri: 'artifacts/ForgeCard.lean', kind: 'SourceFile', description: 'ForgeCard.lean formalization' },
        { uri: 'artifacts/forge_card.py', kind: 'SourceFile', description: 'forge_card.py implementation' },
        { uri: 'ADR/ADR_0168_Forge_Workbench.lean', kind: 'LeanDeclaration', description: 'Formal ADR definition and forge invariant proofs' },
        { uri: 'ADR/lex.lean', kind: 'LeanDeclaration', description: 'ForgePacket and ForgeCard types' },
      ],
    },
  ],
};

export const ALL_FOUNDRY_ADRS: ADR[] = [
  ...FOUNDRY_ADR_SETS.core,
  ...FOUNDRY_ADR_SETS.governance,
];

export function countByStatus(adrs: ADR[], status: ADRStatus): number {
  return adrs.filter(a => a.status === status).length;
}

export function buildADRRegistry(adrs: ADR[]): ADRRegistry {
  const claims = adrs
    .filter(a => a.status === 'Accepted')
    .map(a => ({ owner: a.id, claim: `decision:${a.decision.substring(0, 80)}...` }));
  return { adrs, claims };
}

export const FOUNDRY_AUDIT_TRAIL: Array<{ ADR_ID: string; Action: string; Timestamp: string; Status: string; Author: string }> = [
  { ADR_ID: 'ADR-001', Action: 'Superseded', Timestamp: '2026-03-01T10:00:00Z', Status: 'Superseded', Author: 'PhaseMirror' },
  { ADR_ID: 'ADR-002', Action: 'Accepted', Timestamp: '2026-01-15T14:30:00Z', Status: 'Accepted', Author: 'Foundry Council' },
  { ADR_ID: 'ADR-003', Action: 'Accepted', Timestamp: '2026-02-01T09:00:00Z', Status: 'Accepted', Author: 'Foundry Council' },
  { ADR_ID: 'ADR-004', Action: 'Accepted', Timestamp: '2026-02-15T11:00:00Z', Status: 'Accepted', Author: 'P²C PETC Committee' },
  { ADR_ID: 'ADR-005', Action: 'Accepted', Timestamp: '2026-02-20T16:00:00Z', Status: 'Accepted', Author: 'P²C PETC Committee' },
  { ADR_ID: 'ADR-006', Action: 'Accepted', Timestamp: '2026-03-01T08:00:00Z', Status: 'Accepted', Author: 'P²C PETC Committee' },
  { ADR_ID: 'ADR-007', Action: 'Accepted', Timestamp: '2026-03-05T12:00:00Z', Status: 'Accepted', Author: 'Sharding Working Group' },
  { ADR_ID: 'ADR-008', Action: 'Accepted', Timestamp: '2026-03-10T15:00:00Z', Status: 'Accepted', Author: 'Multiplicity Team' },
  { ADR_ID: 'ADR-009', Action: 'Accepted', Timestamp: '2026-03-15T10:00:00Z', Status: 'Accepted', Author: 'SpectralGovernor' },
  { ADR_ID: 'ADR-010', Action: 'Accepted', Timestamp: '2026-03-20T14:00:00Z', Status: 'Accepted', Author: 'Foundry Council' },
  { ADR_ID: 'ADR-0013', Action: 'Accepted', Timestamp: '2026-04-01T09:00:00Z', Status: 'Accepted', Author: 'Civic Infrastructure Team' },
  { ADR_ID: 'ADR-0113', Action: 'Accepted', Timestamp: '2026-05-01T12:00:00Z', Status: 'Accepted', Author: 'UCC Integration Committee' },
  { ADR_ID: 'ADR-0151', Action: 'Accepted', Timestamp: '2026-09-17T12:00:00Z', Status: 'Accepted', Author: 'PhaseMirror Council' },
  { ADR_ID: 'ADR-0152', Action: 'Accepted', Timestamp: '2026-09-17T12:00:00Z', Status: 'Accepted', Author: 'PhaseMirror Council' },
  { ADR_ID: 'ADR-0153', Action: 'Accepted', Timestamp: '2026-09-18T12:00:00Z', Status: 'Accepted', Author: 'PhaseMirror Council' },
  { ADR_ID: 'ADR-0154', Action: 'Accepted', Timestamp: '2026-09-17T12:00:00Z', Status: 'Accepted', Author: 'PhaseMirror Council' },
  { ADR_ID: 'ADR-0155', Action: 'Accepted', Timestamp: '2026-09-18T12:00:00Z', Status: 'Accepted', Author: 'PhaseMirror Council' },
  { ADR_ID: 'ADR-0156', Action: 'Accepted', Timestamp: '2026-09-18T12:00:00Z', Status: 'Accepted', Author: 'PhaseMirror Council' },
  { ADR_ID: 'ADR-0157', Action: 'Accepted', Timestamp: '2026-09-17T12:00:00Z', Status: 'Accepted', Author: 'PhaseMirror Council' },
  { ADR_ID: 'ADR-0158', Action: 'Accepted', Timestamp: '2026-09-20T10:00:00Z', Status: 'Accepted', Author: 'PhaseMirror Council' },
  { ADR_ID: 'ADR-0159', Action: 'Accepted', Timestamp: '2026-09-20T10:00:00Z', Status: 'Accepted', Author: 'PhaseMirror Council' },
  { ADR_ID: 'ADR-0160', Action: 'Accepted', Timestamp: '2026-09-20T10:00:00Z', Status: 'Accepted', Author: 'PhaseMirror Council' },
  { ADR_ID: 'ADR-0161', Action: 'Accepted', Timestamp: '2026-09-21T10:00:00Z', Status: 'Accepted', Author: 'PhaseMirror Council' },
  { ADR_ID: 'ADR-0162', Action: 'Accepted', Timestamp: '2026-09-21T10:00:00Z', Status: 'Accepted', Author: 'PhaseMirror Council' },
  { ADR_ID: 'ADR-0163', Action: 'Accepted', Timestamp: '2026-09-21T10:00:00Z', Status: 'Accepted', Author: 'PhaseMirror Council' },
  { ADR_ID: 'ADR-0164', Action: 'Accepted', Timestamp: '2026-09-22T10:00:00Z', Status: 'Accepted', Author: 'PhaseMirror Council' },
  { ADR_ID: 'ADR-0165', Action: 'Accepted', Timestamp: '2026-09-22T10:00:00Z', Status: 'Accepted', Author: 'PhaseMirror Council' },
  { ADR_ID: 'ADR-0166', Action: 'Accepted', Timestamp: '2026-09-22T10:00:00Z', Status: 'Accepted', Author: 'PhaseMirror Council' },
  { ADR_ID: 'ADR-0167', Action: 'Accepted', Timestamp: '2026-09-23T10:00:00Z', Status: 'Accepted', Author: 'PhaseMirror Council' },
  { ADR_ID: 'ADR-0168', Action: 'Proposed', Timestamp: '2026-09-26T10:00:00Z', Status: 'Proposed', Author: 'PhaseMirror Council' },
];
